# Comparison against tool-based anomaly-based approaches

## Single-chain scope

### Test 1: Full removal of bridge cases (no training leakage)

In [1]:
import pandas as pd
from pathlib import Path

# Adjust depending on where your test outputs are stored
BASE_DIR = Path("/home/gonca/Documents/GitHub/IST-Thesis/BridgeDefender/outputs")
SINGLE_CHAIN_EVALS_DIR = BASE_DIR / "single-internaltx-eval-comparison-ronin12-omni-nomad-polyn-qubit-harmony-thor123-meter-hypr-xbridge"
CCTX_EVALS_DIR = BASE_DIR / "cctx-eval-comparison-ronin12-omni-nomad-polyn-qubit-harmony-thor123-meter-hypr-xbridge"

# label -> inference run folder
RUNS = {
    "$\\mathbb{A}$ (single-chain)": SINGLE_CHAIN_EVALS_DIR / "train_epochs100_augment0_lr0.005_nosf_es15_ts0_deepsad_comparison_xchainwatcher_leakfree__202608071212/inference_deepsad-comparison-xchainwatcher-leakfree_202608071217",
    "$\\mathbb{B}$ (single-chain)": SINGLE_CHAIN_EVALS_DIR / "train_epochs100_augment0_lr0.005_nosf_es15_ts0_deepsad_comparison_xscope_leakfree__202608071226/inference_deepsad-comparison-xscope-leakfree_202608071235",
    "$\\mathbb{B}$ (cross-chain)": CCTX_EVALS_DIR / "train_epochs100_augment0_lr0.002_nosf_es15_ts0_deepsad_comparison_xscope_leakfree__202608071414/inference_deepsad-comparison-xscope-leakfree_202608071431",
}

METRIC_COLS = [
    "loss", "accuracy",
    "precision_normal", "recall_normal", "f1_normal",
    "precision_anomaly", "recall_anomaly", "f1_anomaly", "f2_anomaly",
    "roc_auc", "pr_auc", "mcc",
]

In [2]:
def load_eval_stats(run_name: str, run_dir: Path) -> pd.DataFrame:
    df = pd.read_csv(run_dir / "eval_stats.csv")
    df.insert(0, "test", run_name)
    return df

all_stats = pd.concat(
    [load_eval_stats(name, path) for name, path in RUNS.items()],
    ignore_index=True,
)
all_stats

,test,fold,loss,accuracy,precision_normal,recall_normal,f1_normal,precision_anomaly,recall_anomaly,f1_anomaly,f2_anomaly,roc_auc,pr_auc,mcc,threshold
0,$\mathbb{A}$ (single-chain),fold_1,0.240153,0.730874,0.775602,0.914742,0.839446,0.294118,0.118343,0.168776,0.134409,0.530285,0.295439,0.048028,0.013945
1,$\mathbb{A}$ (single-chain),fold_2,0.241906,0.785519,0.851211,0.873890,0.862401,0.538961,0.491124,0.513932,0.500000,0.776903,0.413017,0.377384,0.019036
2,$\mathbb{A}$ (single-chain),fold_3,0.247396,0.663934,0.808967,0.737123,0.771375,0.324201,0.420118,0.365979,0.396648,0.741957,0.387925,0.144705,0.017152
3,$\mathbb{A}$ (single-chain),fold_4,0.245782,0.501366,0.693359,0.630551,0.660465,0.054545,0.071006,0.061697,0.066964,0.542088,0.245348,-0.274292,0.007157
4,$\mathbb{A}$ (single-chain),fold_5,0.267460,0.769126,0.769126,1.000000,0.869498,0.000000,0.000000,0.000000,0.000000,0.842770,0.554063,0.000000,1.912453
5,$\mathbb{B}$ (single-chain),fold_1,0.805984,0.511111,0.083333,1.000000,0.153846,1.000000,0.488372,0.656250,0.544041,0.488372,0.972888,0.201737,0.023941
6,$\mathbb{B}$ (single-chain),fold_2,0.810575,0.177778,0.051282,1.000000,0.097561,1.000000,0.139535,0.244898,0.168539,0.488372,0.972888,0.084591,0.179994
7,$\mathbb{B}$ (single-chain),fold_3,0.792762,0.666667,0.117647,1.000000,0.210526,1.000000,0.651163,0.788732,0.700000,1.000000,1.000000,0.276780,0.026368
8,$\mathbb{B}$ (single-chain),fold_4,0.802687,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.012844
9,$\mathbb{B}$ (single-chain),fold_5,0.822618,0.177778,0.051282,1.000000,0.097561,1.000000,0.139535,0.244898,0.168539,0.488372,0.972888,0.084591,0.022265
10,$\mathbb{B}$ (cross-chain),fold_1,0.692427,0.542857,0.272727,0.272727,0.272727,0.666667,0.666667,0.666667,0.666667,0.181818,0.543380,-0.060606,0.013793
11,$\mathbb{B}$ (cross-chain),fold_2,0.700899,0.314286,0.314286,1.000000,0.478261,0.000000,0.000000,0.000000,0.000000,0.242424,0.581510,0.000000,0.754201
12,$\mathbb{B}$ (cross-chain),fold_3,0.750470,0.228571,0.250000,0.727273,0.372093,0.000000,0.000000,0.000000,0.000000,0.000000,0.492887,-0.452267,0.433660
13,$\mathbb{B}$ (cross-chain),fold_4,2.003427,0.400000,0.307692,0.727273,0.432432,0.666667,0.250000,0.363636,0.285714,0.238636,0.664017,-0.024140,0.226210
14,$\mathbb{B}$ (cross-chain),fold_5,18.646734,0.228571,0.250000,0.727273,0.372093,0.000000,0.000000,0.000000,0.000000,0.000000,0.499174,-0.452267,0.090001

In [3]:
summary = all_stats.groupby("test")[METRIC_COLS].agg(["mean", "var"])
summary

                                 loss             accuracy            \
                                 mean        var      mean       var
test
$\mathbb{A}$ (single-chain)  0.248539   0.000120  0.690164  0.013329
$\mathbb{B}$ (cross-chain)   4.558791  62.333861  0.342857  0.017551
$\mathbb{B}$ (single-chain)  0.806925   0.000120  0.506667  0.121333

                            precision_normal           recall_normal  \
                                        mean       var          mean
test
$\mathbb{A}$ (single-chain)         0.779653  0.003388      0.831261
$\mathbb{B}$ (cross-chain)          0.278941  0.000947      0.690909
$\mathbb{B}$ (single-chain)         0.260709  0.171550      1.000000

                                      f1_normal            ... f1_anomaly  \
                                  var      mean       var  ...       mean
test                                                       ...
$\mathbb{A}$ (single-chain)  0.021601  0.800637  0.007642  ...   0.222077
$\mathbb{B}$ (cross-chain)   0.068595  0.385521  0.005971  ...   0.206061
$\mathbb{B}$ (single-chain)  0.000000  0.311899  0.150155  ...   0.586956

                                      f2_anomaly             roc_auc  \
                                  var       mean       var      mean
test
$\mathbb{A}$ (single-chain)  0.045942   0.219604  0.047187  0.686800
$\mathbb{B}$ (cross-chain)   0.091093   0.190476  0.086168  0.132576
$\mathbb{B}$ (single-chain)  0.112532   0.516224  0.127589  0.693023

                                         pr_auc                 mcc
                                  var      mean       var      mean       var
test
$\mathbb{A}$ (single-chain)  0.020232  0.379158  0.014182  0.059165  0.055850
$\mathbb{B}$ (cross-chain)   0.015223  0.556194  0.004922 -0.197856  0.054403
$\mathbb{B}$ (single-chain)  0.078529  0.983733  0.000221  0.329540  0.147158

[3 rows x 24 columns]

In [4]:
summary_flat = summary.copy()
summary_flat.columns = [f"{metric}_{stat}" for metric, stat in summary_flat.columns]
summary_flat = summary_flat.reindex(RUNS.keys())  # preserve the order defined in RUNS
summary_flat = summary_flat.reset_index()
summary_flat

,test,loss_mean,loss_var,accuracy_mean,accuracy_var,precision_normal_mean,precision_normal_var,recall_normal_mean,recall_normal_var,f1_normal_mean,...,f1_anomaly_mean,f1_anomaly_var,f2_anomaly_mean,f2_anomaly_var,roc_auc_mean,roc_auc_var,pr_auc_mean,pr_auc_var,mcc_mean,mcc_var
0,$\mathbb{A}$ (single-chain),0.248539,0.000120,0.690164,0.013329,0.779653,0.003388,0.831261,0.021601,0.800637,...,0.222077,0.045942,0.219604,0.047187,0.686800,0.020232,0.379158,0.014182,0.059165,0.055850
1,$\mathbb{B}$ (single-chain),0.806925,0.000120,0.506667,0.121333,0.260709,0.171550,1.000000,0.000000,0.311899,...,0.586956,0.112532,0.516224,0.127589,0.693023,0.078529,0.983733,0.000221,0.329540,0.147158
2,$\mathbb{B}$ (cross-chain),4.558791,62.333861,0.342857,0.017551,0.278941,0.000947,0.690909,0.068595,0.385521,...,0.206061,0.091093,0.190476,0.086168,0.132576,0.015223,0.556194,0.004922,-0.197856,0.054403

In [221]:
# latex_table = summary_flat.round(4).to_latex(
#     index=False,
#     escape=True,
#     caption="Mean and variance of evaluation metrics per test.",
#     label="tab:eval-summary",
# )
# print(latex_table)

In [5]:
def fmt_mean_var(mean, var, decimals=4, percent=False):
    if percent:
        mean *= 100
        var *= 100
    suffix = "\\%" if percent else ""
    return f"{mean:05.{decimals}f} ± {var:05.{decimals}f}{suffix}"

combined = pd.DataFrame({"test": summary_flat["test"]})
for metric in METRIC_COLS:
    combined[metric] = [
        fmt_mean_var(m, v, decimals=2 if metric not in ["loss"] else 4, percent=True if metric not in ["loss"] else False)
        for m, v in zip(summary_flat[f"{metric}_mean"], summary_flat[f"{metric}_var"])
    ]

combined

,test,loss,accuracy,precision_normal,recall_normal,f1_normal,precision_anomaly,recall_anomaly,f1_anomaly,f2_anomaly,roc_auc,pr_auc,mcc
0,$\mathbb{A}$ (single-chain),0.2485 ± 0.0001,69.02 ± 01.33\%,77.97 ± 00.34\%,83.13 ± 02.16\%,80.06 ± 00.76\%,24.24 ± 04.78\%,22.01 ± 04.86\%,22.21 ± 04.59\%,21.96 ± 04.72\%,68.68 ± 02.02\%,37.92 ± 01.42\%,05.92 ± 05.58\%
1,$\mathbb{B}$ (single-chain),0.8069 ± 0.0001,50.67 ± 12.13\%,26.07 ± 17.15\%,100.00 ± 00.00\%,31.19 ± 15.02\%,100.00 ± 00.00\%,48.37 ± 13.29\%,58.70 ± 11.25\%,51.62 ± 12.76\%,69.30 ± 07.85\%,98.37 ± 00.02\%,32.95 ± 14.72\%
2,$\mathbb{B}$ (cross-chain),4.5588 ± 62.3339,34.29 ± 01.76\%,27.89 ± 00.09\%,69.09 ± 06.86\%,38.55 ± 00.60\%,26.67 ± 13.33\%,18.33 ± 08.47\%,20.61 ± 09.11\%,19.05 ± 08.62\%,13.26 ± 01.52\%,55.62 ± 00.49\%,-19.79 ± 05.44\%

In [6]:
import yaml

def load_dataset_stats(run_dir: Path) -> dict:
    with open(run_dir / "params.yaml") as f:
        params = yaml.safe_load(f)
    stats = params["dataset"]["stats"]
    return {
        "total_samples": stats["total_samples"],
        "anomaly_samples": stats["anomaly_samples"],
    }

dataset_stats = pd.DataFrame(
    [{"test": name, **load_dataset_stats(path)} for name, path in RUNS.items()]
)

combined = combined.merge(dataset_stats, on="test")
cols = ["test", "total_samples", "anomaly_samples"] + METRIC_COLS
combined = combined[cols]
combined

,test,total_samples,anomaly_samples,loss,accuracy,precision_normal,recall_normal,f1_normal,precision_anomaly,recall_anomaly,f1_anomaly,f2_anomaly,roc_auc,pr_auc,mcc
0,$\mathbb{A}$ (single-chain),732,169,0.2485 ± 0.0001,69.02 ± 01.33\%,77.97 ± 00.34\%,83.13 ± 02.16\%,80.06 ± 00.76\%,24.24 ± 04.78\%,22.01 ± 04.86\%,22.21 ± 04.59\%,21.96 ± 04.72\%,68.68 ± 02.02\%,37.92 ± 01.42\%,05.92 ± 05.58\%
1,$\mathbb{B}$ (single-chain),45,43,0.8069 ± 0.0001,50.67 ± 12.13\%,26.07 ± 17.15\%,100.00 ± 00.00\%,31.19 ± 15.02\%,100.00 ± 00.00\%,48.37 ± 13.29\%,58.70 ± 11.25\%,51.62 ± 12.76\%,69.30 ± 07.85\%,98.37 ± 00.02\%,32.95 ± 14.72\%
2,$\mathbb{B}$ (cross-chain),35,24,4.5588 ± 62.3339,34.29 ± 01.76\%,27.89 ± 00.09\%,69.09 ± 06.86\%,38.55 ± 00.60\%,26.67 ± 13.33\%,18.33 ± 08.47\%,20.61 ± 09.11\%,19.05 ± 08.62\%,13.26 ± 01.52\%,55.62 ± 00.49\%,-19.79 ± 05.44\%

In [7]:
FILTERED_METRIC_COLS = ["precision_anomaly", "recall_anomaly", "f1_anomaly"]
combined_filtered = combined.copy()[["test", "total_samples", "anomaly_samples"] + FILTERED_METRIC_COLS]

column_headers = {
    "test": "Reference model (dataset type)",
    "total_samples": "\\#S",
    "anomaly_samples": "\\#A",
    "precision_anomaly": "Precision (anomaly)",
    "recall_anomaly": "Recall (anomaly)",
    "f1_anomaly": "F1 (anomaly)",
}

combined_filtered = combined_filtered.rename(columns=column_headers)
combined_filtered

,Reference model (dataset type),\#S,\#A,Precision (anomaly),Recall (anomaly),F1 (anomaly)
0,$\mathbb{A}$ (single-chain),732,169,24.24 ± 04.78\%,22.01 ± 04.86\%,22.21 ± 04.59\%
1,$\mathbb{B}$ (single-chain),45,43,100.00 ± 00.00\%,48.37 ± 13.29\%,58.70 ± 11.25\%
2,$\mathbb{B}$ (cross-chain),35,24,26.67 ± 13.33\%,18.33 ± 08.47\%,20.61 ± 09.11\%

In [8]:
combined_latex_ready = combined_filtered.copy()
for metric in FILTERED_METRIC_COLS:
    combined_latex_ready[column_headers[metric]] = combined_latex_ready[column_headers[metric]].str.replace(
        "±", r"$\pm$", regex=False
    )

latex_combined = combined_latex_ready.to_latex(
    index=False,
    escape=False,  # needed so $\pm$ isn't escaped into literal text
    caption="Leak-free agreement test metrics based on anomalies identified by prior works.",
    label="table:evaluation-leak-free-agreement",
)
print(latex_combined)

\begin{table}
\caption{Leak-free agreement test metrics based on anomalies identified by prior works.}
\label{table:evaluation-leak-free-agreement}
\begin{tabular}{lrrlll}
\toprule
Reference model (dataset type) & \#S & \#A & Precision (anomaly) & Recall (anomaly) & F1 (anomaly) \\
\midrule
$\mathbb{A}$ (single-chain) & 732 & 169 & 24.24 $\pm$ 04.78\% & 22.01 $\pm$ 04.86\% & 22.21 $\pm$ 04.59\% \\
$\mathbb{B}$ (single-chain) & 45 & 43 & 100.00 $\pm$ 00.00\% & 48.37 $\pm$ 13.29\% & 58.70 $\pm$ 11.25\% \\
$\mathbb{B}$ (cross-chain) & 35 & 24 & 26.67 $\pm$ 13.33\% & 18.33 $\pm$ 08.47\% & 20.61 $\pm$ 09.11\% \\
\bottomrule
\end{tabular}
\end{table}

### Test 2: Leaky testing of bridge cases (stratified 50/50 split on training and testing sets)

In [9]:
import pandas as pd
from pathlib import Path

# Adjust depending on where your test outputs are stored
BASE_DIR = Path("/home/gonca/Documents/GitHub/IST-Thesis/BridgeDefender/outputs")
SINGLE_CHAIN_EVALS_DIR = BASE_DIR / "single-internaltx-eval-comparison-ronin12-omni-nomad-polyn-qubit-harmony-thor123-meter-hypr-xbridge"
CCTX_EVALS_DIR = BASE_DIR / "cctx-eval-comparison-ronin12-omni-nomad-polyn-qubit-harmony-thor123-meter-hypr-xbridge"

# label -> inference run folder
RUNS = {
    "$\\mathbb{A}$ (single-chain)": SINGLE_CHAIN_EVALS_DIR / "train_epochs100_augment0_lr0.005_nosf_es15_ts0_deepsad_comparison_xchainwatcher_5050__202608071221/inference_deepsad-comparison-xchainwatcher-5050_202608071226",
    "$\\mathbb{B}$ (single-chain)": SINGLE_CHAIN_EVALS_DIR / "train_epochs100_augment0_lr0.005_nosf_es15_ts0_deepsad_comparison_xscope_5050__202608071235/inference_deepsad-comparison-xscope-5050_202608071243",
    "$\\mathbb{B}$ (cross-chain)": CCTX_EVALS_DIR / "train_epochs100_augment0_lr0.002_nosf_es15_ts0_deepsad_comparison_xscope_5050__202608071432/inference_deepsad-comparison-xscope-5050_202608071550",
}

METRIC_COLS = [
    "loss", "accuracy",
    "precision_normal", "recall_normal", "f1_normal",
    "precision_anomaly", "recall_anomaly", "f1_anomaly", "f2_anomaly",
    "roc_auc", "pr_auc", "mcc",
]

In [10]:
def load_eval_stats(run_name: str, run_dir: Path) -> pd.DataFrame:
    df = pd.read_csv(run_dir / "eval_stats.csv")
    df.insert(0, "test", run_name)
    return df

all_stats = pd.concat(
    [load_eval_stats(name, path) for name, path in RUNS.items()],
    ignore_index=True,
)
all_stats

,test,fold,loss,accuracy,precision_normal,recall_normal,f1_normal,precision_anomaly,recall_anomaly,f1_anomaly,f2_anomaly,roc_auc,pr_auc,mcc,threshold
0,$\mathbb{A}$ (single-chain),fold_1,0.176659,0.895890,0.961977,0.900356,0.930147,0.725490,0.880952,0.795699,0.844749,0.868073,0.758000,0.732887,0.074829
1,$\mathbb{A}$ (single-chain),fold_2,0.151947,0.854795,1.000000,0.811388,0.895874,0.613139,1.000000,0.760181,0.887949,0.974072,0.935227,0.705332,0.013789
2,$\mathbb{A}$ (single-chain),fold_3,0.149880,0.879452,0.885993,0.967972,0.925170,0.844828,0.583333,0.690141,0.621827,0.942256,0.883206,0.634748,0.006873
3,$\mathbb{A}$ (single-chain),fold_4,0.162527,0.917808,0.980843,0.911032,0.944649,0.759615,0.940476,0.840426,0.897727,0.944586,0.820667,0.794044,0.021758
4,$\mathbb{A}$ (single-chain),fold_5,0.299917,0.947945,0.967857,0.964413,0.966132,0.882353,0.892857,0.887574,0.890736,0.990510,0.966215,0.853733,0.362535
5,$\mathbb{B}$ (single-chain),fold_1,0.784030,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.010228
6,$\mathbb{B}$ (single-chain),fold_2,0.507190,0.636364,0.111111,1.000000,0.200000,1.000000,0.619048,0.764706,0.670103,1.000000,1.000000,0.262265,0.005944
7,$\mathbb{B}$ (single-chain),fold_3,0.667261,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.049913
8,$\mathbb{B}$ (single-chain),fold_4,0.722028,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.043187
9,$\mathbb{B}$ (single-chain),fold_5,0.728434,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.027665
10,$\mathbb{B}$ (cross-chain),fold_1,0.504899,0.470588,0.333333,0.800000,0.470588,0.800000,0.333333,0.470588,0.377358,0.866667,0.929070,0.133333,0.050198
11,$\mathbb{B}$ (cross-chain),fold_2,0.460545,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.037371
12,$\mathbb{B}$ (cross-chain),fold_3,0.141194,0.941176,0.833333,1.000000,0.909091,1.000000,0.916667,0.956522,0.932203,0.983333,0.993590,0.874007,1.904878
13,$\mathbb{B}$ (cross-chain),fold_4,0.546789,0.941176,1.000000,0.800000,0.888889,0.923077,1.000000,0.960000,0.983607,0.866667,0.928775,0.859338,0.041567
14,$\mathbb{B}$ (cross-chain),fold_5,1.720118,0.941176,1.000000,0.800000,0.888889,0.923077,1.000000,0.960000,0.983607,0.950000,0.979070,0.859338,0.102323

In [11]:
summary = all_stats.groupby("test")[METRIC_COLS].agg(["mean", "var"])
summary

                                 loss            accuracy            \
                                 mean       var      mean       var
test
$\mathbb{A}$ (single-chain)  0.188186  0.004014  0.899178  0.001274
$\mathbb{B}$ (cross-chain)   0.674709  0.367146  0.858824  0.047751
$\mathbb{B}$ (single-chain)  0.681789  0.011236  0.927273  0.026446

                            precision_normal           recall_normal  \
                                        mean       var          mean
test
$\mathbb{A}$ (single-chain)         0.959334  0.001894      0.911032
$\mathbb{B}$ (cross-chain)          0.833333  0.083333      0.880000
$\mathbb{B}$ (single-chain)         0.822222  0.158025      1.000000

                                      f1_normal            ... f1_anomaly  \
                                  var      mean       var  ...       mean
test                                                       ...
$\mathbb{A}$ (single-chain)  0.004034  0.932395  0.000670  ...   0.794804
$\mathbb{B}$ (cross-chain)   0.012000  0.831491  0.042814  ...   0.869422
$\mathbb{B}$ (single-chain)  0.000000  0.840000  0.128000  ...   0.952941

                                      f2_anomaly             roc_auc  \
                                  var       mean       var      mean
test
$\mathbb{A}$ (single-chain)  0.005710   0.828598  0.013794  0.943899
$\mathbb{B}$ (cross-chain)   0.050029   0.855355  0.072051  0.933333
$\mathbb{B}$ (single-chain)  0.011073   0.934021  0.021766  1.000000

                                         pr_auc                     mcc  \
                                  var      mean           var      mean
test
$\mathbb{A}$ (single-chain)  0.002209  0.872663  7.157128e-03  0.744149
$\mathbb{B}$ (cross-chain)   0.004028  0.966101  1.209380e-03  0.745203
$\mathbb{B}$ (single-chain)  0.000000  1.000000  4.930381e-32  0.852453


                                  var
test
$\mathbb{A}$ (single-chain)  0.007025
$\mathbb{B}$ (cross-chain)   0.120488
$\mathbb{B}$ (single-chain)  0.108851

[3 rows x 24 columns]

In [12]:
summary_flat = summary.copy()
summary_flat.columns = [f"{metric}_{stat}" for metric, stat in summary_flat.columns]
summary_flat = summary_flat.reindex(RUNS.keys())  # preserve the order defined in RUNS
summary_flat = summary_flat.reset_index()
summary_flat

,test,loss_mean,loss_var,accuracy_mean,accuracy_var,precision_normal_mean,precision_normal_var,recall_normal_mean,recall_normal_var,f1_normal_mean,...,f1_anomaly_mean,f1_anomaly_var,f2_anomaly_mean,f2_anomaly_var,roc_auc_mean,roc_auc_var,pr_auc_mean,pr_auc_var,mcc_mean,mcc_var
0,$\mathbb{A}$ (single-chain),0.188186,0.004014,0.899178,0.001274,0.959334,0.001894,0.911032,0.004034,0.932395,...,0.794804,0.005710,0.828598,0.013794,0.943899,0.002209,0.872663,7.157128e-03,0.744149,0.007025
1,$\mathbb{B}$ (single-chain),0.681789,0.011236,0.927273,0.026446,0.822222,0.158025,1.000000,0.000000,0.840000,...,0.952941,0.011073,0.934021,0.021766,1.000000,0.000000,1.000000,4.930381e-32,0.852453,0.108851
2,$\mathbb{B}$ (cross-chain),0.674709,0.367146,0.858824,0.047751,0.833333,0.083333,0.880000,0.012000,0.831491,...,0.869422,0.050029,0.855355,0.072051,0.933333,0.004028,0.966101,1.209380e-03,0.745203,0.120488

In [230]:
# latex_table = summary_flat.round(4).to_latex(
#     index=False,
#     escape=True,
#     caption="Mean and variance of evaluation metrics per test.",
#     label="tab:eval-summary",
# )
# print(latex_table)

In [13]:
def fmt_mean_var(mean, var, decimals=4, percent=False):
    if percent:
        mean *= 100
        var *= 100
    suffix = "\\%" if percent else ""
    return f"{mean:05.{decimals}f} ± {var:05.{decimals}f}{suffix}"

combined = pd.DataFrame({"test": summary_flat["test"]})
for metric in METRIC_COLS:
    combined[metric] = [
        fmt_mean_var(m, v, decimals=2 if metric not in ["loss"] else 4, percent=True if metric not in ["loss"] else False)
        for m, v in zip(summary_flat[f"{metric}_mean"], summary_flat[f"{metric}_var"])
    ]

combined

,test,loss,accuracy,precision_normal,recall_normal,f1_normal,precision_anomaly,recall_anomaly,f1_anomaly,f2_anomaly,roc_auc,pr_auc,mcc
0,$\mathbb{A}$ (single-chain),0.1882 ± 0.0040,89.92 ± 00.13\%,95.93 ± 00.19\%,91.10 ± 00.40\%,93.24 ± 00.07\%,76.51 ± 01.12\%,85.95 ± 02.60\%,79.48 ± 00.57\%,82.86 ± 01.38\%,94.39 ± 00.22\%,87.27 ± 00.72\%,74.41 ± 00.70\%
1,$\mathbb{B}$ (single-chain),0.6818 ± 0.0112,92.73 ± 02.64\%,82.22 ± 15.80\%,100.00 ± 00.00\%,84.00 ± 12.80\%,100.00 ± 00.00\%,92.38 ± 02.90\%,95.29 ± 01.11\%,93.40 ± 02.18\%,100.00 ± 00.00\%,100.00 ± 00.00\%,85.25 ± 10.89\%
2,$\mathbb{B}$ (cross-chain),0.6747 ± 0.3671,85.88 ± 04.78\%,83.33 ± 08.33\%,88.00 ± 01.20\%,83.15 ± 04.28\%,92.92 ± 00.67\%,85.00 ± 08.47\%,86.94 ± 05.00\%,85.54 ± 07.21\%,93.33 ± 00.40\%,96.61 ± 00.12\%,74.52 ± 12.05\%

In [14]:
import yaml

def load_dataset_stats(run_dir: Path) -> dict:
    with open(run_dir / "params.yaml") as f:
        params = yaml.safe_load(f)
    stats = params["dataset"]["stats"]
    return {
        "total_samples": stats["total_samples"],
        "anomaly_samples": stats["anomaly_samples"],
    }

dataset_stats = pd.DataFrame(
    [{"test": name, **load_dataset_stats(path)} for name, path in RUNS.items()]
)

combined = combined.merge(dataset_stats, on="test")
cols = ["test", "total_samples", "anomaly_samples"] + METRIC_COLS
combined = combined[cols]
combined

,test,total_samples,anomaly_samples,loss,accuracy,precision_normal,recall_normal,f1_normal,precision_anomaly,recall_anomaly,f1_anomaly,f2_anomaly,roc_auc,pr_auc,mcc
0,$\mathbb{A}$ (single-chain),365,84,0.1882 ± 0.0040,89.92 ± 00.13\%,95.93 ± 00.19\%,91.10 ± 00.40\%,93.24 ± 00.07\%,76.51 ± 01.12\%,85.95 ± 02.60\%,79.48 ± 00.57\%,82.86 ± 01.38\%,94.39 ± 00.22\%,87.27 ± 00.72\%,74.41 ± 00.70\%
1,$\mathbb{B}$ (single-chain),22,21,0.6818 ± 0.0112,92.73 ± 02.64\%,82.22 ± 15.80\%,100.00 ± 00.00\%,84.00 ± 12.80\%,100.00 ± 00.00\%,92.38 ± 02.90\%,95.29 ± 01.11\%,93.40 ± 02.18\%,100.00 ± 00.00\%,100.00 ± 00.00\%,85.25 ± 10.89\%
2,$\mathbb{B}$ (cross-chain),17,12,0.6747 ± 0.3671,85.88 ± 04.78\%,83.33 ± 08.33\%,88.00 ± 01.20\%,83.15 ± 04.28\%,92.92 ± 00.67\%,85.00 ± 08.47\%,86.94 ± 05.00\%,85.54 ± 07.21\%,93.33 ± 00.40\%,96.61 ± 00.12\%,74.52 ± 12.05\%

In [15]:
FILTERED_METRIC_COLS = ["precision_anomaly", "recall_anomaly", "f1_anomaly"]
combined_filtered = combined.copy()[["test", "total_samples", "anomaly_samples"] + FILTERED_METRIC_COLS]

column_headers = {
    "test": "Reference model (dataset type)",
    "total_samples": "\\#S",
    "anomaly_samples": "\\#A",
    "precision_anomaly": "Precision (anomaly)",
    "recall_anomaly": "Recall (anomaly)",
    "f1_anomaly": "F1 (anomaly)",
}

combined_filtered = combined_filtered.rename(columns=column_headers)
combined_filtered

,Reference model (dataset type),\#S,\#A,Precision (anomaly),Recall (anomaly),F1 (anomaly)
0,$\mathbb{A}$ (single-chain),365,84,76.51 ± 01.12\%,85.95 ± 02.60\%,79.48 ± 00.57\%
1,$\mathbb{B}$ (single-chain),22,21,100.00 ± 00.00\%,92.38 ± 02.90\%,95.29 ± 01.11\%
2,$\mathbb{B}$ (cross-chain),17,12,92.92 ± 00.67\%,85.00 ± 08.47\%,86.94 ± 05.00\%

In [16]:
combined_latex_ready = combined_filtered.copy()
for metric in FILTERED_METRIC_COLS:
    combined_latex_ready[column_headers[metric]] = combined_latex_ready[column_headers[metric]].str.replace(
        "±", r"$\pm$", regex=False
    )

latex_combined = combined_latex_ready.to_latex(
    index=False,
    escape=False,  # needed so $\pm$ isn't escaped into literal text
    caption="Upper-bound agreement test metrics based on known anomalies, identified by prior works.",
    label="table:evaluation-upper-bound-agreement",
)
print(latex_combined)

\begin{table}
\caption{Upper-bound agreement test metrics based on known anomalies, identified by prior works.}
\label{table:evaluation-upper-bound-agreement}
\begin{tabular}{lrrlll}
\toprule
Reference model (dataset type) & \#S & \#A & Precision (anomaly) & Recall (anomaly) & F1 (anomaly) \\
\midrule
$\mathbb{A}$ (single-chain) & 365 & 84 & 76.51 $\pm$ 01.12\% & 85.95 $\pm$ 02.60\% & 79.48 $\pm$ 00.57\% \\
$\mathbb{B}$ (single-chain) & 22 & 21 & 100.00 $\pm$ 00.00\% & 92.38 $\pm$ 02.90\% & 95.29 $\pm$ 01.11\% \\
$\mathbb{B}$ (cross-chain) & 17 & 12 & 92.92 $\pm$ 00.67\% & 85.00 $\pm$ 08.47\% & 86.94 $\pm$ 05.00\% \\
\bottomrule
\end{tabular}
\end{table}

### Test 3: Cross-testing in different bridge scenarios (test on a different incident each time, use the other incidents for training)

In [31]:
import pandas as pd
from pathlib import Path

BASE_DIR = Path("/home/gonca/Documents/GitHub/IST-Thesis/BridgeDefender/outputs")
SINGLE_CHAIN_EVALS_DIR = BASE_DIR / "single-internaltx-eval-comparison-ronin12-omni-nomad-polyn-qubit-harmony-thor123-meter-hypr-xbridge"
CCTX_EVALS_DIR = BASE_DIR / "cctx-eval-comparison-ronin12-omni-nomad-polyn-qubit-harmony-thor123-meter-hypr-xbridge"

RUNS = {
    "XChainWatcher (single-chain comparison)": {
        "Ronin \\#1": SINGLE_CHAIN_EVALS_DIR / "train_epochs100_augment0_lr0.005_nosf_es15_ts0_deepsad_comparison_ronin1only__202608071247/inference_deepsad-comparison-ronin1only_202608071255",
        "Nomad": SINGLE_CHAIN_EVALS_DIR / "train_epochs100_augment0_lr0.005_nosf_es15_ts0_deepsad_comparison_nomadonly__202608071243/inference_deepsad-comparison-nomadonly_202608071246",
    },
    "XScope (single-chain model)": {
        "Qubit": SINGLE_CHAIN_EVALS_DIR / "train_epochs100_augment0_lr0.005_nosf_es15_ts0_deepsad_comparison_qubitonly__202608071320/inference_deepsad-comparison-qubitonly_202608071328",
        "THORChain \\#1": SINGLE_CHAIN_EVALS_DIR / "train_epochs100_augment0_lr0.005_nosf_es15_ts0_deepsad_comparison_thorchain1only__202608071255/inference_deepsad-comparison-thorchain1only_202608071305",
        "THORChain \\#2": SINGLE_CHAIN_EVALS_DIR / "train_epochs100_augment0_lr0.005_nosf_es15_ts0_deepsad_comparison_thorchain2only__202608071305/inference_deepsad-comparison-thorchain2only_202608071312",
        "THORChain \\#3": SINGLE_CHAIN_EVALS_DIR / "train_epochs100_augment0_lr0.005_nosf_es15_ts0_deepsad_comparison_thorchain3only__202608071312/inference_deepsad-comparison-thorchain3only_202608071320"
    },
    "XScope (cross-chain model)": {
        "Qubit": CCTX_EVALS_DIR / "train_epochs100_augment0_lr0.002_nosf_es15_ts0_deepsad_comparison_qubitonly__202608071754/inference_deepsad-comparison-qubitonly_202608071811",
        "THORChain \\#2": CCTX_EVALS_DIR / "train_epochs100_augment0_lr0.002_nosf_es15_ts0_deepsad_comparison_thorchain2only__202608071712/inference_deepsad-comparison-thorchain2only_202608071730",
        "THORChain \\#3": CCTX_EVALS_DIR / "train_epochs100_augment0_lr0.002_nosf_es15_ts0_deepsad_comparison_thorchain3only__202608071731/inference_deepsad-comparison-thorchain3only_202608071753"
    },
}

# flatten to (model, incident, path) preserving nested order — used by every later cell
RUN_ROWS = [
    (model, incident, path)
    for model, incidents in RUNS.items()
    for incident, path in incidents.items()
]

METRIC_COLS = [
    "precision_anomaly", "recall_anomaly", "f1_anomaly"
]

In [32]:
def load_eval_stats(model: str, incident: str, run_dir: Path) -> pd.DataFrame:
    df = pd.read_csv(run_dir / "eval_stats.csv")
    df.insert(0, "incident", incident)
    df.insert(0, "model", model)
    return df

all_stats = pd.concat(
    [df for model, incident, path in RUN_ROWS
     if (df := load_eval_stats(model, incident, path)) is not None],
    ignore_index=True,
)
all_stats.head(10)

,model,incident,fold,loss,accuracy,precision_normal,recall_normal,f1_normal,precision_anomaly,recall_anomaly,f1_anomaly,f2_anomaly,roc_auc,pr_auc,mcc,threshold
0,XChainWatcher (single-chain comparison),Ronin \#1,fold_1,0.904556,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,1.000000,0.000000,0.202571
1,XChainWatcher (single-chain comparison),Ronin \#1,fold_2,0.891750,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,1.000000,0.000000,0.512507
2,XChainWatcher (single-chain comparison),Ronin \#1,fold_3,0.891734,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,1.000000,0.000000,0.146429
3,XChainWatcher (single-chain comparison),Ronin \#1,fold_4,0.868766,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,NaN,1.000000,0.000000,0.015775
4,XChainWatcher (single-chain comparison),Ronin \#1,fold_5,0.807191,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,NaN,1.000000,0.000000,0.174787
5,XChainWatcher (single-chain comparison),Nomad,fold_1,0.239726,0.646575,0.939481,0.579041,0.716484,0.381201,0.874251,0.530909,0.694577,0.743121,0.442811,0.381265,0.006657
6,XChainWatcher (single-chain comparison),Nomad,fold_2,0.239839,0.721918,0.768657,0.914742,0.835361,0.200000,0.071856,0.105727,0.082418,0.632199,0.340040,-0.020495,0.018427
7,XChainWatcher (single-chain comparison),Nomad,fold_3,0.250526,0.332877,0.645038,0.300178,0.409697,0.158120,0.443114,0.233071,0.325704,0.408409,0.274956,-0.224791,0.005898
8,XChainWatcher (single-chain comparison),Nomad,fold_4,0.234253,0.736986,0.781487,0.914742,0.842881,0.323944,0.137725,0.193277,0.155616,0.713139,0.402717,0.074375,0.008369
9,XChainWatcher (single-chain comparison),Nomad,fold_5,0.247365,0.501370,0.774105,0.499112,0.606911,0.231608,0.508982,0.318352,0.410628,0.512726,0.380227,0.006800,0.003880

In [33]:
summary = all_stats.groupby(["model", "incident"])[METRIC_COLS].agg(["mean", "var"])
summary

                                                      precision_anomaly  \
                                                                   mean
model                                   incident
XChainWatcher (single-chain comparison) Nomad                  0.258974
                                        Ronin \#1              0.400000
XScope (cross-chain model)              Qubit                  0.168421
                                        THORChain \#2          0.400000
                                        THORChain \#3          1.000000
XScope (single-chain model)             Qubit                  0.600000
                                        THORChain \#1          1.000000
                                        THORChain \#2          0.200000
                                        THORChain \#3          1.000000

                                                                 \
                                                            var
model                                   incident
XChainWatcher (single-chain comparison) Nomad          0.008390
                                        Ronin \#1      0.300000
XScope (cross-chain model)              Qubit          0.141828
                                        THORChain \#2  0.300000
                                        THORChain \#3  0.000000
XScope (single-chain model)             Qubit          0.300000
                                        THORChain \#1  0.000000
                                        THORChain \#2  0.200000
                                        THORChain \#3  0.000000

                                                      recall_anomaly  \
                                                                mean
model                                   incident
XChainWatcher (single-chain comparison) Nomad               0.407186
                                        Ronin \#1           0.400000
XScope (cross-chain model)              Qubit               0.200000
                                        THORChain \#2       0.300000
                                        THORChain \#3       1.000000
XScope (single-chain model)             Qubit               0.600000
                                        THORChain \#1       1.000000
                                        THORChain \#2       0.200000
                                        THORChain \#3       1.000000

                                                                f1_anomaly  \
                                                            var       mean
model                                   incident
XChainWatcher (single-chain comparison) Nomad          0.103715   0.276267
                                        Ronin \#1      0.300000   0.400000
XScope (cross-chain model)              Qubit          0.200000   0.182857
                                        THORChain \#2  0.200000   0.333333
                                        THORChain \#3  0.000000   1.000000
XScope (single-chain model)             Qubit          0.300000   0.600000
                                        THORChain \#1  0.000000   1.000000
                                        THORChain \#2  0.200000   0.200000
                                        THORChain \#3  0.000000   1.000000


                                                            var
model                                   incident
XChainWatcher (single-chain comparison) Nomad          0.026113
                                        Ronin \#1      0.300000
XScope (cross-chain model)              Qubit          0.167184
                                        THORChain \#2  0.222222
                                        THORChain \#3  0.000000
XScope (single-chain model)             Qubit          0.300000
                                        THORChain \#1  0.000000
                                        THORChain \#2  0.200000
                                        THORChain \#3  0.000000

In [34]:
summary_flat = summary.copy()
summary_flat.columns = [f"{metric}_{stat}" for metric, stat in summary_flat.columns]
summary_flat = summary_flat.reset_index()
summary_flat

,model,incident,precision_anomaly_mean,precision_anomaly_var,recall_anomaly_mean,recall_anomaly_var,f1_anomaly_mean,f1_anomaly_var
0,XChainWatcher (single-chain comparison),Nomad,0.258974,0.008390,0.407186,0.103715,0.276267,0.026113
1,XChainWatcher (single-chain comparison),Ronin \#1,0.400000,0.300000,0.400000,0.300000,0.400000,0.300000
2,XScope (cross-chain model),Qubit,0.168421,0.141828,0.200000,0.200000,0.182857,0.167184
3,XScope (cross-chain model),THORChain \#2,0.400000,0.300000,0.300000,0.200000,0.333333,0.222222
4,XScope (cross-chain model),THORChain \#3,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000
5,XScope (single-chain model),Qubit,0.600000,0.300000,0.600000,0.300000,0.600000,0.300000
6,XScope (single-chain model),THORChain \#1,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000
7,XScope (single-chain model),THORChain \#2,0.200000,0.200000,0.200000,0.200000,0.200000,0.200000
8,XScope (single-chain model),THORChain \#3,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000

In [35]:
latex_table = summary_flat.round(4).to_latex(
    index=False,
    escape=True,
    caption="Mean and variance of evaluation metrics per test.",
    label="tab:eval-summary",
)
print(latex_table)

\begin{table}
\caption{Mean and variance of evaluation metrics per test.}
\label{tab:eval-summary}
\begin{tabular}{llrrrrrr}
\toprule
model & incident & precision\_anomaly\_mean & precision\_anomaly\_var & recall\_anomaly\_mean & recall\_anomaly\_var & f1\_anomaly\_mean & f1\_anomaly\_var \\
\midrule
XChainWatcher (single-chain comparison) & Nomad & 0.259000 & 0.008400 & 0.407200 & 0.103700 & 0.276300 & 0.026100 \\
XChainWatcher (single-chain comparison) & Ronin \textbackslash \#1 & 0.400000 & 0.300000 & 0.400000 & 0.300000 & 0.400000 & 0.300000 \\
XScope (cross-chain model) & Qubit & 0.168400 & 0.141800 & 0.200000 & 0.200000 & 0.182900 & 0.167200 \\
XScope (cross-chain model) & THORChain \textbackslash \#2 & 0.400000 & 0.300000 & 0.300000 & 0.200000 & 0.333300 & 0.222200 \\
XScope (cross-chain model) & THORChain \textbackslash \#3 & 1.000000 & 0.000000 & 1.000000 & 0.000000 & 1.000000 & 0.000000 \\
XScope (single-chain model) & Qubit & 0.600000 & 0.300000 & 0.600000 & 0.300000 & 0.600000 & 0.300000 \\
XScope (single-chain model) & THORChain \textbackslash \#1 & 1.000000 & 0.000000 & 1.000000 & 0.000000 & 1.000000 & 0.000000 \\
XScope (single-chain model) & THORChain \textbackslash \#2 & 0.200000 & 0.200000 & 0.200000 & 0.200000 & 0.200000 & 0.200000 \\
XScope (single-chain model) & THORChain \textbackslash \#3 & 1.000000 & 0.000000 & 1.000000 & 0.000000 & 1.000000 & 0.000000 \\
\bottomrule
\end{tabular}
\end{table}

In [36]:
def fmt_mean_var(mean, var, decimals=4, percent=False):
    if percent:
        mean *= 100
        var *= 100
    suffix = "\\%" if percent else ""
    return f"{mean:05.{decimals}f} ± {var:05.{decimals}f}{suffix}"

combined = summary_flat[["model", "incident"]].copy()
for metric in METRIC_COLS:
    combined[metric] = [
        fmt_mean_var(m, v, decimals=2 if metric not in ["loss"] else 4, percent=True if metric not in ["loss"] else False)
        for m, v in zip(summary_flat[f"{metric}_mean"], summary_flat[f"{metric}_var"])
    ]

def load_dataset_stats(model: str, incident: str, run_dir: Path) -> dict | None:
    params_path = run_dir / "params.yaml"
    if not params_path.exists():
        return None
    with open(params_path) as f:
        params = yaml.safe_load(f)
    stats = params["dataset"]["stats"]
    return {
        "model": model,
        "incident": incident,
        "total_samples": stats["total_samples"],
        "anomaly_samples": stats["anomaly_samples"],
    }

dataset_stats = pd.DataFrame(
    [d for model, incident, path in RUN_ROWS
     if (d := load_dataset_stats(model, incident, path)) is not None]
)

combined = combined.merge(dataset_stats, on=["model", "incident"])
cols = ["model", "incident", "total_samples", "anomaly_samples"] + METRIC_COLS
combined = combined[cols]
combined

,model,incident,total_samples,anomaly_samples,precision_anomaly,recall_anomaly,f1_anomaly
0,XChainWatcher (single-chain comparison),Nomad,730,167,25.90 ± 00.84\%,40.72 ± 10.37\%,27.63 ± 02.61\%
1,XChainWatcher (single-chain comparison),Ronin \#1,2,2,40.00 ± 30.00\%,40.00 ± 30.00\%,40.00 ± 30.00\%
2,XScope (cross-chain model),Qubit,27,16,16.84 ± 14.18\%,20.00 ± 20.00\%,18.29 ± 16.72\%
3,XScope (cross-chain model),THORChain \#2,2,2,40.00 ± 30.00\%,30.00 ± 20.00\%,33.33 ± 22.22\%
4,XScope (cross-chain model),THORChain \#3,6,6,100.00 ± 00.00\%,100.00 ± 00.00\%,100.00 ± 00.00\%
5,XScope (single-chain model),Qubit,16,16,60.00 ± 30.00\%,60.00 ± 30.00\%,60.00 ± 30.00\%
6,XScope (single-chain model),THORChain \#1,6,6,100.00 ± 00.00\%,100.00 ± 00.00\%,100.00 ± 00.00\%
7,XScope (single-chain model),THORChain \#2,15,15,20.00 ± 20.00\%,20.00 ± 20.00\%,20.00 ± 20.00\%
8,XScope (single-chain model),THORChain \#3,8,6,100.00 ± 00.00\%,100.00 ± 00.00\%,100.00 ± 00.00\%

In [37]:
combined_latex_ready = combined.copy()
for metric in METRIC_COLS:
    combined_latex_ready[metric] = combined_latex_ready[metric].str.replace(
        "±", r"$\pm$", regex=False
    )

combined_latex_ready = combined_latex_ready.set_index(["model", "incident"])

latex_combined = combined_latex_ready.to_latex(
    multirow=True,
    escape=False,
    caption="Cross-incident evaluation metrics based on incidents identified by earlier models.",
    label="table:evaluation-cross-eval-incidents",
)
print(latex_combined)
# NOTE: Requires `multirow` package in LaTeX

\begin{table}
\caption{Cross-incident evaluation metrics based on incidents identified by earlier models.}
\label{table:evaluation-cross-eval-incidents}
\begin{tabular}{llrrlll}
\toprule
 &  & total_samples & anomaly_samples & precision_anomaly & recall_anomaly & f1_anomaly \\
model & incident &  &  &  &  &  \\
\midrule
\multirow[t]{2}{*}{XChainWatcher (single-chain comparison)} & Nomad & 730 & 167 & 25.90 $\pm$ 00.84\% & 40.72 $\pm$ 10.37\% & 27.63 $\pm$ 02.61\% \\
 & Ronin \#1 & 2 & 2 & 40.00 $\pm$ 30.00\% & 40.00 $\pm$ 30.00\% & 40.00 $\pm$ 30.00\% \\
\cline{1-7}
\multirow[t]{3}{*}{XScope (cross-chain model)} & Qubit & 27 & 16 & 16.84 $\pm$ 14.18\% & 20.00 $\pm$ 20.00\% & 18.29 $\pm$ 16.72\% \\
 & THORChain \#2 & 2 & 2 & 40.00 $\pm$ 30.00\% & 30.00 $\pm$ 20.00\% & 33.33 $\pm$ 22.22\% \\
 & THORChain \#3 & 6 & 6 & 100.00 $\pm$ 00.00\% & 100.00 $\pm$ 00.00\% & 100.00 $\pm$ 00.00\% \\
\cline{1-7}
\multirow[t]{4}{*}{XScope (single-chain model)} & Qubit & 16 & 16 & 60.00 $\pm$ 30.00\% & 60.00 $\pm$ 30.00\% & 60.00 $\pm$ 30.00\% \\
 & THORChain \#1 & 6 & 6 & 100.00 $\pm$ 00.00\% & 100.00 $\pm$ 00.00\% & 100.00 $\pm$ 00.00\% \\
 & THORChain \#2 & 15 & 15 & 20.00 $\pm$ 20.00\% & 20.00 $\pm$ 20.00\% & 20.00 $\pm$ 20.00\% \\
 & THORChain \#3 & 8 & 6 & 100.00 $\pm$ 00.00\% & 100.00 $\pm$ 00.00\% & 100.00 $\pm$ 00.00\% \\
\cline{1-7}
\bottomrule
\end{tabular}
\end{table}