# Comparison against tool-based anomaly-based approaches

## Single-chain scope

### Test 1: Full removal of bridge cases (no training leakage)

In [4]:
import pandas as pd
from pathlib import Path

# Adjust depending on where your test outputs are stored
BASE_DIR = Path("/home/gonca/Documents/GitHub/IST-Thesis/BridgeDefender/outputs")
SINGLE_CHAIN_EVALS_DIR = BASE_DIR / "mlpbased-single-eval-comparison-ronin12-omni-nomad-polyn-qubit-harmony-thor123-meter-hypr-xbridge"
CCTX_EVALS_DIR = BASE_DIR / "mlpbased-cctx-eval-comparison-ronin12-omni-nomad-polyn-qubit-harmony-thor123-meter-hypr-xbridge"

# label -> inference run folder
RUNS = {
    "$\\mathbb{A}$ (single-chain)": SINGLE_CHAIN_EVALS_DIR / "train_epochs100_augment0_lr0.005_nosf_es15_ts0_mlpbased_comparison_xchainwatcher_leakfree__202608110849/inference_mlpbased-comparison-xchainwatcher-leakfree_202608110851",
    "$\\mathbb{B}$ (single-chain)": SINGLE_CHAIN_EVALS_DIR / "train_epochs100_augment0_lr0.005_nosf_es15_ts0_mlpbased_comparison_xscope_leakfree__202608110857/inference_mlpbased-comparison-xscope-leakfree_202608110902",
    "$\\mathbb{B}$ (cross-chain)": CCTX_EVALS_DIR / "train_epochs100_augment0_lr0.005_nosf_es15_ts0_mlpbased_comparison_xscope_leakfree__202608111014/inference_mlpbased-comparison-xscope-leakfree_202608111032",
}

METRIC_COLS = [
    "loss", "accuracy",
    "precision_normal", "recall_normal", "f1_normal",
    "precision_anomaly", "recall_anomaly", "f1_anomaly", "f2_anomaly",
    "roc_auc", "pr_auc", "mcc",
]

In [5]:
def load_eval_stats(run_name: str, run_dir: Path) -> pd.DataFrame:
    df = pd.read_csv(run_dir / "eval_stats.csv")
    df.insert(0, "test", run_name)
    return df

all_stats = pd.concat(
    [load_eval_stats(name, path) for name, path in RUNS.items()],
    ignore_index=True,
)
all_stats

,test,fold,loss,accuracy,precision_normal,recall_normal,f1_normal,precision_anomaly,recall_anomaly,f1_anomaly,f2_anomaly,roc_auc,pr_auc,mcc
0,$\mathbb{A}$ (single-chain),fold_1,1.335613,0.769126,0.769126,1.000000,0.869498,0.000000,0.000000,0.000000,0.000000,0.500079,0.227300,0.000000
1,$\mathbb{A}$ (single-chain),fold_2,1.400585,0.769126,0.769126,1.000000,0.869498,0.000000,0.000000,0.000000,0.000000,0.490283,0.221236,0.000000
2,$\mathbb{A}$ (single-chain),fold_3,1.104189,0.648907,0.737578,0.843694,0.787075,0.000000,0.000000,0.000000,0.000000,0.618128,0.264334,-0.202529
3,$\mathbb{A}$ (single-chain),fold_4,1.256964,0.769126,0.769126,1.000000,0.869498,0.000000,0.000000,0.000000,0.000000,0.458070,0.217164,0.000000
4,$\mathbb{A}$ (single-chain),fold_5,1.265862,0.769126,0.769126,1.000000,0.869498,0.000000,0.000000,0.000000,0.000000,0.481029,0.225127,0.000000
5,$\mathbb{B}$ (single-chain),fold_1,8.759109,0.044444,0.044444,1.000000,0.085106,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000
6,$\mathbb{B}$ (single-chain),fold_2,12.496231,0.044444,0.044444,1.000000,0.085106,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000
7,$\mathbb{B}$ (single-chain),fold_3,7.540596,0.044444,0.044444,1.000000,0.085106,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000
8,$\mathbb{B}$ (single-chain),fold_4,8.820647,0.044444,0.044444,1.000000,0.085106,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000
9,$\mathbb{B}$ (single-chain),fold_5,7.601460,0.044444,0.044444,1.000000,0.085106,0.000000,0.000000,0.000000,0.000000,0.651163,0.981421,0.000000
10,$\mathbb{B}$ (cross-chain),fold_1,2.715220,0.400000,0.343750,1.000000,0.511628,1.000000,0.125000,0.222222,0.151515,0.761364,0.822555,0.207289
11,$\mathbb{B}$ (cross-chain),fold_2,1.615011,0.828571,1.000000,0.454545,0.625000,0.800000,1.000000,0.888889,0.952381,0.727273,0.748145,0.603023
12,$\mathbb{B}$ (cross-chain),fold_3,3.472554,0.342857,0.227273,0.454545,0.303030,0.538462,0.291667,0.378378,0.321101,0.276515,0.589931,-0.243832
13,$\mathbb{B}$ (cross-chain),fold_4,6.006472,0.285714,0.266667,0.727273,0.390244,0.400000,0.083333,0.137931,0.099010,0.079545,0.512620,-0.251259
14,$\mathbb{B}$ (cross-chain),fold_5,4.188575,0.285714,0.266667,0.727273,0.390244,0.400000,0.083333,0.137931,0.099010,0.333333,0.619008,-0.251259

In [6]:
summary = all_stats.groupby("test")[METRIC_COLS].agg(["mean", "var"])
summary

                                 loss            accuracy            \
                                 mean       var      mean       var
test
$\mathbb{A}$ (single-chain)  1.272643  0.012251  0.745082  0.002891
$\mathbb{B}$ (cross-chain)   3.599567  2.719196  0.428571  0.052245
$\mathbb{B}$ (single-chain)  9.043609  4.097523  0.044444  0.000000

                            precision_normal           recall_normal  \
                                        mean       var          mean
test
$\mathbb{A}$ (single-chain)         0.762816  0.000199      0.968739
$\mathbb{B}$ (cross-chain)          0.420871  0.106594      0.672727
$\mathbb{B}$ (single-chain)         0.044444  0.000000      1.000000

                                      f1_normal            ... f1_anomaly  \
                                  var      mean       var  ...       mean
test                                                       ...
$\mathbb{A}$ (single-chain)  0.004886  0.853014  0.001359  ...    0.00000
$\mathbb{B}$ (cross-chain)   0.052066  0.444029  0.015747  ...    0.35307
$\mathbb{B}$ (single-chain)  0.000000  0.085106  0.000000  ...    0.00000

                                      f2_anomaly             roc_auc  \
                                  var       mean       var      mean
test
$\mathbb{A}$ (single-chain)  0.000000   0.000000  0.000000  0.509518
$\mathbb{B}$ (cross-chain)   0.099358   0.324603  0.131465  0.435606
$\mathbb{B}$ (single-chain)  0.000000   0.000000  0.000000  0.930233

                                         pr_auc                 mcc
                                  var      mean       var      mean       var
test
$\mathbb{A}$ (single-chain)  0.003928  0.231032  0.000362 -0.040506  0.008204
$\mathbb{B}$ (cross-chain)   0.088434  0.658452  0.015623  0.012792  0.147876
$\mathbb{B}$ (single-chain)  0.024337  0.996284  0.000069  0.000000  0.000000

[3 rows x 24 columns]

In [7]:
summary_flat = summary.copy()
summary_flat.columns = [f"{metric}_{stat}" for metric, stat in summary_flat.columns]
summary_flat = summary_flat.reindex(RUNS.keys())  # preserve the order defined in RUNS
summary_flat = summary_flat.reset_index()
summary_flat

,test,loss_mean,loss_var,accuracy_mean,accuracy_var,precision_normal_mean,precision_normal_var,recall_normal_mean,recall_normal_var,f1_normal_mean,...,f1_anomaly_mean,f1_anomaly_var,f2_anomaly_mean,f2_anomaly_var,roc_auc_mean,roc_auc_var,pr_auc_mean,pr_auc_var,mcc_mean,mcc_var
0,$\mathbb{A}$ (single-chain),1.272643,0.012251,0.745082,0.002891,0.762816,0.000199,0.968739,0.004886,0.853014,...,0.00000,0.000000,0.000000,0.000000,0.509518,0.003928,0.231032,0.000362,-0.040506,0.008204
1,$\mathbb{B}$ (single-chain),9.043609,4.097523,0.044444,0.000000,0.044444,0.000000,1.000000,0.000000,0.085106,...,0.00000,0.000000,0.000000,0.000000,0.930233,0.024337,0.996284,0.000069,0.000000,0.000000
2,$\mathbb{B}$ (cross-chain),3.599567,2.719196,0.428571,0.052245,0.420871,0.106594,0.672727,0.052066,0.444029,...,0.35307,0.099358,0.324603,0.131465,0.435606,0.088434,0.658452,0.015623,0.012792,0.147876

In [8]:
# latex_table = summary_flat.round(4).to_latex(
#     index=False,
#     escape=True,
#     caption="Mean and variance of evaluation metrics per test.",
#     label="tab:eval-summary",
# )
# print(latex_table)

In [9]:
def fmt_mean_var(mean, var, decimals=4, percent=False):
    if percent:
        mean *= 100
        var *= 100
    suffix = "\\%" if percent else ""
    return f"{mean:05.{decimals}f} ± {var:05.{decimals}f}{suffix}"

combined = pd.DataFrame({"test": summary_flat["test"]})
for metric in METRIC_COLS:
    combined[metric] = [
        fmt_mean_var(m, v, decimals=2 if metric not in ["loss"] else 4, percent=True if metric not in ["loss"] else False)
        for m, v in zip(summary_flat[f"{metric}_mean"], summary_flat[f"{metric}_var"])
    ]

combined

,test,loss,accuracy,precision_normal,recall_normal,f1_normal,precision_anomaly,recall_anomaly,f1_anomaly,f2_anomaly,roc_auc,pr_auc,mcc
0,$\mathbb{A}$ (single-chain),1.2726 ± 0.0123,74.51 ± 00.29\%,76.28 ± 00.02\%,96.87 ± 00.49\%,85.30 ± 00.14\%,00.00 ± 00.00\%,00.00 ± 00.00\%,00.00 ± 00.00\%,00.00 ± 00.00\%,50.95 ± 00.39\%,23.10 ± 00.04\%,-4.05 ± 00.82\%
1,$\mathbb{B}$ (single-chain),9.0436 ± 4.0975,04.44 ± 00.00\%,04.44 ± 00.00\%,100.00 ± 00.00\%,08.51 ± 00.00\%,00.00 ± 00.00\%,00.00 ± 00.00\%,00.00 ± 00.00\%,00.00 ± 00.00\%,93.02 ± 02.43\%,99.63 ± 00.01\%,00.00 ± 00.00\%
2,$\mathbb{B}$ (cross-chain),3.5996 ± 2.7192,42.86 ± 05.22\%,42.09 ± 10.66\%,67.27 ± 05.21\%,44.40 ± 01.57\%,62.77 ± 07.00\%,31.67 ± 15.33\%,35.31 ± 09.94\%,32.46 ± 13.15\%,43.56 ± 08.84\%,65.85 ± 01.56\%,01.28 ± 14.79\%

In [10]:
import yaml

def load_dataset_stats(run_dir: Path) -> dict:
    with open(run_dir / "params.yaml") as f:
        params = yaml.safe_load(f)
    stats = params["dataset"]["stats"]
    return {
        "total_samples": stats["total_samples"],
        "anomaly_samples": stats["anomaly_samples"],
    }

dataset_stats = pd.DataFrame(
    [{"test": name, **load_dataset_stats(path)} for name, path in RUNS.items()]
)

combined = combined.merge(dataset_stats, on="test")
cols = ["test", "total_samples", "anomaly_samples"] + METRIC_COLS
combined = combined[cols]
combined

,test,total_samples,anomaly_samples,loss,accuracy,precision_normal,recall_normal,f1_normal,precision_anomaly,recall_anomaly,f1_anomaly,f2_anomaly,roc_auc,pr_auc,mcc
0,$\mathbb{A}$ (single-chain),732,169,1.2726 ± 0.0123,74.51 ± 00.29\%,76.28 ± 00.02\%,96.87 ± 00.49\%,85.30 ± 00.14\%,00.00 ± 00.00\%,00.00 ± 00.00\%,00.00 ± 00.00\%,00.00 ± 00.00\%,50.95 ± 00.39\%,23.10 ± 00.04\%,-4.05 ± 00.82\%
1,$\mathbb{B}$ (single-chain),45,43,9.0436 ± 4.0975,04.44 ± 00.00\%,04.44 ± 00.00\%,100.00 ± 00.00\%,08.51 ± 00.00\%,00.00 ± 00.00\%,00.00 ± 00.00\%,00.00 ± 00.00\%,00.00 ± 00.00\%,93.02 ± 02.43\%,99.63 ± 00.01\%,00.00 ± 00.00\%
2,$\mathbb{B}$ (cross-chain),35,24,3.5996 ± 2.7192,42.86 ± 05.22\%,42.09 ± 10.66\%,67.27 ± 05.21\%,44.40 ± 01.57\%,62.77 ± 07.00\%,31.67 ± 15.33\%,35.31 ± 09.94\%,32.46 ± 13.15\%,43.56 ± 08.84\%,65.85 ± 01.56\%,01.28 ± 14.79\%

In [11]:
FILTERED_METRIC_COLS = ["precision_anomaly", "recall_anomaly", "f1_anomaly"]
combined_filtered = combined.copy()[["test", "total_samples", "anomaly_samples"] + FILTERED_METRIC_COLS]

column_headers = {
    "test": "Reference model (dataset type)",
    "total_samples": "\\#S",
    "anomaly_samples": "\\#A",
    "precision_anomaly": "Precision (anomaly)",
    "recall_anomaly": "Recall (anomaly)",
    "f1_anomaly": "F1 (anomaly)",
}

combined_filtered = combined_filtered.rename(columns=column_headers)
combined_filtered

,Reference model (dataset type),\#S,\#A,Precision (anomaly),Recall (anomaly),F1 (anomaly)
0,$\mathbb{A}$ (single-chain),732,169,00.00 ± 00.00\%,00.00 ± 00.00\%,00.00 ± 00.00\%
1,$\mathbb{B}$ (single-chain),45,43,00.00 ± 00.00\%,00.00 ± 00.00\%,00.00 ± 00.00\%
2,$\mathbb{B}$ (cross-chain),35,24,62.77 ± 07.00\%,31.67 ± 15.33\%,35.31 ± 09.94\%

In [12]:
combined_latex_ready = combined_filtered.copy()
for metric in FILTERED_METRIC_COLS:
    combined_latex_ready[column_headers[metric]] = combined_latex_ready[column_headers[metric]].str.replace(
        "±", r"$\pm$", regex=False
    )

latex_combined = combined_latex_ready.to_latex(
    index=False,
    escape=False,  # needed so $\pm$ isn't escaped into literal text
    caption="Leak-free agreement test metrics based on anomalies identified by prior works.",
    label="table:evaluation-leak-free-agreement",
)
print(latex_combined)

\begin{table}
\caption{Leak-free agreement test metrics based on anomalies identified by prior works.}
\label{table:evaluation-leak-free-agreement}
\begin{tabular}{lrrlll}
\toprule
Reference model (dataset type) & \#S & \#A & Precision (anomaly) & Recall (anomaly) & F1 (anomaly) \\
\midrule
$\mathbb{A}$ (single-chain) & 732 & 169 & 00.00 $\pm$ 00.00\% & 00.00 $\pm$ 00.00\% & 00.00 $\pm$ 00.00\% \\
$\mathbb{B}$ (single-chain) & 45 & 43 & 00.00 $\pm$ 00.00\% & 00.00 $\pm$ 00.00\% & 00.00 $\pm$ 00.00\% \\
$\mathbb{B}$ (cross-chain) & 35 & 24 & 62.77 $\pm$ 07.00\% & 31.67 $\pm$ 15.33\% & 35.31 $\pm$ 09.94\% \\
\bottomrule
\end{tabular}
\end{table}

### Test 2: Leaky testing of bridge cases (stratified 50/50 split on training and testing sets)

In [17]:
import pandas as pd
from pathlib import Path

# Adjust depending on where your test outputs are stored
BASE_DIR = Path("/home/gonca/Documents/GitHub/IST-Thesis/BridgeDefender/outputs")
SINGLE_CHAIN_EVALS_DIR = BASE_DIR / "mlpbased-single-eval-comparison-ronin12-omni-nomad-polyn-qubit-harmony-thor123-meter-hypr-xbridge"
CCTX_EVALS_DIR = BASE_DIR / "mlpbased-cctx-eval-comparison-ronin12-omni-nomad-polyn-qubit-harmony-thor123-meter-hypr-xbridge"

# label -> inference run folder
RUNS = {
    "$\\mathbb{A}$ (single-chain)": SINGLE_CHAIN_EVALS_DIR / "train_epochs100_augment0_lr0.005_nosf_es15_ts0_mlpbased_comparison_xchainwatcher_5050__202608110852/inference_mlpbased-comparison-xchainwatcher-5050_202608110857",
    "$\\mathbb{B}$ (single-chain)": SINGLE_CHAIN_EVALS_DIR / "train_epochs100_augment0_lr0.005_nosf_es15_ts0_mlpbased_comparison_xscope_5050__202608110902/inference_mlpbased-comparison-xscope-5050_202608110908",
    "$\\mathbb{B}$ (cross-chain)": CCTX_EVALS_DIR / "train_epochs100_augment0_lr0.005_nosf_es15_ts0_mlpbased_comparison_xscope_5050__202608111033/inference_mlpbased-comparison-xscope-5050_202608111048",
}

METRIC_COLS = [
    "loss", "accuracy",
    "precision_normal", "recall_normal", "f1_normal",
    "precision_anomaly", "recall_anomaly", "f1_anomaly", "f2_anomaly",
    "roc_auc", "pr_auc", "mcc",
]

In [19]:
def load_eval_stats(run_name: str, run_dir: Path) -> pd.DataFrame:
    df = pd.read_csv(run_dir / "eval_stats.csv")
    df.insert(0, "test", run_name)
    return df

all_stats = pd.concat(
    [load_eval_stats(name, path) for name, path in RUNS.items()],
    ignore_index=True,
)
all_stats

,test,fold,loss,accuracy,precision_normal,recall_normal,f1_normal,precision_anomaly,recall_anomaly,f1_anomaly,f2_anomaly,roc_auc,pr_auc,mcc
0,$\mathbb{A}$ (single-chain),fold_1,0.103288,0.967123,0.996310,0.960854,0.978261,0.882979,0.988095,0.932584,0.965116,0.991781,0.973112,0.913455
1,$\mathbb{A}$ (single-chain),fold_2,0.115388,0.967123,0.996310,0.960854,0.978261,0.882979,0.988095,0.932584,0.965116,0.986528,0.949531,0.913455
2,$\mathbb{A}$ (single-chain),fold_3,0.111615,0.967123,0.996310,0.960854,0.978261,0.882979,0.988095,0.932584,0.965116,0.980554,0.922805,0.913455
3,$\mathbb{A}$ (single-chain),fold_4,0.085809,0.967123,0.996310,0.960854,0.978261,0.882979,0.988095,0.932584,0.965116,0.996865,0.987681,0.913455
4,$\mathbb{A}$ (single-chain),fold_5,0.097923,0.967123,0.996310,0.960854,0.978261,0.882979,0.988095,0.932584,0.965116,0.991908,0.979656,0.913455
5,$\mathbb{B}$ (single-chain),fold_1,0.025021,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
6,$\mathbb{B}$ (single-chain),fold_2,0.011724,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
7,$\mathbb{B}$ (single-chain),fold_3,0.020759,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
8,$\mathbb{B}$ (single-chain),fold_4,0.010963,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
9,$\mathbb{B}$ (single-chain),fold_5,0.057106,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
10,$\mathbb{B}$ (cross-chain),fold_1,0.316770,0.941176,1.000000,0.800000,0.888889,0.923077,1.000000,0.960000,0.983607,1.000000,1.000000,0.859338
11,$\mathbb{B}$ (cross-chain),fold_2,0.400578,0.941176,1.000000,0.800000,0.888889,0.923077,1.000000,0.960000,0.983607,0.983333,0.993590,0.859338
12,$\mathbb{B}$ (cross-chain),fold_3,0.658147,0.470588,0.333333,0.800000,0.470588,0.800000,0.333333,0.470588,0.377358,0.850000,0.917664,0.133333
13,$\mathbb{B}$ (cross-chain),fold_4,0.814907,0.705882,0.000000,0.000000,0.000000,0.705882,1.000000,0.827586,0.923077,0.800000,0.834923,0.000000
14,$\mathbb{B}$ (cross-chain),fold_5,0.686591,0.705882,0.000000,0.000000,0.000000,0.705882,1.000000,0.827586,0.923077,0.983333,0.993590,0.000000

In [20]:
summary = all_stats.groupby("test")[METRIC_COLS].agg(["mean", "var"])
summary

                                 loss            accuracy            \
                                 mean       var      mean       var
test
$\mathbb{A}$ (single-chain)  0.102804  0.000137  0.967123  0.000000
$\mathbb{B}$ (cross-chain)   0.575398  0.043507  0.752941  0.038754
$\mathbb{B}$ (single-chain)  0.025114  0.000355  1.000000  0.000000

                            precision_normal           recall_normal         \
                                        mean       var          mean    var
test
$\mathbb{A}$ (single-chain)         0.996310  0.000000      0.960854  0.000
$\mathbb{B}$ (cross-chain)          0.466667  0.255556      0.480000  0.192
$\mathbb{B}$ (single-chain)         1.000000  0.000000      1.000000  0.000

                            f1_normal            ... f1_anomaly            \
                                 mean       var  ...       mean       var
test                                             ...
$\mathbb{A}$ (single-chain)  0.978261  0.000000  ...   0.932584  0.000000
$\mathbb{B}$ (cross-chain)   0.449673  0.197668  ...   0.809152  0.040204
$\mathbb{B}$ (single-chain)  1.000000  0.000000  ...   1.000000  0.000000

                            f2_anomaly             roc_auc            \
                                  mean       var      mean       var
test
$\mathbb{A}$ (single-chain)   0.965116  0.000000  0.989527  0.000039
$\mathbb{B}$ (cross-chain)    0.838145  0.067267  0.923333  0.008417
$\mathbb{B}$ (single-chain)   1.000000  0.000000  1.000000  0.000000

                               pr_auc                 mcc
                                 mean       var      mean       var
test
$\mathbb{A}$ (single-chain)  0.962557  0.000696  0.913455  0.000000
$\mathbb{B}$ (cross-chain)   0.947953  0.005142  0.370402  0.202178
$\mathbb{B}$ (single-chain)  1.000000  0.000000  1.000000  0.000000

[3 rows x 24 columns]

In [21]:
summary_flat = summary.copy()
summary_flat.columns = [f"{metric}_{stat}" for metric, stat in summary_flat.columns]
summary_flat = summary_flat.reindex(RUNS.keys())  # preserve the order defined in RUNS
summary_flat = summary_flat.reset_index()
summary_flat

,test,loss_mean,loss_var,accuracy_mean,accuracy_var,precision_normal_mean,precision_normal_var,recall_normal_mean,recall_normal_var,f1_normal_mean,...,f1_anomaly_mean,f1_anomaly_var,f2_anomaly_mean,f2_anomaly_var,roc_auc_mean,roc_auc_var,pr_auc_mean,pr_auc_var,mcc_mean,mcc_var
0,$\mathbb{A}$ (single-chain),0.102804,0.000137,0.967123,0.000000,0.996310,0.000000,0.960854,0.000,0.978261,...,0.932584,0.000000,0.965116,0.000000,0.989527,0.000039,0.962557,0.000696,0.913455,0.000000
1,$\mathbb{B}$ (single-chain),0.025114,0.000355,1.000000,0.000000,1.000000,0.000000,1.000000,0.000,1.000000,...,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000
2,$\mathbb{B}$ (cross-chain),0.575398,0.043507,0.752941,0.038754,0.466667,0.255556,0.480000,0.192,0.449673,...,0.809152,0.040204,0.838145,0.067267,0.923333,0.008417,0.947953,0.005142,0.370402,0.202178

In [22]:
# latex_table = summary_flat.round(4).to_latex(
#     index=False,
#     escape=True,
#     caption="Mean and variance of evaluation metrics per test.",
#     label="tab:eval-summary",
# )
# print(latex_table)

In [23]:
def fmt_mean_var(mean, var, decimals=4, percent=False):
    if percent:
        mean *= 100
        var *= 100
    suffix = "\\%" if percent else ""
    return f"{mean:05.{decimals}f} ± {var:05.{decimals}f}{suffix}"

combined = pd.DataFrame({"test": summary_flat["test"]})
for metric in METRIC_COLS:
    combined[metric] = [
        fmt_mean_var(m, v, decimals=2 if metric not in ["loss"] else 4, percent=True if metric not in ["loss"] else False)
        for m, v in zip(summary_flat[f"{metric}_mean"], summary_flat[f"{metric}_var"])
    ]

combined

,test,loss,accuracy,precision_normal,recall_normal,f1_normal,precision_anomaly,recall_anomaly,f1_anomaly,f2_anomaly,roc_auc,pr_auc,mcc
0,$\mathbb{A}$ (single-chain),0.1028 ± 0.0001,96.71 ± 00.00\%,99.63 ± 00.00\%,96.09 ± 00.00\%,97.83 ± 00.00\%,88.30 ± 00.00\%,98.81 ± 00.00\%,93.26 ± 00.00\%,96.51 ± 00.00\%,98.95 ± 00.00\%,96.26 ± 00.07\%,91.35 ± 00.00\%
1,$\mathbb{B}$ (single-chain),0.0251 ± 0.0004,100.00 ± 00.00\%,100.00 ± 00.00\%,100.00 ± 00.00\%,100.00 ± 00.00\%,100.00 ± 00.00\%,100.00 ± 00.00\%,100.00 ± 00.00\%,100.00 ± 00.00\%,100.00 ± 00.00\%,100.00 ± 00.00\%,100.00 ± 00.00\%
2,$\mathbb{B}$ (cross-chain),0.5754 ± 0.0435,75.29 ± 03.88\%,46.67 ± 25.56\%,48.00 ± 19.20\%,44.97 ± 19.77\%,81.16 ± 01.18\%,86.67 ± 08.89\%,80.92 ± 04.02\%,83.81 ± 06.73\%,92.33 ± 00.84\%,94.80 ± 00.51\%,37.04 ± 20.22\%

In [24]:
import yaml

def load_dataset_stats(run_dir: Path) -> dict:
    with open(run_dir / "params.yaml") as f:
        params = yaml.safe_load(f)
    stats = params["dataset"]["stats"]
    return {
        "total_samples": stats["total_samples"],
        "anomaly_samples": stats["anomaly_samples"],
    }

dataset_stats = pd.DataFrame(
    [{"test": name, **load_dataset_stats(path)} for name, path in RUNS.items()]
)

combined = combined.merge(dataset_stats, on="test")
cols = ["test", "total_samples", "anomaly_samples"] + METRIC_COLS
combined = combined[cols]
combined

,test,total_samples,anomaly_samples,loss,accuracy,precision_normal,recall_normal,f1_normal,precision_anomaly,recall_anomaly,f1_anomaly,f2_anomaly,roc_auc,pr_auc,mcc
0,$\mathbb{A}$ (single-chain),365,84,0.1028 ± 0.0001,96.71 ± 00.00\%,99.63 ± 00.00\%,96.09 ± 00.00\%,97.83 ± 00.00\%,88.30 ± 00.00\%,98.81 ± 00.00\%,93.26 ± 00.00\%,96.51 ± 00.00\%,98.95 ± 00.00\%,96.26 ± 00.07\%,91.35 ± 00.00\%
1,$\mathbb{B}$ (single-chain),22,21,0.0251 ± 0.0004,100.00 ± 00.00\%,100.00 ± 00.00\%,100.00 ± 00.00\%,100.00 ± 00.00\%,100.00 ± 00.00\%,100.00 ± 00.00\%,100.00 ± 00.00\%,100.00 ± 00.00\%,100.00 ± 00.00\%,100.00 ± 00.00\%,100.00 ± 00.00\%
2,$\mathbb{B}$ (cross-chain),17,12,0.5754 ± 0.0435,75.29 ± 03.88\%,46.67 ± 25.56\%,48.00 ± 19.20\%,44.97 ± 19.77\%,81.16 ± 01.18\%,86.67 ± 08.89\%,80.92 ± 04.02\%,83.81 ± 06.73\%,92.33 ± 00.84\%,94.80 ± 00.51\%,37.04 ± 20.22\%

In [25]:
FILTERED_METRIC_COLS = ["precision_anomaly", "recall_anomaly", "f1_anomaly"]
combined_filtered = combined.copy()[["test", "total_samples", "anomaly_samples"] + FILTERED_METRIC_COLS]

column_headers = {
    "test": "Reference model (dataset type)",
    "total_samples": "\\#S",
    "anomaly_samples": "\\#A",
    "precision_anomaly": "Precision (anomaly)",
    "recall_anomaly": "Recall (anomaly)",
    "f1_anomaly": "F1 (anomaly)",
}

combined_filtered = combined_filtered.rename(columns=column_headers)
combined_filtered

,Reference model (dataset type),\#S,\#A,Precision (anomaly),Recall (anomaly),F1 (anomaly)
0,$\mathbb{A}$ (single-chain),365,84,88.30 ± 00.00\%,98.81 ± 00.00\%,93.26 ± 00.00\%
1,$\mathbb{B}$ (single-chain),22,21,100.00 ± 00.00\%,100.00 ± 00.00\%,100.00 ± 00.00\%
2,$\mathbb{B}$ (cross-chain),17,12,81.16 ± 01.18\%,86.67 ± 08.89\%,80.92 ± 04.02\%

In [26]:
combined_latex_ready = combined_filtered.copy()
for metric in FILTERED_METRIC_COLS:
    combined_latex_ready[column_headers[metric]] = combined_latex_ready[column_headers[metric]].str.replace(
        "±", r"$\pm$", regex=False
    )

latex_combined = combined_latex_ready.to_latex(
    index=False,
    escape=False,  # needed so $\pm$ isn't escaped into literal text
    caption="Upper-bound agreement test metrics based on known anomalies, identified by prior works.",
    label="table:evaluation-upper-bound-agreement",
)
print(latex_combined)

\begin{table}
\caption{Upper-bound agreement test metrics based on known anomalies, identified by prior works.}
\label{table:evaluation-upper-bound-agreement}
\begin{tabular}{lrrlll}
\toprule
Reference model (dataset type) & \#S & \#A & Precision (anomaly) & Recall (anomaly) & F1 (anomaly) \\
\midrule
$\mathbb{A}$ (single-chain) & 365 & 84 & 88.30 $\pm$ 00.00\% & 98.81 $\pm$ 00.00\% & 93.26 $\pm$ 00.00\% \\
$\mathbb{B}$ (single-chain) & 22 & 21 & 100.00 $\pm$ 00.00\% & 100.00 $\pm$ 00.00\% & 100.00 $\pm$ 00.00\% \\
$\mathbb{B}$ (cross-chain) & 17 & 12 & 81.16 $\pm$ 01.18\% & 86.67 $\pm$ 08.89\% & 80.92 $\pm$ 04.02\% \\
\bottomrule
\end{tabular}
\end{table}

### Test 3: Cross-testing in different bridge scenarios (test on a different incident each time, use the other incidents for training)

In [27]:
import pandas as pd
from pathlib import Path

BASE_DIR = Path("/home/gonca/Documents/GitHub/IST-Thesis/BridgeDefender/outputs")
SINGLE_CHAIN_EVALS_DIR = BASE_DIR / "mlpbased-single-eval-comparison-ronin12-omni-nomad-polyn-qubit-harmony-thor123-meter-hypr-xbridge"
CCTX_EVALS_DIR = BASE_DIR / "mlpbased-cctx-eval-comparison-ronin12-omni-nomad-polyn-qubit-harmony-thor123-meter-hypr-xbridge"

RUNS = {
    "XChainWatcher (single-chain comparison)": {
        "Ronin \\#1": SINGLE_CHAIN_EVALS_DIR / "train_epochs100_augment0_lr0.005_nosf_es15_ts0_mlpbased_comparison_ronin1only__202608110911/inference_mlpbased-comparison-ronin1only_202608110918",
        "Nomad": SINGLE_CHAIN_EVALS_DIR / "train_epochs100_augment0_lr0.005_nosf_es15_ts0_mlpbased_comparison_nomadonly__202608110909/inference_mlpbased-comparison-nomadonly_202608110911",
    },
    "XScope (single-chain model)": {
        "Qubit": SINGLE_CHAIN_EVALS_DIR / "train_epochs100_augment0_lr0.005_nosf_es15_ts0_mlpbased_comparison_qubitonly__202608110936/inference_mlpbased-comparison-qubitonly_202608110942",
        "THORChain \\#1": SINGLE_CHAIN_EVALS_DIR / "train_epochs100_augment0_lr0.005_nosf_es15_ts0_mlpbased_comparison_thorchain1only__202608110918/inference_mlpbased-comparison-thorchain1only_202608110923",
        "THORChain \\#2": SINGLE_CHAIN_EVALS_DIR / "train_epochs100_augment0_lr0.005_nosf_es15_ts0_mlpbased_comparison_thorchain2only__202608110924/inference_mlpbased-comparison-thorchain2only_202608110929",
        "THORChain \\#3": SINGLE_CHAIN_EVALS_DIR / "train_epochs100_augment0_lr0.005_nosf_es15_ts0_mlpbased_comparison_thorchain3only__202608110929/inference_mlpbased-comparison-thorchain3only_202608110936"
    },
    "XScope (cross-chain model)": {
        "Qubit": CCTX_EVALS_DIR / "train_epochs100_augment0_lr0.005_nosf_es15_ts0_mlpbased_comparison_qubitonly__202608111133/inference_mlpbased-comparison-qubitonly_202608111147",
        "THORChain \\#2": CCTX_EVALS_DIR / "train_epochs100_augment0_lr0.005_nosf_es15_ts0_mlpbased_comparison_thorchain2only__202608111049/inference_mlpbased-comparison-thorchain2only_202608111105",
        "THORChain \\#3": CCTX_EVALS_DIR / "train_epochs100_augment0_lr0.005_nosf_es15_ts0_mlpbased_comparison_thorchain3only__202608111118/inference_mlpbased-comparison-thorchain3only_202608111132"
    },
}

# flatten to (model, incident, path) preserving nested order — used by every later cell
RUN_ROWS = [
    (model, incident, path)
    for model, incidents in RUNS.items()
    for incident, path in incidents.items()
]

METRIC_COLS = [
    "precision_anomaly", "recall_anomaly", "f1_anomaly"
]

In [28]:
def load_eval_stats(model: str, incident: str, run_dir: Path) -> pd.DataFrame:
    df = pd.read_csv(run_dir / "eval_stats.csv")
    df.insert(0, "incident", incident)
    df.insert(0, "model", model)
    return df

all_stats = pd.concat(
    [df for model, incident, path in RUN_ROWS
     if (df := load_eval_stats(model, incident, path)) is not None],
    ignore_index=True,
)
all_stats.head(10)

,model,incident,fold,loss,accuracy,precision_normal,recall_normal,f1_normal,precision_anomaly,recall_anomaly,f1_anomaly,f2_anomaly,roc_auc,pr_auc,mcc
0,XChainWatcher (single-chain comparison),Ronin \#1,fold_1,7.597078,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,1.000000,0.000000
1,XChainWatcher (single-chain comparison),Ronin \#1,fold_2,13.775382,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,1.000000,0.000000
2,XChainWatcher (single-chain comparison),Ronin \#1,fold_3,2.775037,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,1.000000,0.000000
3,XChainWatcher (single-chain comparison),Ronin \#1,fold_4,13.365232,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,1.000000,0.000000
4,XChainWatcher (single-chain comparison),Ronin \#1,fold_5,10.018219,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,1.000000,0.000000
5,XChainWatcher (single-chain comparison),Nomad,fold_1,0.597796,0.771233,0.771233,1.000000,0.870843,0.000000,0.000000,0.000000,0.000000,0.652471,0.283627,0.000000
6,XChainWatcher (single-chain comparison),Nomad,fold_2,1.017713,0.771233,0.771233,1.000000,0.870843,0.000000,0.000000,0.000000,0.000000,0.634582,0.271322,0.000000
7,XChainWatcher (single-chain comparison),Nomad,fold_3,0.574528,0.641096,0.912329,0.591474,0.717672,0.369863,0.808383,0.507519,0.653437,0.787228,0.615396,0.335911
8,XChainWatcher (single-chain comparison),Nomad,fold_4,1.371814,0.486301,0.680077,0.630551,0.654378,0.000000,0.000000,0.000000,0.000000,0.476564,0.210158,-0.343796
9,XChainWatcher (single-chain comparison),Nomad,fold_5,0.986389,0.552055,0.707018,0.715808,0.711386,0.000000,0.000000,0.000000,0.000000,0.641314,0.274816,-0.288554

In [29]:
summary = all_stats.groupby(["model", "incident"])[METRIC_COLS].agg(["mean", "var"])
summary

                                                      precision_anomaly  \
                                                                   mean
model                                   incident
XChainWatcher (single-chain comparison) Nomad                  0.073973
                                        Ronin \#1              0.000000
XScope (cross-chain model)              Qubit                  0.000000
                                        THORChain \#2          1.000000
                                        THORChain \#3          1.000000
XScope (single-chain model)             Qubit                  0.600000
                                        THORChain \#1          1.000000
                                        THORChain \#2          0.000000
                                        THORChain \#3          0.000000

                                                               recall_anomaly  \
                                                           var           mean
model                                   incident
XChainWatcher (single-chain comparison) Nomad          0.02736       0.161677
                                        Ronin \#1      0.00000       0.000000
XScope (cross-chain model)              Qubit          0.00000       0.000000
                                        THORChain \#2  0.00000       0.900000
                                        THORChain \#3  0.00000       1.000000
XScope (single-chain model)             Qubit          0.30000       0.600000
                                        THORChain \#1  0.00000       1.000000
                                        THORChain \#2  0.00000       0.000000
                                        THORChain \#3  0.00000       0.000000

                                                                f1_anomaly  \
                                                            var       mean
model                                   incident
XChainWatcher (single-chain comparison) Nomad          0.130697   0.101504
                                        Ronin \#1      0.000000   0.000000
XScope (cross-chain model)              Qubit          0.000000   0.000000
                                        THORChain \#2  0.050000   0.933333
                                        THORChain \#3  0.000000   1.000000
XScope (single-chain model)             Qubit          0.300000   0.600000
                                        THORChain \#1  0.000000   1.000000
                                        THORChain \#2  0.000000   0.000000
                                        THORChain \#3  0.000000   0.000000


                                                            var
model                                   incident
XChainWatcher (single-chain comparison) Nomad          0.051515
                                        Ronin \#1      0.000000
XScope (cross-chain model)              Qubit          0.000000
                                        THORChain \#2  0.022222
                                        THORChain \#3  0.000000
XScope (single-chain model)             Qubit          0.300000
                                        THORChain \#1  0.000000
                                        THORChain \#2  0.000000
                                        THORChain \#3  0.000000

In [30]:
summary_flat = summary.copy()
summary_flat.columns = [f"{metric}_{stat}" for metric, stat in summary_flat.columns]
summary_flat = summary_flat.reset_index()
summary_flat

,model,incident,precision_anomaly_mean,precision_anomaly_var,recall_anomaly_mean,recall_anomaly_var,f1_anomaly_mean,f1_anomaly_var
0,XChainWatcher (single-chain comparison),Nomad,0.073973,0.02736,0.161677,0.130697,0.101504,0.051515
1,XChainWatcher (single-chain comparison),Ronin \#1,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
2,XScope (cross-chain model),Qubit,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
3,XScope (cross-chain model),THORChain \#2,1.000000,0.00000,0.900000,0.050000,0.933333,0.022222
4,XScope (cross-chain model),THORChain \#3,1.000000,0.00000,1.000000,0.000000,1.000000,0.000000
5,XScope (single-chain model),Qubit,0.600000,0.30000,0.600000,0.300000,0.600000,0.300000
6,XScope (single-chain model),THORChain \#1,1.000000,0.00000,1.000000,0.000000,1.000000,0.000000
7,XScope (single-chain model),THORChain \#2,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
8,XScope (single-chain model),THORChain \#3,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000

In [31]:
latex_table = summary_flat.round(4).to_latex(
    index=False,
    escape=True,
    caption="Mean and variance of evaluation metrics per test.",
    label="tab:eval-summary",
)
print(latex_table)

\begin{table}
\caption{Mean and variance of evaluation metrics per test.}
\label{tab:eval-summary}
\begin{tabular}{llrrrrrr}
\toprule
model & incident & precision\_anomaly\_mean & precision\_anomaly\_var & recall\_anomaly\_mean & recall\_anomaly\_var & f1\_anomaly\_mean & f1\_anomaly\_var \\
\midrule
XChainWatcher (single-chain comparison) & Nomad & 0.074000 & 0.027400 & 0.161700 & 0.130700 & 0.101500 & 0.051500 \\
XChainWatcher (single-chain comparison) & Ronin \textbackslash \#1 & 0.000000 & 0.000000 & 0.000000 & 0.000000 & 0.000000 & 0.000000 \\
XScope (cross-chain model) & Qubit & 0.000000 & 0.000000 & 0.000000 & 0.000000 & 0.000000 & 0.000000 \\
XScope (cross-chain model) & THORChain \textbackslash \#2 & 1.000000 & 0.000000 & 0.900000 & 0.050000 & 0.933300 & 0.022200 \\
XScope (cross-chain model) & THORChain \textbackslash \#3 & 1.000000 & 0.000000 & 1.000000 & 0.000000 & 1.000000 & 0.000000 \\
XScope (single-chain model) & Qubit & 0.600000 & 0.300000 & 0.600000 & 0.300000 & 0.600000 & 0.300000 \\
XScope (single-chain model) & THORChain \textbackslash \#1 & 1.000000 & 0.000000 & 1.000000 & 0.000000 & 1.000000 & 0.000000 \\
XScope (single-chain model) & THORChain \textbackslash \#2 & 0.000000 & 0.000000 & 0.000000 & 0.000000 & 0.000000 & 0.000000 \\
XScope (single-chain model) & THORChain \textbackslash \#3 & 0.000000 & 0.000000 & 0.000000 & 0.000000 & 0.000000 & 0.000000 \\
\bottomrule
\end{tabular}
\end{table}

In [32]:
def fmt_mean_var(mean, var, decimals=4, percent=False):
    if percent:
        mean *= 100
        var *= 100
    suffix = "\\%" if percent else ""
    return f"{mean:05.{decimals}f} ± {var:05.{decimals}f}{suffix}"

combined = summary_flat[["model", "incident"]].copy()
for metric in METRIC_COLS:
    combined[metric] = [
        fmt_mean_var(m, v, decimals=2 if metric not in ["loss"] else 4, percent=True if metric not in ["loss"] else False)
        for m, v in zip(summary_flat[f"{metric}_mean"], summary_flat[f"{metric}_var"])
    ]

def load_dataset_stats(model: str, incident: str, run_dir: Path) -> dict | None:
    params_path = run_dir / "params.yaml"
    if not params_path.exists():
        return None
    with open(params_path) as f:
        params = yaml.safe_load(f)
    stats = params["dataset"]["stats"]
    return {
        "model": model,
        "incident": incident,
        "total_samples": stats["total_samples"],
        "anomaly_samples": stats["anomaly_samples"],
    }

dataset_stats = pd.DataFrame(
    [d for model, incident, path in RUN_ROWS
     if (d := load_dataset_stats(model, incident, path)) is not None]
)

combined = combined.merge(dataset_stats, on=["model", "incident"])
cols = ["model", "incident", "total_samples", "anomaly_samples"] + METRIC_COLS
combined = combined[cols]
combined

,model,incident,total_samples,anomaly_samples,precision_anomaly,recall_anomaly,f1_anomaly
0,XChainWatcher (single-chain comparison),Nomad,730,167,07.40 ± 02.74\%,16.17 ± 13.07\%,10.15 ± 05.15\%
1,XChainWatcher (single-chain comparison),Ronin \#1,2,2,00.00 ± 00.00\%,00.00 ± 00.00\%,00.00 ± 00.00\%
2,XScope (cross-chain model),Qubit,27,16,00.00 ± 00.00\%,00.00 ± 00.00\%,00.00 ± 00.00\%
3,XScope (cross-chain model),THORChain \#2,2,2,100.00 ± 00.00\%,90.00 ± 05.00\%,93.33 ± 02.22\%
4,XScope (cross-chain model),THORChain \#3,6,6,100.00 ± 00.00\%,100.00 ± 00.00\%,100.00 ± 00.00\%
5,XScope (single-chain model),Qubit,16,16,60.00 ± 30.00\%,60.00 ± 30.00\%,60.00 ± 30.00\%
6,XScope (single-chain model),THORChain \#1,6,6,100.00 ± 00.00\%,100.00 ± 00.00\%,100.00 ± 00.00\%
7,XScope (single-chain model),THORChain \#2,15,15,00.00 ± 00.00\%,00.00 ± 00.00\%,00.00 ± 00.00\%
8,XScope (single-chain model),THORChain \#3,8,6,00.00 ± 00.00\%,00.00 ± 00.00\%,00.00 ± 00.00\%

In [33]:
combined_latex_ready = combined.copy()
for metric in METRIC_COLS:
    combined_latex_ready[metric] = combined_latex_ready[metric].str.replace(
        "±", r"$\pm$", regex=False
    )

combined_latex_ready = combined_latex_ready.set_index(["model", "incident"])

latex_combined = combined_latex_ready.to_latex(
    multirow=True,
    escape=False,
    caption="Cross-incident evaluation metrics based on incidents identified by earlier models.",
    label="table:evaluation-cross-eval-incidents",
)
print(latex_combined)
# NOTE: Requires `multirow` package in LaTeX

\begin{table}
\caption{Cross-incident evaluation metrics based on incidents identified by earlier models.}
\label{table:evaluation-cross-eval-incidents}
\begin{tabular}{llrrlll}
\toprule
 &  & total_samples & anomaly_samples & precision_anomaly & recall_anomaly & f1_anomaly \\
model & incident &  &  &  &  &  \\
\midrule
\multirow[t]{2}{*}{XChainWatcher (single-chain comparison)} & Nomad & 730 & 167 & 07.40 $\pm$ 02.74\% & 16.17 $\pm$ 13.07\% & 10.15 $\pm$ 05.15\% \\
 & Ronin \#1 & 2 & 2 & 00.00 $\pm$ 00.00\% & 00.00 $\pm$ 00.00\% & 00.00 $\pm$ 00.00\% \\
\cline{1-7}
\multirow[t]{3}{*}{XScope (cross-chain model)} & Qubit & 27 & 16 & 00.00 $\pm$ 00.00\% & 00.00 $\pm$ 00.00\% & 00.00 $\pm$ 00.00\% \\
 & THORChain \#2 & 2 & 2 & 100.00 $\pm$ 00.00\% & 90.00 $\pm$ 05.00\% & 93.33 $\pm$ 02.22\% \\
 & THORChain \#3 & 6 & 6 & 100.00 $\pm$ 00.00\% & 100.00 $\pm$ 00.00\% & 100.00 $\pm$ 00.00\% \\
\cline{1-7}
\multirow[t]{4}{*}{XScope (single-chain model)} & Qubit & 16 & 16 & 60.00 $\pm$ 30.00\% & 60.00 $\pm$ 30.00\% & 60.00 $\pm$ 30.00\% \\
 & THORChain \#1 & 6 & 6 & 100.00 $\pm$ 00.00\% & 100.00 $\pm$ 00.00\% & 100.00 $\pm$ 00.00\% \\
 & THORChain \#2 & 15 & 15 & 00.00 $\pm$ 00.00\% & 00.00 $\pm$ 00.00\% & 00.00 $\pm$ 00.00\% \\
 & THORChain \#3 & 8 & 6 & 00.00 $\pm$ 00.00\% & 00.00 $\pm$ 00.00\% & 00.00 $\pm$ 00.00\% \\
\cline{1-7}
\bottomrule
\end{tabular}
\end{table}