# Single-chain context

In [1]:
import sys
from pathlib import Path

sys.path.insert(0, str(Path.cwd().parent))

from types import SimpleNamespace

from cli import Cli
from dataset_generator.types import DATASET_TYPE

# Define the absolute path for the root directory for outputs here (and if possible, make sure to have a prepared _dataset folder)
OUTPUTS_ROOT = Path("/home/gonca/Documents/GitHub/IST-Thesis/BridgeDefender/outputs/mlpbased-single-eval-tuningpooling-ronin12-omni-nomad-polyn-qubit-harmony-thor123-meter-hypr-xbridge")

/home/gonca/Documents/GitHub/IST-Thesis/BridgeDefender/.venv/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Test runs

The next cells will run the model training for different pooling layer strategies.

This process can take a long time to finish.

**If you already have the models trained, you can skip this section and go to the evaluation section.**

In [3]:
dataset_path = OUTPUTS_ROOT.absolute() / "_dataset"
fixed_args = {
    "device": "cpu",  # Change to "cuda" if you have a GPU and want to use it
    "dataset": DATASET_TYPE.SINGLE,
    "load_data": str(dataset_path),
    "new_dataset": None,
    "force_reload": False,
    "num_workers": 0,
    "tags": "mlpbased,tuningpooling",

    "num_epochs": 100,
    "learning_rate": 0.005,
    "augment_factor": 0,
    "dme_threshold": 0.5,
    "rm_semantic_fusion": True,
    "early_stopping": 15,
    "kfolds": 5,
    "first_layer_channels": 128,
    "hidden_channels": 64,
    "dropout": 0.5,
    "input_drop": 0.0,
    "att_drop": 0.0,
    "n_fp_layers": 2,
    "n_mlp_layers": 2,
    "activation": "relu",
    "residual": False,
    "random_seed": 42,
    "test_split": 0.15,
}

In [4]:
# Run for mean pooling
pooling = "mean"
Cli.train_model(SimpleNamespace(
    **fixed_args,
    pooling=pooling
))

Early stopping: 15
Exporting data from database to CSV files...

Processing single-chain graphs dataset: 100%|██████████| 1152/1152 [00:15<00:00, 73.50graph/s]

Splitting dataset into train/val/test sets with test size 15% and 5 folds for cross-validation.
Normalizing node features using min-max normalization.
Label distribution in train/val pool: 782 normal, 197 anomaly.
Identified 264 differential meta-paths for training.
Fold 1/5, epoch 1/100 — training...
  Fold 1, epoch 1, train loss: 0.3910, val loss: 0.1805, PR-AUC (anomaly): 0.8998, f2-score (anomaly): 0.9045
              precision    recall  f1-score   support

           0       0.98      0.96      0.97       157
           1       0.84      0.92      0.88        39

    accuracy                           0.95       196
   macro avg       0.91      0.94      0.92       196
weighted avg       0.95      0.95      0.95       196

Fold 1/5, epoch 2/100 — training...
  Fold 1, epoch 2, train loss: 0.1696, val loss: 0.0933, PR-AUC (anomaly): 0.9230, f2-score (anomaly): 0.9512
              precision    recall  f1-score   support

           0       1.00      0.94      0.97       157
           1       0.80      1.00      0.89        39

    accuracy                           0.95       196
   macro avg       0.90      0.97      0.93       196
weighted avg       0.96      0.95      0.95       196

Fold 1/5, epoch 3/100 — training...
  Fold 1, epoch 3, train loss: 0.1493, val loss: 0.0950, PR-AUC (anomaly): 0.9292, f2-score (anomaly): 0.9606
              precision    recall  f1-score   support

           0       1.00      0.95      0.97       157
           1       0.83      1.00      0.91        39

    accuracy                           0.96       196
   macro avg       0.91      0.97      0.94       196
weighted avg       0.97      0.96      0.96       196

Fold 1/5, epoch 4/100 — training...
  Fold 1, epoch 4, train loss: 0.1265, val loss: 0.0859, PR-AUC (anomaly): 0.9337, f2-score (anomaly): 0.9653
              precision    recall  f1-score   support

           0       1.00      0.96      0.98       157
           1       0.85      1.00      0.92        39

    accuracy                           0.96       196
   macro avg       0.92      0.98      0.95       196
weighted avg       0.97      0.96      0.97       196

Fold 1/5, epoch 5/100 — training...
  Fold 1, epoch 5, train loss: 0.1034, val loss: 0.0777, PR-AUC (anomaly): 0.9384, f2-score (anomaly): 0.9653
              precision    recall  f1-score   support

           0       1.00      0.96      0.98       157
           1       0.85      1.00      0.92        39

    accuracy                           0.96       196
   macro avg       0.92      0.98      0.95       196
weighted avg       0.97      0.96      0.97       196

Fold 1/5, epoch 6/100 — training...
  Fold 1, epoch 6, train loss: 0.1119, val loss: 0.0949, PR-AUC (anomaly): 0.9320, f2-score (anomaly): 0.9466
              precision    recall  f1-score   support

           0       1.00      0.93      0.96       157
           1       0.78      1.00      0.88        39

    accuracy                           0.94       196
   macro avg       0.89      0.96      0.92       196
weighted avg       0.96      0.94      0.95       196

Fold 1/5, epoch 7/100 — training...
  Fold 1, epoch 7, train loss: 0.1125, val loss: 0.1382, PR-AUC (anomaly): 0.9047, f2-score (anomaly): 0.9045
              precision    recall  f1-score   support

           0       0.98      0.96      0.97       157
           1       0.84      0.92      0.88        39

    accuracy                           0.95       196
   macro avg       0.91      0.94      0.92       196
weighted avg       0.95      0.95      0.95       196

Fold 1/5, epoch 8/100 — training...
  Fold 1, epoch 8, train loss: 0.1170, val loss: 0.0871, PR-AUC (anomaly): 0.9517, f2-score (anomaly): 0.9653
              precision    recall  f1-score   support

           0       1.00      0.96      0.98       157
           1       0.85      1.00      0.92        39

    accuracy                           0.96       196
   macro avg       0.92      0.98      0.95       196
weighted avg       0.97      0.96      0.97       196

Fold 1/5, epoch 9/100 — training...
  Fold 1, epoch 9, train loss: 0.1392, val loss: 0.0893, PR-AUC (anomaly): 0.9273, f2-score (anomaly): 0.9606
              precision    recall  f1-score   support

           0       1.00      0.95      0.97       157
           1       0.83      1.00      0.91        39

    accuracy                           0.96       196
   macro avg       0.91      0.97      0.94       196
weighted avg       0.97      0.96      0.96       196

Fold 1/5, epoch 10/100 — training...
  Fold 1, epoch 10, train loss: 0.1098, val loss: 0.0846, PR-AUC (anomaly): 0.9506, f2-score (anomaly): 0.9606
              precision    recall  f1-score   support

           0       1.00      0.95      0.97       157
           1       0.83      1.00      0.91        39

    accuracy                           0.96       196
   macro avg       0.91      0.97      0.94       196
weighted avg       0.97      0.96      0.96       196

Fold 1/5, epoch 11/100 — training...
  Fold 1, epoch 11, train loss: 0.1072, val loss: 0.0764, PR-AUC (anomaly): 0.9435, f2-score (anomaly): 0.9606
              precision    recall  f1-score   support

           0       1.00      0.95      0.97       157
           1       0.83      1.00      0.91        39

    accuracy                           0.96       196
   macro avg       0.91      0.97      0.94       196
weighted avg       0.97      0.96      0.96       196

Fold 1/5, epoch 12/100 — training...
  Fold 1, epoch 12, train loss: 0.1100, val loss: 0.0735, PR-AUC (anomaly): 0.9563, f2-score (anomaly): 0.9701
              precision    recall  f1-score   support

           0       1.00      0.96      0.98       157
           1       0.87      1.00      0.93        39

    accuracy                           0.97       196
   macro avg       0.93      0.98      0.95       196
weighted avg       0.97      0.97      0.97       196

Fold 1/5, epoch 13/100 — training...
  Fold 1, epoch 13, train loss: 0.0909, val loss: 0.0651, PR-AUC (anomaly): 0.9848, f2-score (anomaly): 0.9606
              precision    recall  f1-score   support

           0       1.00      0.95      0.97       157
           1       0.83      1.00      0.91        39

    accuracy                           0.96       196
   macro avg       0.91      0.97      0.94       196
weighted avg       0.97      0.96      0.96       196

Fold 1/5, epoch 14/100 — training...
  Fold 1, epoch 14, train loss: 0.1072, val loss: 0.0825, PR-AUC (anomaly): 0.9429, f2-score (anomaly): 0.9701
              precision    recall  f1-score   support

           0       1.00      0.96      0.98       157
           1       0.87      1.00      0.93        39

    accuracy                           0.97       196
   macro avg       0.93      0.98      0.95       196
weighted avg       0.97      0.97      0.97       196

Fold 1/5, epoch 15/100 — training...
  Fold 1, epoch 15, train loss: 0.1202, val loss: 0.0747, PR-AUC (anomaly): 0.9493, f2-score (anomaly): 0.9606
              precision    recall  f1-score   support

           0       1.00      0.95      0.97       157
           1       0.83      1.00      0.91        39

    accuracy                           0.96       196
   macro avg       0.91      0.97      0.94       196
weighted avg       0.97      0.96      0.96       196

Fold 1/5, epoch 16/100 — training...
  Fold 1, epoch 16, train loss: 0.0923, val loss: 0.0555, PR-AUC (anomaly): 0.9514, f2-score (anomaly): 0.9750
              precision    recall  f1-score   support

           0       1.00      0.97      0.98       157
           1       0.89      1.00      0.94        39

    accuracy                           0.97       196
   macro avg       0.94      0.98      0.96       196
weighted avg       0.98      0.97      0.98       196

Fold 1/5, epoch 17/100 — training...
  Fold 1, epoch 17, train loss: 0.0816, val loss: 0.0525, PR-AUC (anomaly): 0.9689, f2-score (anomaly): 0.9750
              precision    recall  f1-score   support

           0       1.00      0.97      0.98       157
           1       0.89      1.00      0.94        39

    accuracy                           0.97       196
   macro avg       0.94      0.98      0.96       196
weighted avg       0.98      0.97      0.98       196

Fold 1/5, epoch 18/100 — training...
  Fold 1, epoch 18, train loss: 0.0888, val loss: 0.0489, PR-AUC (anomaly): 0.9689, f2-score (anomaly): 0.9799
              precision    recall  f1-score   support

           0       1.00      0.97      0.99       157
           1       0.91      1.00      0.95        39

    accuracy                           0.98       196
   macro avg       0.95      0.99      0.97       196
weighted avg       0.98      0.98      0.98       196

Fold 1/5, epoch 19/100 — training...
  Fold 1, epoch 19, train loss: 0.1010, val loss: 0.0533, PR-AUC (anomaly): 0.9578, f2-score (anomaly): 0.9799
              precision    recall  f1-score   support

           0       1.00      0.97      0.99       157
           1       0.91      1.00      0.95        39

    accuracy                           0.98       196
   macro avg       0.95      0.99      0.97       196
weighted avg       0.98      0.98      0.98       196

Fold 1/5, epoch 20/100 — training...
  Fold 1, epoch 20, train loss: 0.0799, val loss: 0.0553, PR-AUC (anomaly): 0.9718, f2-score (anomaly): 0.9653
              precision    recall  f1-score   support

           0       1.00      0.96      0.98       157
           1       0.85      1.00      0.92        39

    accuracy                           0.96       196
   macro avg       0.92      0.98      0.95       196
weighted avg       0.97      0.96      0.97       196

Fold 1/5, epoch 21/100 — training...
  Fold 1, epoch 21, train loss: 0.0718, val loss: 0.0503, PR-AUC (anomaly): 0.9653, f2-score (anomaly): 0.9799
              precision    recall  f1-score   support

           0       1.00      0.97      0.99       157
           1       0.91      1.00      0.95        39

    accuracy                           0.98       196
   macro avg       0.95      0.99      0.97       196
weighted avg       0.98      0.98      0.98       196

Fold 1/5, epoch 22/100 — training...
  Fold 1, epoch 22, train loss: 0.0877, val loss: 0.0568, PR-AUC (anomaly): 0.9676, f2-score (anomaly): 0.9799
              precision    recall  f1-score   support

           0       1.00      0.97      0.99       157
           1       0.91      1.00      0.95        39

    accuracy                           0.98       196
   macro avg       0.95      0.99      0.97       196
weighted avg       0.98      0.98      0.98       196

Fold 1/5, epoch 23/100 — training...
  Fold 1, epoch 23, train loss: 0.0786, val loss: 0.0449, PR-AUC (anomaly): 0.9718, f2-score (anomaly): 0.9799
              precision    recall  f1-score   support

           0       1.00      0.97      0.99       157
           1       0.91      1.00      0.95        39

    accuracy                           0.98       196
   macro avg       0.95      0.99      0.97       196
weighted avg       0.98      0.98      0.98       196

Fold 1/5, epoch 24/100 — training...
  Fold 1, epoch 24, train loss: 0.0940, val loss: 0.0592, PR-AUC (anomaly): 0.9666, f2-score (anomaly): 0.9799
              precision    recall  f1-score   support

           0       1.00      0.97      0.99       157
           1       0.91      1.00      0.95        39

    accuracy                           0.98       196
   macro avg       0.95      0.99      0.97       196
weighted avg       0.98      0.98      0.98       196

Fold 1/5, epoch 25/100 — training...
  Fold 1, epoch 25, train loss: 0.1021, val loss: 0.0688, PR-AUC (anomaly): 0.9477, f2-score (anomaly): 0.9653
              precision    recall  f1-score   support

           0       1.00      0.96      0.98       157
           1       0.85      1.00      0.92        39

    accuracy                           0.96       196
   macro avg       0.92      0.98      0.95       196
weighted avg       0.97      0.96      0.97       196

Fold 1/5, epoch 26/100 — training...
  Fold 1, epoch 26, train loss: 0.0835, val loss: 0.0471, PR-AUC (anomaly): 0.9599, f2-score (anomaly): 0.9799
              precision    recall  f1-score   support

           0       1.00      0.97      0.99       157
           1       0.91      1.00      0.95        39

    accuracy                           0.98       196
   macro avg       0.95      0.99      0.97       196
weighted avg       0.98      0.98      0.98       196

Fold 1/5, epoch 27/100 — training...
  Fold 1, epoch 27, train loss: 0.0886, val loss: 0.0467, PR-AUC (anomaly): 0.9619, f2-score (anomaly): 0.9799
              precision    recall  f1-score   support

           0       1.00      0.97      0.99       157
           1       0.91      1.00      0.95        39

    accuracy                           0.98       196
   macro avg       0.95      0.99      0.97       196
weighted avg       0.98      0.98      0.98       196

Fold 1/5, epoch 28/100 — training...
  Fold 1, epoch 28, train loss: 0.0598, val loss: 0.0446, PR-AUC (anomaly): 0.9619, f2-score (anomaly): 0.9799
              precision    recall  f1-score   support

           0       1.00      0.97      0.99       157
           1       0.91      1.00      0.95        39

    accuracy                           0.98       196
   macro avg       0.95      0.99      0.97       196
weighted avg       0.98      0.98      0.98       196

Fold 1/5, epoch 29/100 — training...
  Fold 1, epoch 29, train loss: 0.0717, val loss: 0.0564, PR-AUC (anomaly): 0.9616, f2-score (anomaly): 0.9750
              precision    recall  f1-score   support

           0       1.00      0.97      0.98       157
           1       0.89      1.00      0.94        39

    accuracy                           0.97       196
   macro avg       0.94      0.98      0.96       196
weighted avg       0.98      0.97      0.98       196

Fold 1/5, epoch 30/100 — training...
  Fold 1, epoch 30, train loss: 0.0716, val loss: 0.0493, PR-AUC (anomaly): 0.9854, f2-score (anomaly): 0.9799
              precision    recall  f1-score   support

           0       1.00      0.97      0.99       157
           1       0.91      1.00      0.95        39

    accuracy                           0.98       196
   macro avg       0.95      0.99      0.97       196
weighted avg       0.98      0.98      0.98       196

Fold 1/5, epoch 31/100 — training...
  Fold 1, epoch 31, train loss: 0.0779, val loss: 0.0498, PR-AUC (anomaly): 0.9778, f2-score (anomaly): 0.9799
              precision    recall  f1-score   support

           0       1.00      0.97      0.99       157
           1       0.91      1.00      0.95        39

    accuracy                           0.98       196
   macro avg       0.95      0.99      0.97       196
weighted avg       0.98      0.98      0.98       196

Fold 1/5, epoch 32/100 — training...
  Fold 1, epoch 32, train loss: 0.0779, val loss: 0.0510, PR-AUC (anomaly): 0.9620, f2-score (anomaly): 0.9701
              precision    recall  f1-score   support

           0       1.00      0.96      0.98       157
           1       0.87      1.00      0.93        39

    accuracy                           0.97       196
   macro avg       0.93      0.98      0.95       196
weighted avg       0.97      0.97      0.97       196

Fold 1/5, epoch 33/100 — training...
  Fold 1, epoch 33, train loss: 0.0890, val loss: 0.0471, PR-AUC (anomaly): 0.9786, f2-score (anomaly): 0.9799
              precision    recall  f1-score   support

           0       1.00      0.97      0.99       157
           1       0.91      1.00      0.95        39

    accuracy                           0.98       196
   macro avg       0.95      0.99      0.97       196
weighted avg       0.98      0.98      0.98       196

Early stopping triggered at epoch 33 for fold 1.
Saved fold 1 best model to /home/gonca/Documents/GitHub/IST-Thesis/BridgeDefender/outputs/mlpbased-single-eval-tuningpooling-ronin12-omni-nomad-polyn-qubit-harmony-thor123-meter-hypr-xbridge/train_epochs100_augment0_lr0.005_nosf_es15_mlpbased_tuningpooling__202608102150/models/fold_1.pt
Fold 2/5, epoch 1/100 — training...
  Fold 2, epoch 1, train loss: 0.5523, val loss: 0.2936, PR-AUC (anomaly): 0.8645, f2-score (anomaly): 0.8413
              precision    recall  f1-score   support

           0       0.97      0.89      0.93       157
           1       0.67      0.90      0.77        39

    accuracy                           0.89       196
   macro avg       0.82      0.89      0.85       196
weighted avg       0.91      0.89      0.90       196

Fold 2/5, epoch 2/100 — training...
  Fold 2, epoch 2, train loss: 0.2107, val loss: 0.2025, PR-AUC (anomaly): 0.8430, f2-score (anomaly): 0.9113
              precision    recall  f1-score   support

           0       0.99      0.94      0.96       157
           1       0.79      0.95      0.86        39

    accuracy                           0.94       196
   macro avg       0.89      0.94      0.91       196
weighted avg       0.95      0.94      0.94       196

Fold 2/5, epoch 3/100 — training...
  Fold 2, epoch 3, train loss: 0.1326, val loss: 0.2059, PR-AUC (anomaly): 0.8697, f2-score (anomaly): 0.9420
              precision    recall  f1-score   support

           0       1.00      0.92      0.96       157
           1       0.76      1.00      0.87        39

    accuracy                           0.94       196
   macro avg       0.88      0.96      0.91       196
weighted avg       0.95      0.94      0.94       196

Fold 2/5, epoch 4/100 — training...
  Fold 2, epoch 4, train loss: 0.1221, val loss: 0.1718, PR-AUC (anomaly): 0.8571, f2-score (anomaly): 0.9466
              precision    recall  f1-score   support

           0       1.00      0.93      0.96       157
           1       0.78      1.00      0.88        39

    accuracy                           0.94       196
   macro avg       0.89      0.96      0.92       196
weighted avg       0.96      0.94      0.95       196

Fold 2/5, epoch 5/100 — training...
  Fold 2, epoch 5, train loss: 0.0957, val loss: 0.1706, PR-AUC (anomaly): 0.9303, f2-score (anomaly): 0.9406
              precision    recall  f1-score   support

           0       0.99      0.95      0.97       157
           1       0.83      0.97      0.89        39

    accuracy                           0.95       196
   macro avg       0.91      0.96      0.93       196
weighted avg       0.96      0.95      0.96       196

Fold 2/5, epoch 6/100 — training...
  Fold 2, epoch 6, train loss: 0.0793, val loss: 0.1770, PR-AUC (anomaly): 0.9447, f2-score (anomaly): 0.9360
              precision    recall  f1-score   support

           0       0.99      0.94      0.97       157
           1       0.81      0.97      0.88        39

    accuracy                           0.95       196
   macro avg       0.90      0.96      0.93       196
weighted avg       0.96      0.95      0.95       196

Fold 2/5, epoch 7/100 — training...
  Fold 2, epoch 7, train loss: 0.1045, val loss: 0.1861, PR-AUC (anomaly): 0.9413, f2-score (anomaly): 0.9314
              precision    recall  f1-score   support

           0       0.99      0.94      0.96       157
           1       0.79      0.97      0.87        39

    accuracy                           0.94       196
   macro avg       0.89      0.96      0.92       196
weighted avg       0.95      0.94      0.95       196

Fold 2/5, epoch 8/100 — training...
  Fold 2, epoch 8, train loss: 0.0784, val loss: 0.1488, PR-AUC (anomaly): 0.9633, f2-score (anomaly): 0.9453
              precision    recall  f1-score   support

           0       0.99      0.96      0.97       157
           1       0.84      0.97      0.90        39

    accuracy                           0.96       196
   macro avg       0.92      0.96      0.94       196

'/home/gonca/Documents/GitHub/IST-Thesis/BridgeDefender/outputs/mlpbased-single-eval-tuningpooling-ronin12-omni-nomad-polyn-qubit-harmony-thor123-meter-hypr-xbridge/train_epochs100_augment0_lr0.005_nosf_es15_mlpbased_tuningpooling__202608102150'

In [5]:
# Run for max pooling
pooling = "max"
Cli.train_model(SimpleNamespace(
    **fixed_args,
    pooling=pooling
))

Early stopping: 15
Exporting data from database to CSV files...
Splitting dataset into train/val/test sets with test size 15% and 5 folds for cross-validation.
Normalizing node features using min-max normalization.
Label distribution in train/val pool: 782 normal, 197 anomaly.
Identified 264 differential meta-paths for training.
Fold 1/5, epoch 1/100 — training...
  Fold 1, epoch 1, train loss: 0.3763, val loss: 0.1536, PR-AUC (anomaly): 0.9183, f2-score (anomaly): 0.9559
              precision    recall  f1-score   support

           0       1.00      0.94      0.97       157
           1       0.81      1.00      0.90        39

    accuracy                           0.95       196
   macro avg       0.91      0.97      0.93       196
weighted avg       0.96      0.95      0.96       196

Fold 1/5, epoch 2/100 — training...
  Fold 1, epoch 2, train loss: 0.1715, val loss: 0.0981, PR-AUC (anomaly): 0.9090, f2-score (anomaly): 0.9653
              precision    recall  f1-score   support

           0       1.00      0.96      0.98       157
           1       0.85      1.00      0.92        39

    accuracy                           0.96       196
   macro avg       0.92      0.98      0.95       196
weighted avg       0.97      0.96      0.97       196

Fold 1/5, epoch 3/100 — training...
  Fold 1, epoch 3, train loss: 0.1488, val loss: 0.0972, PR-AUC (anomaly): 0.9256, f2-score (anomaly): 0.9653
              precision    recall  f1-score   support

           0       1.00      0.96      0.98       157
           1       0.85      1.00      0.92        39

    accuracy                           0.96       196
   macro avg       0.92      0.98      0.95       196
weighted avg       0.97      0.96      0.97       196

Fold 1/5, epoch 4/100 — training...
  Fold 1, epoch 4, train loss: 0.1323, val loss: 0.0917, PR-AUC (anomaly): 0.9240, f2-score (anomaly): 0.9606
              precision    recall  f1-score   support

           0       1.00      0.95      0.97       157
           1       0.83      1.00      0.91        39

    accuracy                           0.96       196
   macro avg       0.91      0.97      0.94       196
weighted avg       0.97      0.96      0.96       196

Fold 1/5, epoch 5/100 — training...
  Fold 1, epoch 5, train loss: 0.1008, val loss: 0.0737, PR-AUC (anomaly): 0.9478, f2-score (anomaly): 0.9653
              precision    recall  f1-score   support

           0       1.00      0.96      0.98       157
           1       0.85      1.00      0.92        39

    accuracy                           0.96       196
   macro avg       0.92      0.98      0.95       196
weighted avg       0.97      0.96      0.97       196

Fold 1/5, epoch 6/100 — training...
  Fold 1, epoch 6, train loss: 0.1192, val loss: 0.0877, PR-AUC (anomaly): 0.9509, f2-score (anomaly): 0.9512
              precision    recall  f1-score   support

           0       1.00      0.94      0.97       157
           1       0.80      1.00      0.89        39

    accuracy                           0.95       196
   macro avg       0.90      0.97      0.93       196
weighted avg       0.96      0.95      0.95       196

Fold 1/5, epoch 7/100 — training...
  Fold 1, epoch 7, train loss: 0.0990, val loss: 0.0559, PR-AUC (anomaly): 0.9663, f2-score (anomaly): 0.9750
              precision    recall  f1-score   support

           0       1.00      0.97      0.98       157
           1       0.89      1.00      0.94        39

    accuracy                           0.97       196
   macro avg       0.94      0.98      0.96       196
weighted avg       0.98      0.97      0.98       196

Fold 1/5, epoch 8/100 — training...
  Fold 1, epoch 8, train loss: 0.0826, val loss: 0.0526, PR-AUC (anomaly): 0.9656, f2-score (anomaly): 0.9750
              precision    recall  f1-score   support

           0       1.00      0.97      0.98       157
           1       0.89      1.00      0.94        39

    accuracy                           0.97       196
   macro avg       0.94      0.98      0.96       196
weighted avg       0.98      0.97      0.98       196

Fold 1/5, epoch 9/100 — training...
  Fold 1, epoch 9, train loss: 0.0856, val loss: 0.0543, PR-AUC (anomaly): 0.9652, f2-score (anomaly): 0.9750
              precision    recall  f1-score   support

           0       1.00      0.97      0.98       157
           1       0.89      1.00      0.94        39

    accuracy                           0.97       196
   macro avg       0.94      0.98      0.96       196
weighted avg       0.98      0.97      0.98       196

Fold 1/5, epoch 10/100 — training...
  Fold 1, epoch 10, train loss: 0.1038, val loss: 0.0900, PR-AUC (anomaly): 0.9020, f2-score (anomaly): 0.9606
              precision    recall  f1-score   support

           0       1.00      0.95      0.97       157
           1       0.83      1.00      0.91        39

    accuracy                           0.96       196
   macro avg       0.91      0.97      0.94       196
weighted avg       0.97      0.96      0.96       196

Fold 1/5, epoch 11/100 — training...
  Fold 1, epoch 11, train loss: 0.1170, val loss: 0.0829, PR-AUC (anomaly): 0.9421, f2-score (anomaly): 0.9606
              precision    recall  f1-score   support

           0       1.00      0.95      0.97       157
           1       0.83      1.00      0.91        39

    accuracy                           0.96       196
   macro avg       0.91      0.97      0.94       196
weighted avg       0.97      0.96      0.96       196

Fold 1/5, epoch 12/100 — training...
  Fold 1, epoch 12, train loss: 0.0987, val loss: 0.0577, PR-AUC (anomaly): 0.9695, f2-score (anomaly): 0.9750
              precision    recall  f1-score   support

           0       1.00      0.97      0.98       157
           1       0.89      1.00      0.94        39

    accuracy                           0.97       196
   macro avg       0.94      0.98      0.96       196
weighted avg       0.98      0.97      0.98       196

Fold 1/5, epoch 13/100 — training...
  Fold 1, epoch 13, train loss: 0.1055, val loss: 0.0699, PR-AUC (anomaly): 0.9631, f2-score (anomaly): 0.9701
              precision    recall  f1-score   support

           0       1.00      0.96      0.98       157
           1       0.87      1.00      0.93        39

    accuracy                           0.97       196
   macro avg       0.93      0.98      0.95       196
weighted avg       0.97      0.97      0.97       196

Fold 1/5, epoch 14/100 — training...
  Fold 1, epoch 14, train loss: 0.0802, val loss: 0.0558, PR-AUC (anomaly): 0.9603, f2-score (anomaly): 0.9799
              precision    recall  f1-score   support

           0       1.00      0.97      0.99       157
           1       0.91      1.00      0.95        39

    accuracy                           0.98       196
   macro avg       0.95      0.99      0.97       196
weighted avg       0.98      0.98      0.98       196

Fold 1/5, epoch 15/100 — training...
  Fold 1, epoch 15, train loss: 0.0811, val loss: 0.0580, PR-AUC (anomaly): 0.9453, f2-score (anomaly): 0.9750
              precision    recall  f1-score   support

           0       1.00      0.97      0.98       157
           1       0.89      1.00      0.94        39

    accuracy                           0.97       196
   macro avg       0.94      0.98      0.96       196
weighted avg       0.98      0.97      0.98       196

Fold 1/5, epoch 16/100 — training...
  Fold 1, epoch 16, train loss: 0.0751, val loss: 0.0564, PR-AUC (anomaly): 0.9563, f2-score (anomaly): 0.9750
              precision    recall  f1-score   support

           0       1.00      0.97      0.98       157
           1       0.89      1.00      0.94        39

    accuracy                           0.97       196
   macro avg       0.94      0.98      0.96       196
weighted avg       0.98      0.97      0.98       196

Fold 1/5, epoch 17/100 — training...
  Fold 1, epoch 17, train loss: 0.1038, val loss: 0.0687, PR-AUC (anomaly): 0.9477, f2-score (anomaly): 0.9653
              precision    recall  f1-score   support

           0       1.00      0.96      0.98       157
           1       0.85      1.00      0.92        39

    accuracy                           0.96       196
   macro avg       0.92      0.98      0.95       196
weighted avg       0.97      0.96      0.97       196

Fold 1/5, epoch 18/100 — training...
  Fold 1, epoch 18, train loss: 0.1046, val loss: 0.0569, PR-AUC (anomaly): 0.9602, f2-score (anomaly): 0.9799
              precision    recall  f1-score   support

           0       1.00      0.97      0.99       157
           1       0.91      1.00      0.95        39

    accuracy                           0.98       196
   macro avg       0.95      0.99      0.97       196
weighted avg       0.98      0.98      0.98       196

Fold 1/5, epoch 19/100 — training...
  Fold 1, epoch 19, train loss: 0.1046, val loss: 0.0513, PR-AUC (anomaly): 0.9603, f2-score (anomaly): 0.9799
              precision    recall  f1-score   support

           0       1.00      0.97      0.99       157
           1       0.91      1.00      0.95        39

    accuracy                           0.98       196
   macro avg       0.95      0.99      0.97       196
weighted avg       0.98      0.98      0.98       196

Fold 1/5, epoch 20/100 — training...
  Fold 1, epoch 20, train loss: 0.1065, val loss: 0.0567, PR-AUC (anomaly): 0.9597, f2-score (anomaly): 0.9799
              precision    recall  f1-score   support

           0       1.00      0.97      0.99       157
           1       0.91      1.00      0.95        39

    accuracy                           0.98       196
   macro avg       0.95      0.99      0.97       196
weighted avg       0.98      0.98      0.98       196

Fold 1/5, epoch 21/100 — training...
  Fold 1, epoch 21, train loss: 0.0771, val loss: 0.0486, PR-AUC (anomaly): 0.9656, f2-score (anomaly): 0.9799
              precision    recall  f1-score   support

           0       1.00      0.97      0.99       157
           1       0.91      1.00      0.95        39

    accuracy                           0.98       196
   macro avg       0.95      0.99      0.97       196
weighted avg       0.98      0.98      0.98       196

Fold 1/5, epoch 22/100 — training...
  Fold 1, epoch 22, train loss: 0.0817, val loss: 0.0571, PR-AUC (anomaly): 0.9676, f2-score (anomaly): 0.9799
              precision    recall  f1-score   support

           0       1.00      0.97      0.99       157
           1       0.91      1.00      0.95        39

    accuracy                           0.98       196
   macro avg       0.95      0.99      0.97       196
weighted avg       0.98      0.98      0.98       196

Fold 1/5, epoch 23/100 — training...
  Fold 1, epoch 23, train loss: 0.0747, val loss: 0.0481, PR-AUC (anomaly): 0.9676, f2-score (anomaly): 0.9799
              precision    recall  f1-score   support

           0       1.00      0.97      0.99       157
           1       0.91      1.00      0.95        39

    accuracy                           0.98       196
   macro avg       0.95      0.99      0.97       196
weighted avg       0.98      0.98      0.98       196

Fold 1/5, epoch 24/100 — training...
  Fold 1, epoch 24, train loss: 0.0659, val loss: 0.0485, PR-AUC (anomaly): 0.9676, f2-score (anomaly): 0.9799
              precision    recall  f1-score   support

           0       1.00      0.97      0.99       157
           1       0.91      1.00      0.95        39

    accuracy                           0.98       196
   macro avg       0.95      0.99      0.97       196
weighted avg       0.98      0.98      0.98       196

Fold 1/5, epoch 25/100 — training...
  Fold 1, epoch 25, train loss: 0.0958, val loss: 0.0765, PR-AUC (anomaly): 0.9715, f2-score (anomaly): 0.9750
              precision    recall  f1-score   support

           0       1.00      0.97      0.98       157
           1       0.89      1.00      0.94        39

    accuracy                           0.97       196
   macro avg       0.94      0.98      0.96       196
weighted avg       0.98      0.97      0.98       196

Fold 1/5, epoch 26/100 — training...
  Fold 1, epoch 26, train loss: 0.0742, val loss: 0.0587, PR-AUC (anomaly): 0.9676, f2-score (anomaly): 0.9799
              precision    recall  f1-score   support

           0       1.00      0.97      0.99       157
           1       0.91      1.00      0.95        39

    accuracy                           0.98       196
   macro avg       0.95      0.99      0.97       196
weighted avg       0.98      0.98      0.98       196

Fold 1/5, epoch 27/100 — training...
  Fold 1, epoch 27, train loss: 0.0739, val loss: 0.0512, PR-AUC (anomaly): 0.9676, f2-score (anomaly): 0.9799
              precision    recall  f1-score   support

           0       1.00      0.97      0.99       157
           1       0.91      1.00      0.95        39

    accuracy                           0.98       196
   macro avg       0.95      0.99      0.97       196
weighted avg       0.98      0.98      0.98       196

Fold 1/5, epoch 28/100 — training...
  Fold 1, epoch 28, train loss: 0.0643, val loss: 0.0590, PR-AUC (anomaly): 0.9676, f2-score (anomaly): 0.9799
              precision    recall  f1-score   support

           0       1.00      0.97      0.99       157
           1       0.91      1.00      0.95        39

    accuracy                           0.98       196
   macro avg       0.95      0.99      0.97       196
weighted avg       0.98      0.98      0.98       196

Fold 1/5, epoch 29/100 — training...
  Fold 1, epoch 29, train loss: 0.0904, val loss: 0.1515, PR-AUC (anomaly): 0.9676, f2-score (anomaly): 0.8945
              precision    recall  f1-score   support

           0       1.00      0.85      0.92       157
           1       0.63      1.00      0.77        39

    accuracy                           0.88       196
   macro avg       0.81      0.93      0.85       196
weighted avg       0.93      0.88      0.89       196

Early stopping triggered at epoch 29 for fold 1.
Saved fold 1 best model to /home/gonca/Documents/GitHub/IST-Thesis/BridgeDefender/outputs/mlpbased-single-eval-tuningpooling-ronin12-omni-nomad-polyn-qubit-harmony-thor123-meter-hypr-xbridge/train_epochs100_augment0_lr0.005_poolmax_nosf_es15_mlpbased_tuningpooling__202608102155/models/fold_1.pt
Fold 2/5, epoch 1/100 — training...
  Fold 2, epoch 1, train loss: 0.4009, val loss: 0.3090, PR-AUC (anomaly): 0.8738, f2-score (anomaly): 0.7732
              precision    recall  f1-score   support

           0       0.94      0.95      0.95       157
           1       0.79      0.77      0.78        39

    accuracy                           0.91       196
   macro avg       0.87      0.86      0.86       196
weighted avg       0.91      0.91      0.91       196

Fold 2/5, epoch 2/100 — training...
  Fold 2, epoch 2, train loss: 0.1978, val loss: 0.1884, PR-AUC (anomaly): 0.8420, f2-score (anomaly): 0.9512
              precision    recall  f1-score   support

           0       1.00      0.94      0.97       157
           1       0.80      1.00      0.89        39

    accuracy                           0.95       196
   macro avg       0.90      0.97      0.93       196
weighted avg       0.96      0.95      0.95       196

Fold 2/5, epoch 3/100 — training...
  Fold 2, epoch 3, train loss: 0.1034, val loss: 0.1548, PR-AUC (anomaly): 0.8573, f2-score (anomaly): 0.9512
              precision    recall  f1-score   support

           0       1.00      0.94      0.97       157
           1       0.80      1.00      0.89        39

    accuracy                           0.95       196
   macro avg       0.90      0.97      0.93       196
weighted avg       0.96      0.95      0.95       196

Fold 2/5, epoch 4/100 — training...
  Fold 2, epoch 4, train loss: 0.1181, val loss: 0.1903, PR-AUC (anomaly): 0.8813, f2-score (anomaly): 0.9420
              precision    recall  f1-score   support

           0       1.00      0.92      0.96       157
           1       0.76      1.00      0.87        39

    accuracy                           0.94       196
   macro avg       0.88      0.96      0.91       196
weighted avg       0.95      0.94      0.94       196

Fold 2/5, epoch 5/100 — training...
  Fold 2, epoch 5, train loss: 0.0867, val loss: 0.1560, PR-AUC (anomaly): 0.8950, f2-score (anomaly): 0.9512
              precision    recall  f1-score   support

           0       1.00      0.94      0.97       157
           1       0.80      1.00      0.89        39

    accuracy                           0.95       196
   macro avg       0.90      0.97      0.93       196
weighted avg       0.96      0.95      0.95       196

Fold 2/5, epoch 6/100 — training...
  Fold 2, epoch 6, train loss: 0.0788, val loss: 0.1717, PR-AUC (anomaly): 0.9522, f2-score (anomaly): 0.9406
              precision    recall  f1-score   support

           0       0.99      0.95      0.97       157
           1       0.83      0.97      0.89        39

    accuracy                           0.95       196
   macro avg       0.91      0.96      0.93       196
weighted avg       0.96      0.95      0.96       196

Fold 2/5, epoch 7/100 — training...
  Fold 2, epoch 7, train loss: 0.0680, val loss: 0.1522, PR-AUC (anomaly): 0.9653, f2-score (anomaly): 0.9453
              precision    recall  f1-score   support

           0       0.99      0.96      0.97       157
           1       0.84      0.97      0.90        39

    accuracy                           0.96       196
   macro avg       0.92      0.96      0.94       196
weighted avg       0.96      0.96      0.96       196

Fold 2/5, epoch 8/100 — training...
  Fold 2, epoch 8, train loss: 0.0567, val loss: 0.1609, PR-AUC (anomaly): 0.9653, f2-score (anomaly): 0.9250
              precision    recall  f1-score   support

           0       0.99      0.96      0.97       157
           1       0.84      0.95      0.89        39

    accuracy                           0.95       196
   macro avg       0.91      0.95      0.93       196
weighted avg       0.96      0.95      0.96       196

Fold 2/5, epoch 9/100 — training...
  Fold 2, epoch 9, train loss: 0.0562, val loss: 0.1785, PR-AUC (anomaly): 0.9692, f2-score (anomaly): 0.9453
              precision    recall  f1-score   support

           0       0.99      0.96      0.97       157
           1       0.84      0.97      0.90        39

    accuracy                           0.96       196
   macro avg       0.92      0.96      0.94       196
weighted avg       0.96      0.96      0.96       196

Fold 2/5, epoch 10/100 — training...
  Fold 2, epoch 10, train loss: 0.0794, val loss: 0.2054, PR-AUC (anomaly): 0.9687, f2-score (anomaly): 0.9453
              precision    recall  f1-score   support

           0       0.99      0.96      0.97       157
           1       0.84      0.97      0.90        39

    accuracy                           0.96       196
   macro avg       0.92      0.96      0.94       196
weighted avg       0.96      0.96      0.96       196

Fold 2/5, epoch 11/100 — training...
  Fold 2, epoch 11, train loss: 0.0648, val loss: 0.1358, PR-AUC (anomaly): 0.9647, f2-score (anomaly): 0.9453
              precision    recall  f1-score   support

           0       0.99      0.96      0.97       157
           1       0.84      0.97      0.90        39

    accuracy                           0.96       196
   macro avg       0.92      0.96      0.94       196
weighted avg       0.96      0.96      0.96       196

Fold 2/5, epoch 12/100 — training...
  Fold 2, epoch 12, train loss: 0.1102, val loss: 0.1534, PR-AUC (anomaly): 0.9663, f2-score (anomaly): 0.9250
              precision    recall  f1-score   support

           0       0.99      0.96      0.97       157
           1       0.84      0.95      0.89        39


'/home/gonca/Documents/GitHub/IST-Thesis/BridgeDefender/outputs/mlpbased-single-eval-tuningpooling-ronin12-omni-nomad-polyn-qubit-harmony-thor123-meter-hypr-xbridge/train_epochs100_augment0_lr0.005_poolmax_nosf_es15_mlpbased_tuningpooling__202608102155'

In [6]:
# Run for sum pooling
pooling = "sum"
Cli.train_model(SimpleNamespace(
    **fixed_args,
    pooling=pooling
))

Early stopping: 15
Exporting data from database to CSV files...
Splitting dataset into train/val/test sets with test size 15% and 5 folds for cross-validation.
Normalizing node features using min-max normalization.
Label distribution in train/val pool: 782 normal, 197 anomaly.
Identified 264 differential meta-paths for training.
Fold 1/5, epoch 1/100 — training...
  Fold 1, epoch 1, train loss: 0.4207, val loss: 0.1985, PR-AUC (anomaly): 0.8859, f2-score (anomaly): 0.9045
              precision    recall  f1-score   support

           0       0.98      0.96      0.97       157
           1       0.84      0.92      0.88        39

    accuracy                           0.95       196
   macro avg       0.91      0.94      0.92       196
weighted avg       0.95      0.95      0.95       196

Fold 1/5, epoch 2/100 — training...
  Fold 1, epoch 2, train loss: 0.1437, val loss: 0.0779, PR-AUC (anomaly): 0.9220, f2-score (anomaly): 0.9701
              precision    recall  f1-score   support

           0       1.00      0.96      0.98       157
           1       0.87      1.00      0.93        39

    accuracy                           0.97       196
   macro avg       0.93      0.98      0.95       196
weighted avg       0.97      0.97      0.97       196

Fold 1/5, epoch 3/100 — training...
  Fold 1, epoch 3, train loss: 0.1132, val loss: 0.0855, PR-AUC (anomaly): 0.9397, f2-score (anomaly): 0.9653
              precision    recall  f1-score   support

           0       1.00      0.96      0.98       157
           1       0.85      1.00      0.92        39

    accuracy                           0.96       196
   macro avg       0.92      0.98      0.95       196
weighted avg       0.97      0.96      0.97       196

Fold 1/5, epoch 4/100 — training...
  Fold 1, epoch 4, train loss: 0.0980, val loss: 0.0741, PR-AUC (anomaly): 0.9498, f2-score (anomaly): 0.9653
              precision    recall  f1-score   support

           0       1.00      0.96      0.98       157
           1       0.85      1.00      0.92        39

    accuracy                           0.96       196
   macro avg       0.92      0.98      0.95       196
weighted avg       0.97      0.96      0.97       196

Fold 1/5, epoch 5/100 — training...
  Fold 1, epoch 5, train loss: 0.0872, val loss: 0.0592, PR-AUC (anomaly): 0.9641, f2-score (anomaly): 0.9701
              precision    recall  f1-score   support

           0       1.00      0.96      0.98       157
           1       0.87      1.00      0.93        39

    accuracy                           0.97       196
   macro avg       0.93      0.98      0.95       196
weighted avg       0.97      0.97      0.97       196

Fold 1/5, epoch 6/100 — training...
  Fold 1, epoch 6, train loss: 0.0964, val loss: 0.0529, PR-AUC (anomaly): 0.9627, f2-score (anomaly): 0.9799
              precision    recall  f1-score   support

           0       1.00      0.97      0.99       157
           1       0.91      1.00      0.95        39

    accuracy                           0.98       196
   macro avg       0.95      0.99      0.97       196
weighted avg       0.98      0.98      0.98       196

Fold 1/5, epoch 7/100 — training...
  Fold 1, epoch 7, train loss: 0.0855, val loss: 0.0654, PR-AUC (anomaly): 0.9647, f2-score (anomaly): 0.9799
              precision    recall  f1-score   support

           0       1.00      0.97      0.99       157
           1       0.91      1.00      0.95        39

    accuracy                           0.98       196
   macro avg       0.95      0.99      0.97       196
weighted avg       0.98      0.98      0.98       196

Fold 1/5, epoch 8/100 — training...
  Fold 1, epoch 8, train loss: 0.1011, val loss: 0.0686, PR-AUC (anomaly): 0.9467, f2-score (anomaly): 0.9799
              precision    recall  f1-score   support

           0       1.00      0.97      0.99       157
           1       0.91      1.00      0.95        39

    accuracy                           0.98       196
   macro avg       0.95      0.99      0.97       196
weighted avg       0.98      0.98      0.98       196

Fold 1/5, epoch 9/100 — training...
  Fold 1, epoch 9, train loss: 0.1009, val loss: 0.0538, PR-AUC (anomaly): 0.9718, f2-score (anomaly): 0.9799
              precision    recall  f1-score   support

           0       1.00      0.97      0.99       157
           1       0.91      1.00      0.95        39

    accuracy                           0.98       196
   macro avg       0.95      0.99      0.97       196
weighted avg       0.98      0.98      0.98       196

Fold 1/5, epoch 10/100 — training...
  Fold 1, epoch 10, train loss: 0.0843, val loss: 0.0608, PR-AUC (anomaly): 0.9666, f2-score (anomaly): 0.9799
              precision    recall  f1-score   support

           0       1.00      0.97      0.99       157
           1       0.91      1.00      0.95        39

    accuracy                           0.98       196
   macro avg       0.95      0.99      0.97       196
weighted avg       0.98      0.98      0.98       196

Fold 1/5, epoch 11/100 — training...
  Fold 1, epoch 11, train loss: 0.0869, val loss: 0.0559, PR-AUC (anomaly): 0.9602, f2-score (anomaly): 0.9799
              precision    recall  f1-score   support

           0       1.00      0.97      0.99       157
           1       0.91      1.00      0.95        39

    accuracy                           0.98       196
   macro avg       0.95      0.99      0.97       196
weighted avg       0.98      0.98      0.98       196

Fold 1/5, epoch 12/100 — training...
  Fold 1, epoch 12, train loss: 0.0794, val loss: 0.0535, PR-AUC (anomaly): 0.9653, f2-score (anomaly): 0.9799
              precision    recall  f1-score   support

           0       1.00      0.97      0.99       157
           1       0.91      1.00      0.95        39

    accuracy                           0.98       196
   macro avg       0.95      0.99      0.97       196
weighted avg       0.98      0.98      0.98       196

Fold 1/5, epoch 13/100 — training...
  Fold 1, epoch 13, train loss: 0.0774, val loss: 0.0502, PR-AUC (anomaly): 0.9629, f2-score (anomaly): 0.9799
              precision    recall  f1-score   support

           0       1.00      0.97      0.99       157
           1       0.91      1.00      0.95        39

    accuracy                           0.98       196
   macro avg       0.95      0.99      0.97       196
weighted avg       0.98      0.98      0.98       196

Fold 1/5, epoch 14/100 — training...
  Fold 1, epoch 14, train loss: 0.0864, val loss: 0.0705, PR-AUC (anomaly): 0.9631, f2-score (anomaly): 0.9799
              precision    recall  f1-score   support

           0       1.00      0.97      0.99       157
           1       0.91      1.00      0.95        39

    accuracy                           0.98       196
   macro avg       0.95      0.99      0.97       196
weighted avg       0.98      0.98      0.98       196

Fold 1/5, epoch 15/100 — training...
  Fold 1, epoch 15, train loss: 0.1011, val loss: 0.0521, PR-AUC (anomaly): 0.9649, f2-score (anomaly): 0.9799
              precision    recall  f1-score   support

           0       1.00      0.97      0.99       157
           1       0.91      1.00      0.95        39

    accuracy                           0.98       196
   macro avg       0.95      0.99      0.97       196
weighted avg       0.98      0.98      0.98       196

Fold 1/5, epoch 16/100 — training...
  Fold 1, epoch 16, train loss: 0.0788, val loss: 0.0549, PR-AUC (anomaly): 0.9663, f2-score (anomaly): 0.9799
              precision    recall  f1-score   support

           0       1.00      0.97      0.99       157
           1       0.91      1.00      0.95        39

    accuracy                           0.98       196
   macro avg       0.95      0.99      0.97       196
weighted avg       0.98      0.98      0.98       196

Fold 1/5, epoch 17/100 — training...
  Fold 1, epoch 17, train loss: 0.0629, val loss: 0.0504, PR-AUC (anomaly): 0.9624, f2-score (anomaly): 0.9799
              precision    recall  f1-score   support

           0       1.00      0.97      0.99       157
           1       0.91      1.00      0.95        39

    accuracy                           0.98       196
   macro avg       0.95      0.99      0.97       196
weighted avg       0.98      0.98      0.98       196

Fold 1/5, epoch 18/100 — training...
  Fold 1, epoch 18, train loss: 0.0655, val loss: 0.0487, PR-AUC (anomaly): 0.9675, f2-score (anomaly): 0.9799
              precision    recall  f1-score   support

           0       1.00      0.97      0.99       157
           1       0.91      1.00      0.95        39

    accuracy                           0.98       196
   macro avg       0.95      0.99      0.97       196
weighted avg       0.98      0.98      0.98       196

Fold 1/5, epoch 19/100 — training...
  Fold 1, epoch 19, train loss: 0.0630, val loss: 0.0503, PR-AUC (anomaly): 0.9602, f2-score (anomaly): 0.9799
              precision    recall  f1-score   support

           0       1.00      0.97      0.99       157
           1       0.91      1.00      0.95        39

    accuracy                           0.98       196
   macro avg       0.95      0.99      0.97       196
weighted avg       0.98      0.98      0.98       196

Fold 1/5, epoch 20/100 — training...
  Fold 1, epoch 20, train loss: 0.1079, val loss: 0.0604, PR-AUC (anomaly): 0.9712, f2-score (anomaly): 0.9750
              precision    recall  f1-score   support

           0       1.00      0.97      0.98       157
           1       0.89      1.00      0.94        39

    accuracy                           0.97       196
   macro avg       0.94      0.98      0.96       196
weighted avg       0.98      0.97      0.98       196

Fold 1/5, epoch 21/100 — training...
  Fold 1, epoch 21, train loss: 0.0825, val loss: 0.0502, PR-AUC (anomaly): 0.9613, f2-score (anomaly): 0.9799
              precision    recall  f1-score   support

           0       1.00      0.97      0.99       157
           1       0.91      1.00      0.95        39

    accuracy                           0.98       196
   macro avg       0.95      0.99      0.97       196
weighted avg       0.98      0.98      0.98       196

Early stopping triggered at epoch 21 for fold 1.
Saved fold 1 best model to /home/gonca/Documents/GitHub/IST-Thesis/BridgeDefender/outputs/mlpbased-single-eval-tuningpooling-ronin12-omni-nomad-polyn-qubit-harmony-thor123-meter-hypr-xbridge/train_epochs100_augment0_lr0.005_poolsum_nosf_es15_mlpbased_tuningpooling__202608102201/models/fold_1.pt
Fold 2/5, epoch 1/100 — training...
  Fold 2, epoch 1, train loss: 0.3506, val loss: 0.2372, PR-AUC (anomaly): 0.8875, f2-score (anomaly): 0.9466
              precision    recall  f1-score   support

           0       1.00      0.93      0.96       157
           1       0.78      1.00      0.88        39

    accuracy                           0.94       196
   macro avg       0.89      0.96      0.92       196
weighted avg       0.96      0.94      0.95       196

Fold 2/5, epoch 2/100 — training...
  Fold 2, epoch 2, train loss: 0.1229, val loss: 0.1592, PR-AUC (anomaly): 0.9205, f2-score (anomaly): 0.9512
              precision    recall  f1-score   support

           0       1.00      0.94      0.97       157
           1       0.80      1.00      0.89        39

    accuracy                           0.95       196
   macro avg       0.90      0.97      0.93       196
weighted avg       0.96      0.95      0.95       196

Fold 2/5, epoch 3/100 — training...
  Fold 2, epoch 3, train loss: 0.1293, val loss: 0.1666, PR-AUC (anomaly): 0.9313, f2-score (anomaly): 0.9559
              precision    recall  f1-score   support

           0       1.00      0.94      0.97       157
           1       0.81      1.00      0.90        39

    accuracy                           0.95       196
   macro avg       0.91      0.97      0.93       196
weighted avg       0.96      0.95      0.96       196

Fold 2/5, epoch 4/100 — training...
  Fold 2, epoch 4, train loss: 0.1340, val loss: 0.1431, PR-AUC (anomaly): 0.9405, f2-score (anomaly): 0.9559
              precision    recall  f1-score   support

           0       1.00      0.94      0.97       157
           1       0.81      1.00      0.90        39

    accuracy                           0.95       196
   macro avg       0.91      0.97      0.93       196
weighted avg       0.96      0.95      0.96       196

Fold 2/5, epoch 5/100 — training...
  Fold 2, epoch 5, train loss: 0.0835, val loss: 0.1509, PR-AUC (anomaly): 0.9562, f2-score (anomaly): 0.9406
              precision    recall  f1-score   support

           0       0.99      0.95      0.97       157
           1       0.83      0.97      0.89        39

    accuracy                           0.95       196
   macro avg       0.91      0.96      0.93       196
weighted avg       0.96      0.95      0.96       196

Fold 2/5, epoch 6/100 — training...
  Fold 2, epoch 6, train loss: 0.0692, val loss: 0.1784, PR-AUC (anomaly): 0.9634, f2-score (anomaly): 0.9406
              precision    recall  f1-score   support

           0       0.99      0.95      0.97       157
           1       0.83      0.97      0.89        39

    accuracy                           0.95       196
   macro avg       0.91      0.96      0.93       196
weighted avg       0.96      0.95      0.96       196

Fold 2/5, epoch 7/100 — training...
  Fold 2, epoch 7, train loss: 0.0641, val loss: 0.1824, PR-AUC (anomaly): 0.9539, f2-score (anomaly): 0.9360
              precision    recall  f1-score   support

           0       0.99      0.94      0.97       157
           1       0.81      0.97      0.88        39

    accuracy                           0.95       196
   macro avg       0.90      0.96      0.93       196
weighted avg       0.96      0.95      0.95       196

Fold 2/5, epoch 8/100 — training...
  Fold 2, epoch 8, train loss: 0.0710, val loss: 0.1509, PR-AUC (anomaly): 0.9644, f2-score (anomaly): 0.9453
              precision    recall  f1-score   support

           0       0.99      0.96      0.97       157
           1       0.84      0.97      0.90        39

    accuracy                           0.96       196
   macro avg       0.92      0.96      0.94       196
weighted avg       0.96      0.96      0.96       196

Fold 2/5, epoch 9/100 — training...
  Fold 2, epoch 9, train loss: 0.0678, val loss: 0.1929, PR-AUC (anomaly): 0.9526, f2-score (anomaly): 0.9453
              precision    recall  f1-score   support

           0       0.99      0.96      0.97       157
           1       0.84      0.97      0.90        39

    accuracy                           0.96       196
   macro avg       0.92      0.96      0.94       196
weighted avg       0.96      0.96      0.96       196

Fold 2/5, epoch 10/100 — training...
  Fold 2, epoch 10, train loss: 0.0754, val loss: 0.1959, PR-AUC (anomaly): 0.9609, f2-score (anomaly): 0.9406
              precision    recall  f1-score   support

           0       0.99      0.95      0.97       157
           1       0.83      0.97      0.89        39

    accuracy                           0.95       196
   macro avg       0.91      0.96      0.93       196
weighted avg       0.96      0.95      0.96       196

Fold 2/5, epoch 11/100 — training...
  Fold 2, epoch 11, train loss: 0.0660, val loss: 0.2218, PR-AUC (anomaly): 0.9501, f2-score (anomaly): 0.9453
              precision    recall  f1-score   support

           0       0.99      0.96      0.97       157
           1       0.84      0.97      0.90        39

    accuracy                           0.96       196
   macro avg       0.92      0.96      0.94       196
weighted avg       0.96      0.96      0.96       196

Fold 2/5, epoch 12/100 — training...
  Fold 2, epoch 12, train loss: 0.0615, val loss: 0.1763, PR-AUC (anomaly): 0.9691, f2-score (anomaly): 0.9500
              precision    recall  f1-score   support

           0       0.99      0.96      0.98       157
           1       0.86      0.97      0.92        39

    accuracy                           0.96       196
   macro avg       0.93      0.97      0.95       196
weighted avg       0.97      0.96      0.97       196

Fold 2/5, epoch 13/100 — training...
  Fold 2, epoch 13, train loss: 0.0700, val loss: 0.2089, PR-AUC (anomaly): 0.9550, f2-score (anomaly): 0.9453
              precision    recall  f1-score   support

           0       0.99      0.96      0.97       157
           1       0.84      0.97      0.90        39

    accuracy                           0.96       196
   macro avg       0.92      0.96      0.94       196
weighted avg       0.96      0.96      0.96       196

Fold 2/5, epoch 14/100 — training...
  Fold 2, epoch 14, train loss: 0.0868, val loss: 0.1415, PR-AUC (anomaly): 0.9439, f2-score (anomaly): 0.9453
              precision    recall  f1-score   support

           0       0.99      0.96      0.97       157
           1       0.84      0.97      0.90        39

    accuracy                           0.96       196
   macro avg       0.92      0.96      0.94       196
weighted avg       0.96      0.96      0.96       196

Fold 2/5, epoch 15/100 — training...
  Fold 2, epoch 15, train loss: 0.0849, val loss: 0.1340, PR-AUC (anomaly): 0.9528, f2-score (anomaly): 0.9653
              precision    recall  f1-score   support

           0       1.00      0.96      0.98       157
           1       0.85      1.00      0.92        39

    accuracy                           0.96       196
   macro avg       0.92      0.98      0.95       196
weighted avg       0.97      0.96      0.97       196

Fold 2/5, epoch 16/100 — training...
  Fold 2, epoch 16, train loss: 0.0755, val loss: 0.1821, PR-AUC (anomaly): 0.9674, f2-score (anomaly): 0.9406
              precision    recall  f1-score   support

           0       0.99      0.95      0.97       157
           1       0.83      0.97      0.89        39

    accuracy                           0.95       196
   macro avg       0.91      0.96      0.93       196
weighted avg       0.96      0.95      0.96       196

Fold 2/5, epoch 17/100 — training...
  Fold 2, epoch 17, train loss: 0.0695, val loss: 0.1791, PR-AUC (anomaly): 0.9601, f2-score (anomaly): 0.9500
              precision    recall  f1-score   support

           0       0.99      0.96      0.98       157
           1       0.86      0.97      0.92        39

    accuracy                           0.96       196
   macro avg       0.93      0.97      0.95       196
weighted avg       0.97      0.96      0.97       196

Fold 2/5, epoch 18/100 — training...
  Fold 2, epoch 18, train loss: 0.0590, val loss: 0.2082, PR-AUC (anomaly): 0.9614, f2-score (anomaly): 0.9500
              precision    recall  f1-score   support

           0       0.99      0.96      0.98       157
           1       0.86      0.97      0.92        39

    accuracy                           0.96       196
   macro avg       0.93      0.97      0.95       196
weighted avg       0.97      0.96      0.97       196

Fold 2/5, epoch 19/100 — training...
  Fold 2, epoch 19, train loss: 0.0610, val loss: 0.1920, PR-AUC (anomaly): 0.9595, f2-score (anomaly): 0.9500
              precision    recall  f1-score   support

           0       0.99      0.96      0.98       157
           1       0.86      0.97      0.92        39

    accuracy                           0.96       196
   macro avg       0.93      0.97      0.95       196
weighted avg       0.97      0.96      0.97       196

Fold 2/5, epoch 20/100 — training...
  Fold 2, epoch 20, train loss: 0.0746, val loss: 0.1885, PR-AUC (anomaly): 0.9552, f2-score (anomaly): 0.9500
              precision    recall  f1-score   support

           0       0.99      0.96      0.98       157
           1       0.86      0.97      0.92        39


'/home/gonca/Documents/GitHub/IST-Thesis/BridgeDefender/outputs/mlpbased-single-eval-tuningpooling-ronin12-omni-nomad-polyn-qubit-harmony-thor123-meter-hypr-xbridge/train_epochs100_augment0_lr0.005_poolsum_nosf_es15_mlpbased_tuningpooling__202608102201'

In [7]:
# Run for mean+max pooling
pooling = "mean_max"
Cli.train_model(SimpleNamespace(
    **fixed_args,
    pooling=pooling
))

Early stopping: 15
Exporting data from database to CSV files...
Splitting dataset into train/val/test sets with test size 15% and 5 folds for cross-validation.
Normalizing node features using min-max normalization.
Label distribution in train/val pool: 782 normal, 197 anomaly.
Identified 264 differential meta-paths for training.
Fold 1/5, epoch 1/100 — training...
  Fold 1, epoch 1, train loss: 0.3814, val loss: 0.1200, PR-AUC (anomaly): 0.9272, f2-score (anomaly): 0.9653
              precision    recall  f1-score   support

           0       1.00      0.96      0.98       157
           1       0.85      1.00      0.92        39

    accuracy                           0.96       196
   macro avg       0.92      0.98      0.95       196
weighted avg       0.97      0.96      0.97       196

Fold 1/5, epoch 2/100 — training...
  Fold 1, epoch 2, train loss: 0.1627, val loss: 0.1019, PR-AUC (anomaly): 0.9261, f2-score (anomaly): 0.9653
              precision    recall  f1-score   support

           0       1.00      0.96      0.98       157
           1       0.85      1.00      0.92        39

    accuracy                           0.96       196
   macro avg       0.92      0.98      0.95       196
weighted avg       0.97      0.96      0.97       196

Fold 1/5, epoch 3/100 — training...
  Fold 1, epoch 3, train loss: 0.1197, val loss: 0.0776, PR-AUC (anomaly): 0.9516, f2-score (anomaly): 0.9653
              precision    recall  f1-score   support

           0       1.00      0.96      0.98       157
           1       0.85      1.00      0.92        39

    accuracy                           0.96       196
   macro avg       0.92      0.98      0.95       196
weighted avg       0.97      0.96      0.97       196

Fold 1/5, epoch 4/100 — training...
  Fold 1, epoch 4, train loss: 0.1489, val loss: 0.1100, PR-AUC (anomaly): 0.9218, f2-score (anomaly): 0.9559
              precision    recall  f1-score   support

           0       1.00      0.94      0.97       157
           1       0.81      1.00      0.90        39

    accuracy                           0.95       196
   macro avg       0.91      0.97      0.93       196
weighted avg       0.96      0.95      0.96       196

Fold 1/5, epoch 5/100 — training...
  Fold 1, epoch 5, train loss: 0.1211, val loss: 0.0872, PR-AUC (anomaly): 0.9440, f2-score (anomaly): 0.9559
              precision    recall  f1-score   support

           0       1.00      0.94      0.97       157
           1       0.81      1.00      0.90        39

    accuracy                           0.95       196
   macro avg       0.91      0.97      0.93       196
weighted avg       0.96      0.95      0.96       196

Fold 1/5, epoch 6/100 — training...
  Fold 1, epoch 6, train loss: 0.0990, val loss: 0.0670, PR-AUC (anomaly): 0.9542, f2-score (anomaly): 0.9653
              precision    recall  f1-score   support

           0       1.00      0.96      0.98       157
           1       0.85      1.00      0.92        39

    accuracy                           0.96       196
   macro avg       0.92      0.98      0.95       196
weighted avg       0.97      0.96      0.97       196

Fold 1/5, epoch 7/100 — training...
  Fold 1, epoch 7, train loss: 0.0926, val loss: 0.0769, PR-AUC (anomaly): 0.9476, f2-score (anomaly): 0.9799
              precision    recall  f1-score   support

           0       1.00      0.97      0.99       157
           1       0.91      1.00      0.95        39

    accuracy                           0.98       196
   macro avg       0.95      0.99      0.97       196
weighted avg       0.98      0.98      0.98       196

Fold 1/5, epoch 8/100 — training...
  Fold 1, epoch 8, train loss: 0.0830, val loss: 0.0510, PR-AUC (anomaly): 0.9655, f2-score (anomaly): 0.9799
              precision    recall  f1-score   support

           0       1.00      0.97      0.99       157
           1       0.91      1.00      0.95        39

    accuracy                           0.98       196
   macro avg       0.95      0.99      0.97       196
weighted avg       0.98      0.98      0.98       196

Fold 1/5, epoch 9/100 — training...
  Fold 1, epoch 9, train loss: 0.0841, val loss: 0.0584, PR-AUC (anomaly): 0.9695, f2-score (anomaly): 0.9653
              precision    recall  f1-score   support

           0       1.00      0.96      0.98       157
           1       0.85      1.00      0.92        39

    accuracy                           0.96       196
   macro avg       0.92      0.98      0.95       196
weighted avg       0.97      0.96      0.97       196

Fold 1/5, epoch 10/100 — training...
  Fold 1, epoch 10, train loss: 0.0889, val loss: 0.0453, PR-AUC (anomaly): 0.9718, f2-score (anomaly): 0.9799
              precision    recall  f1-score   support

           0       1.00      0.97      0.99       157
           1       0.91      1.00      0.95        39

    accuracy                           0.98       196
   macro avg       0.95      0.99      0.97       196
weighted avg       0.98      0.98      0.98       196

Fold 1/5, epoch 11/100 — training...
  Fold 1, epoch 11, train loss: 0.1027, val loss: 0.0649, PR-AUC (anomaly): 0.9547, f2-score (anomaly): 0.9750
              precision    recall  f1-score   support

           0       1.00      0.97      0.98       157
           1       0.89      1.00      0.94        39

    accuracy                           0.97       196
   macro avg       0.94      0.98      0.96       196
weighted avg       0.98      0.97      0.98       196

Fold 1/5, epoch 12/100 — training...
  Fold 1, epoch 12, train loss: 0.0880, val loss: 0.0543, PR-AUC (anomaly): 0.9619, f2-score (anomaly): 0.9750
              precision    recall  f1-score   support

           0       1.00      0.97      0.98       157
           1       0.89      1.00      0.94        39

    accuracy                           0.97       196
   macro avg       0.94      0.98      0.96       196
weighted avg       0.98      0.97      0.98       196

Fold 1/5, epoch 13/100 — training...
  Fold 1, epoch 13, train loss: 0.0784, val loss: 0.0477, PR-AUC (anomaly): 0.9699, f2-score (anomaly): 0.9799
              precision    recall  f1-score   support

           0       1.00      0.97      0.99       157
           1       0.91      1.00      0.95        39

    accuracy                           0.98       196
   macro avg       0.95      0.99      0.97       196
weighted avg       0.98      0.98      0.98       196

Fold 1/5, epoch 14/100 — training...
  Fold 1, epoch 14, train loss: 0.0811, val loss: 0.0460, PR-AUC (anomaly): 0.9650, f2-score (anomaly): 0.9799
              precision    recall  f1-score   support

           0       1.00      0.97      0.99       157
           1       0.91      1.00      0.95        39

    accuracy                           0.98       196
   macro avg       0.95      0.99      0.97       196
weighted avg       0.98      0.98      0.98       196

Fold 1/5, epoch 15/100 — training...
  Fold 1, epoch 15, train loss: 0.0982, val loss: 0.0482, PR-AUC (anomaly): 0.9865, f2-score (anomaly): 0.9799
              precision    recall  f1-score   support

           0       1.00      0.97      0.99       157
           1       0.91      1.00      0.95        39

    accuracy                           0.98       196
   macro avg       0.95      0.99      0.97       196
weighted avg       0.98      0.98      0.98       196

Fold 1/5, epoch 16/100 — training...
  Fold 1, epoch 16, train loss: 0.0707, val loss: 0.0719, PR-AUC (anomaly): 0.9457, f2-score (anomaly): 0.9653
              precision    recall  f1-score   support

           0       1.00      0.96      0.98       157
           1       0.85      1.00      0.92        39

    accuracy                           0.96       196
   macro avg       0.92      0.98      0.95       196
weighted avg       0.97      0.96      0.97       196

Fold 1/5, epoch 17/100 — training...
  Fold 1, epoch 17, train loss: 0.1082, val loss: 0.1086, PR-AUC (anomaly): 0.9628, f2-score (anomaly): 0.9242
              precision    recall  f1-score   support

           0       1.00      0.90      0.95       157
           1       0.71      1.00      0.83        39

    accuracy                           0.92       196
   macro avg       0.85      0.95      0.89       196
weighted avg       0.94      0.92      0.92       196

Fold 1/5, epoch 18/100 — training...
  Fold 1, epoch 18, train loss: 0.0886, val loss: 0.0658, PR-AUC (anomaly): 0.9608, f2-score (anomaly): 0.9750
              precision    recall  f1-score   support

           0       1.00      0.97      0.98       157
           1       0.89      1.00      0.94        39

    accuracy                           0.97       196
   macro avg       0.94      0.98      0.96       196
weighted avg       0.98      0.97      0.98       196

Fold 1/5, epoch 19/100 — training...
  Fold 1, epoch 19, train loss: 0.0910, val loss: 0.0533, PR-AUC (anomaly): 0.9581, f2-score (anomaly): 0.9799
              precision    recall  f1-score   support

           0       1.00      0.97      0.99       157
           1       0.91      1.00      0.95        39

    accuracy                           0.98       196
   macro avg       0.95      0.99      0.97       196
weighted avg       0.98      0.98      0.98       196

Fold 1/5, epoch 20/100 — training...
  Fold 1, epoch 20, train loss: 0.0894, val loss: 0.0561, PR-AUC (anomaly): 0.9608, f2-score (anomaly): 0.9799
              precision    recall  f1-score   support

           0       1.00      0.97      0.99       157
           1       0.91      1.00      0.95        39

    accuracy                           0.98       196
   macro avg       0.95      0.99      0.97       196
weighted avg       0.98      0.98      0.98       196

Fold 1/5, epoch 21/100 — training...
  Fold 1, epoch 21, train loss: 0.1123, val loss: 0.0551, PR-AUC (anomaly): 0.9655, f2-score (anomaly): 0.9799
              precision    recall  f1-score   support

           0       1.00      0.97      0.99       157
           1       0.91      1.00      0.95        39

    accuracy                           0.98       196
   macro avg       0.95      0.99      0.97       196
weighted avg       0.98      0.98      0.98       196

Fold 1/5, epoch 22/100 — training...
  Fold 1, epoch 22, train loss: 0.0743, val loss: 0.0617, PR-AUC (anomaly): 0.9661, f2-score (anomaly): 0.9799
              precision    recall  f1-score   support

           0       1.00      0.97      0.99       157
           1       0.91      1.00      0.95        39

    accuracy                           0.98       196
   macro avg       0.95      0.99      0.97       196
weighted avg       0.98      0.98      0.98       196

Early stopping triggered at epoch 22 for fold 1.
Saved fold 1 best model to /home/gonca/Documents/GitHub/IST-Thesis/BridgeDefender/outputs/mlpbased-single-eval-tuningpooling-ronin12-omni-nomad-polyn-qubit-harmony-thor123-meter-hypr-xbridge/train_epochs100_augment0_lr0.005_poolmean_max_nosf_es15_mlpbased_tuningpooling__202608102206/models/fold_1.pt
Fold 2/5, epoch 1/100 — training...
  Fold 2, epoch 1, train loss: 0.3959, val loss: 0.2337, PR-AUC (anomaly): 0.8275, f2-score (anomaly): 0.9112
              precision    recall  f1-score   support

           0       1.00      0.88      0.94       157
           1       0.67      1.00      0.80        39

    accuracy                           0.90       196
   macro avg       0.84      0.94      0.87       196
weighted avg       0.93      0.90      0.91       196

Fold 2/5, epoch 2/100 — training...
  Fold 2, epoch 2, train loss: 0.1507, val loss: 0.1504, PR-AUC (anomaly): 0.8802, f2-score (anomaly): 0.9466
              precision    recall  f1-score   support

           0       1.00      0.93      0.96       157
           1       0.78      1.00      0.88        39

    accuracy                           0.94       196
   macro avg       0.89      0.96      0.92       196
weighted avg       0.96      0.94      0.95       196

Fold 2/5, epoch 3/100 — training...
  Fold 2, epoch 3, train loss: 0.1123, val loss: 0.1871, PR-AUC (anomaly): 0.8736, f2-score (anomaly): 0.9420
              precision    recall  f1-score   support

           0       1.00      0.92      0.96       157
           1       0.76      1.00      0.87        39

    accuracy                           0.94       196
   macro avg       0.88      0.96      0.91       196
weighted avg       0.95      0.94      0.94       196

Fold 2/5, epoch 4/100 — training...
  Fold 2, epoch 4, train loss: 0.0840, val loss: 0.1681, PR-AUC (anomaly): 0.9440, f2-score (anomaly): 0.9360
              precision    recall  f1-score   support

           0       0.99      0.94      0.97       157
           1       0.81      0.97      0.88        39

    accuracy                           0.95       196
   macro avg       0.90      0.96      0.93       196
weighted avg       0.96      0.95      0.95       196

Fold 2/5, epoch 5/100 — training...
  Fold 2, epoch 5, train loss: 0.0822, val loss: 0.1517, PR-AUC (anomaly): 0.9381, f2-score (anomaly): 0.9406
              precision    recall  f1-score   support

           0       0.99      0.95      0.97       157
           1       0.83      0.97      0.89        39

    accuracy                           0.95       196
   macro avg       0.91      0.96      0.93       196
weighted avg       0.96      0.95      0.96       196

Fold 2/5, epoch 6/100 — training...
  Fold 2, epoch 6, train loss: 0.0825, val loss: 0.1398, PR-AUC (anomaly): 0.9491, f2-score (anomaly): 0.9406
              precision    recall  f1-score   support

           0       0.99      0.95      0.97       157
           1       0.83      0.97      0.89        39

    accuracy                           0.95       196
   macro avg       0.91      0.96      0.93       196
weighted avg       0.96      0.95      0.96       196

Fold 2/5, epoch 7/100 — training...
  Fold 2, epoch 7, train loss: 0.0904, val loss: 0.1732, PR-AUC (anomaly): 0.9403, f2-score (anomaly): 0.9406
              precision    recall  f1-score   support

           0       0.99      0.95      0.97       157
           1       0.83      0.97      0.89        39

    accuracy                           0.95       196
   macro avg       0.91      0.96      0.93       196
weighted avg       0.96      0.95      0.96       196

Fold 2/5, epoch 8/100 — training...
  Fold 2, epoch 8, train loss: 0.0839, val loss: 0.1530, PR-AUC (anomaly): 0.9556, f2-score (anomaly): 0.9500
              precision    recall  f1-score   support

           0       0.99      0.96      0.98       157
           1       0.86      0.97      0.92        39

    accuracy                           0.96       196
   macro avg       0.93      0.97      0.95       196
weighted avg       0.97      0.96      0.97       196

Fold 2/5, epoch 9/100 — training...
  Fold 2, epoch 9, train loss: 0.0657, val loss: 0.2108, PR-AUC (anomaly): 0.9624, f2-score (anomaly): 0.9453
              precision    recall  f1-score   support

           0       0.99      0.96      0.97       157
           1       0.84      0.97      0.90        39

    accuracy                           0.96       196
   macro avg       0.92      0.96      0.94       196
weighted avg       0.96      0.96      0.96       196

Fold 2/5, epoch 10/100 — training...
  Fold 2, epoch 10, train loss: 0.0640, val loss: 0.1811, PR-AUC (anomaly): 0.9580, f2-score (anomaly): 0.9453
              precision    recall  f1-score   support

           0       0.99      0.96      0.97       157
           1       0.84      0.97      0.90        39

    accuracy                           0.96       196
   macro avg       0.92      0.96      0.94       196
weighted avg       0.96      0.96      0.96       196

Fold 2/5, epoch 11/100 — training...
  Fold 2, epoch 11, train loss: 0.0652, val loss: 0.1682, PR-AUC (anomaly): 0.9630, f2-score (anomaly): 0.9453
              precision    recall  f1-score   support

           0       0.99      0.96      0.97       157
           1       0.84      0.97      0.90        39

    accuracy                           0.96       196
   macro avg       0.92      0.96      0.94       196
weighted avg       0.96      0.96      0.96       196

Fold 2/5, epoch 12/100 — training...
  Fold 2, epoch 12, train loss: 0.0681, val loss: 0.1724, PR-AUC (anomaly): 0.9559, f2-score (anomaly): 0.9453
              precision    recall  f1-score   support

           0       0.99      0.96      0.97       157
           1       0.84      0.97      0.90        39

    accuracy                           0.96       196
   macro avg       0.92      0.96      0.94       196
weighted avg       0.96      0.96      0.96       196

Fold 2/5, epoch 13/100 — training...
  Fold 2, epoch 13, train loss: 0.0647, val loss: 0.1981, PR-AUC (anomaly): 0.9535, f2-score (anomaly): 0.9453
              precision    recall  f1-score   support

           0       0.99      0.96      0.97       157
           1       0.84      0.97      0.90        39

    accuracy                           0.96       196
   macro avg       0.92      0.96      0.94       196
weighted avg       0.96      0.96      0.96       196

Fold 2/5, epoch 14/100 — training...
  Fold 2, epoch 14, train loss: 0.0703, val loss: 0.1780, PR-AUC (anomaly): 0.9518, f2-score (anomaly): 0.9453
              precision    recall  f1-score   support

           0       0.99      0.96      0.97       157
           1       0.84      0.97      0.90        39

    accuracy                           0.96       196
   macro avg       0.92      0.96      0.94       196
weighted avg       0.96      0.96      0.96       196

Fold 2/5, epoch 15/100 — training...
  Fold 2, epoch 15, train loss: 0.0725, val loss: 0.1834, PR-AUC (anomaly): 0.9569, f2-score (anomaly): 0.9453
              precision    recall  f1-score   support

           0       0.99      0.96      0.97       157
           1       0.84      0.97      0.90        39

    accuracy                           0.96       196
   macro avg       0.92      0.96      0.94       196
weighted avg       0.96      0.96      0.96       196

Fold 2/5, epoch 16/100 — training...
  Fold 2, epoch 16, train loss: 0.0624, val loss: 0.2330, PR-AUC (anomaly): 0.9571, f2-score (anomaly): 0.9453
              precision    recall  f1-score   support

           0       0.99      0.96      0.97       157
           1       0.84      0.97      0.90        39

    accuracy                           0.96       196
   macro avg       0.92      0.96      0.94       196
weighted avg       0.96      0.96      0.96       196

Fold 2/5, epoch 17/100 — training...
  Fold 2, epoch 17, train loss: 0.0903, val loss: 0.1569, PR-AUC (anomaly): 0.9259, f2-score (anomaly): 0.9360
              precision    recall  f1-score   support

           0       0.99      0.94      0.97       157
           1       0.81      0.97      0.88        39

    accuracy                           0.95       196
   macro avg       0.90      0.96      0.93       196
weighted avg       0.96      0.95      0.95       196

Fold 2/5, epoch 18/100 — training...
  Fold 2, epoch 18, train loss: 0.0877, val loss: 0.1833, PR-AUC (anomaly): 0.8724, f2-score (anomaly): 0.9512
              precision    recall  f1-score   support

           0       1.00      0.94      0.97       157
           1       0.80      1.00      0.89        39

    accuracy                           0.95       196
   macro avg       0.90      0.97      0.93       196
weighted avg       0.96      0.95      0.95       196

Fold 2/5, epoch 19/100 — training...
  Fold 2, epoch 19, train loss: 0.0946, val loss: 0.1554, PR-AUC (anomaly): 0.9522, f2-score (anomaly): 0.9406
              precision    recall  f1-score   support

           0       0.99      0.95      0.97       157
           1       0.83      0.97      0.89        39


'/home/gonca/Documents/GitHub/IST-Thesis/BridgeDefender/outputs/mlpbased-single-eval-tuningpooling-ronin12-omni-nomad-polyn-qubit-harmony-thor123-meter-hypr-xbridge/train_epochs100_augment0_lr0.005_poolmean_max_nosf_es15_mlpbased_tuningpooling__202608102206'

## Results processing

In [2]:
# Obtain all relevant run directories that match the pattern and contain a params.yaml file
run_dirs = sorted(
    p for p in OUTPUTS_ROOT.glob("train_epochs*")
    if p.is_dir() and (p / "params.yaml").exists()
)

print(f"Found {len(run_dirs)} run directories")
for p in run_dirs:
    print(p)

Found 4 run directories
/home/gonca/Documents/GitHub/IST-Thesis/BridgeDefender/outputs/mlpbased-single-eval-tuningpooling-ronin12-omni-nomad-polyn-qubit-harmony-thor123-meter-hypr-xbridge/train_epochs100_augment0_lr0.005_nosf_es15_mlpbased_tuningpooling__202608102150
/home/gonca/Documents/GitHub/IST-Thesis/BridgeDefender/outputs/mlpbased-single-eval-tuningpooling-ronin12-omni-nomad-polyn-qubit-harmony-thor123-meter-hypr-xbridge/train_epochs100_augment0_lr0.005_poolmax_nosf_es15_mlpbased_tuningpooling__202608102155
/home/gonca/Documents/GitHub/IST-Thesis/BridgeDefender/outputs/mlpbased-single-eval-tuningpooling-ronin12-omni-nomad-polyn-qubit-harmony-thor123-meter-hypr-xbridge/train_epochs100_augment0_lr0.005_poolmean_max_nosf_es15_mlpbased_tuningpooling__202608102206
/home/gonca/Documents/GitHub/IST-Thesis/BridgeDefender/outputs/mlpbased-single-eval-tuningpooling-ronin12-omni-nomad-polyn-qubit-harmony-thor123-meter-hypr-xbridge/train_epochs100_augment0_lr0.005_poolsum_nosf_es15_mlpbased_tuningpooling__202608102201

In [3]:
import yaml
import pandas as pd

def load_run_config(run_dir: Path) -> dict:
    TOTAL_METAPATHS = 6475  # Total number of metapaths in the dataset
    with open(run_dir / "params.yaml") as f:
        doc = yaml.safe_load(f)

    return {
        "run_dir": run_dir,
        "run_name": run_dir.name,
        "pooling": doc["params"]["pooling"],
    }

configs = [load_run_config(p) for p in run_dirs]
configs_df = pd.DataFrame(configs)
configs_df

,run_dir,run_name,pooling
0,/home/gonca/Documents/GitHub/IST-Thesis/Bridge...,train_epochs100_augment0_lr0.005_nosf_es15_mlp...,mean
1,/home/gonca/Documents/GitHub/IST-Thesis/Bridge...,train_epochs100_augment0_lr0.005_poolmax_nosf_...,max
2,/home/gonca/Documents/GitHub/IST-Thesis/Bridge...,train_epochs100_augment0_lr0.005_poolmean_max_...,mean_max
3,/home/gonca/Documents/GitHub/IST-Thesis/Bridge...,train_epochs100_augment0_lr0.005_poolsum_nosf_...,sum

In [4]:
def load_val_metrics(run_dir: Path) -> dict:
    df = pd.read_csv(run_dir / "val_best_metrics.csv")
    metric_cols = [c for c in df.columns if c != "fold"]

    result = {"run_dir": run_dir}
    for col in metric_cols:
        result[f"{col}_mean"] = df[col].mean()
        result[f"{col}_std"] = df[col].std(ddof=0)
    
    result["precision_macro_mean"] = ((df["precision_normal"] + df["precision_anomaly"]) / 2).mean()
    result["precision_macro_std"] = ((df["precision_normal"] + df["precision_anomaly"]) / 2).std(ddof=0)
    result["recall_macro_mean"] = ((df["recall_normal"] + df["recall_anomaly"]) / 2).mean()
    result["recall_macro_std"] = ((df["recall_normal"] + df["recall_anomaly"]) / 2).std(ddof=0)
    result["f1_macro_mean"] = ((df["f1_normal"] + df["f1_anomaly"]) / 2).mean()
    result["f1_macro_std"] = ((df["f1_normal"] + df["f1_anomaly"]) / 2).std(ddof=0)
    return result

metrics = [load_val_metrics(p) for p in run_dirs]
metrics_df = pd.DataFrame(metrics)
metrics_df

,run_dir,epoch_mean,epoch_std,val_loss_mean,val_loss_std,accuracy_mean,accuracy_std,precision_normal_mean,precision_normal_std,recall_normal_mean,...,pr_auc_mean,pr_auc_std,mcc_mean,mcc_std,precision_macro_mean,precision_macro_std,recall_macro_mean,recall_macro_std,f1_macro_mean,f1_macro_std
0,/home/gonca/Documents/GitHub/IST-Thesis/Bridge...,16.4,9.645724,0.072225,0.050195,0.971402,0.013911,1.0,0.0,0.964225,...,0.964799,0.054122,0.920079,0.034666,0.939152,0.024946,0.982113,0.008663,0.958068,0.019247
1,/home/gonca/Documents/GitHub/IST-Thesis/Bridge...,12.4,8.685620,0.075460,0.040799,0.973443,0.012661,1.0,0.0,0.966781,...,0.967131,0.037524,0.925198,0.032290,0.942858,0.023499,0.983390,0.007884,0.960880,0.017749
2,/home/gonca/Documents/GitHub/IST-Thesis/Bridge...,12.6,4.409082,0.081550,0.051463,0.974464,0.013305,1.0,0.0,0.968063,...,0.965674,0.046745,0.928000,0.034110,0.944972,0.024890,0.984032,0.008286,0.962355,0.018702
3,/home/gonca/Documents/GitHub/IST-Thesis/Bridge...,14.0,7.615773,0.065610,0.035730,0.978550,0.007496,1.0,0.0,0.973167,...,0.981791,0.017048,0.938111,0.020205,0.952224,0.015081,0.986583,0.004658,0.967969,0.010869

In [5]:
def load_fold_durations(run_dir: Path) -> dict:
    df = pd.read_csv(run_dir / "fold_durations.csv")
    return {
        "run_dir": run_dir,
        "fold_time_mean": df["time"].mean(),
        "fold_time_std": df["time"].std(ddof=0),  # match summary.txt convention
        "fold_time_total": df["time"].sum(),
    }

durations = [load_fold_durations(p) for p in run_dirs]
durations_df = pd.DataFrame(durations)
durations_df

,run_dir,fold_time_mean,fold_time_std,fold_time_total
0,/home/gonca/Documents/GitHub/IST-Thesis/Bridge...,62.450,14.052665,312.25
1,/home/gonca/Documents/GitHub/IST-Thesis/Bridge...,61.042,18.895700,305.21
2,/home/gonca/Documents/GitHub/IST-Thesis/Bridge...,63.676,11.460978,318.38
3,/home/gonca/Documents/GitHub/IST-Thesis/Bridge...,58.066,12.190527,290.33

In [6]:
comparison_df = (
    configs_df
    .merge(metrics_df, on="run_dir")
    .merge(durations_df, on="run_dir")
)
comparison_df["pooling"] = pd.Categorical(comparison_df["pooling"], categories=["mean", "max", "sum", "mean_max"])
comparison_df = (
    comparison_df
    .sort_values(["pooling"])
    .reset_index(drop=True)
)
comparison_df

,run_dir,run_name,pooling,epoch_mean,epoch_std,val_loss_mean,val_loss_std,accuracy_mean,accuracy_std,precision_normal_mean,...,mcc_std,precision_macro_mean,precision_macro_std,recall_macro_mean,recall_macro_std,f1_macro_mean,f1_macro_std,fold_time_mean,fold_time_std,fold_time_total
0,/home/gonca/Documents/GitHub/IST-Thesis/Bridge...,train_epochs100_augment0_lr0.005_nosf_es15_mlp...,mean,16.4,9.645724,0.072225,0.050195,0.971402,0.013911,1.0,...,0.034666,0.939152,0.024946,0.982113,0.008663,0.958068,0.019247,62.450,14.052665,312.25
1,/home/gonca/Documents/GitHub/IST-Thesis/Bridge...,train_epochs100_augment0_lr0.005_poolmax_nosf_...,max,12.4,8.685620,0.075460,0.040799,0.973443,0.012661,1.0,...,0.032290,0.942858,0.023499,0.983390,0.007884,0.960880,0.017749,61.042,18.895700,305.21
2,/home/gonca/Documents/GitHub/IST-Thesis/Bridge...,train_epochs100_augment0_lr0.005_poolsum_nosf_...,sum,14.0,7.615773,0.065610,0.035730,0.978550,0.007496,1.0,...,0.020205,0.952224,0.015081,0.986583,0.004658,0.967969,0.010869,58.066,12.190527,290.33
3,/home/gonca/Documents/GitHub/IST-Thesis/Bridge...,train_epochs100_augment0_lr0.005_poolmean_max_...,mean_max,12.6,4.409082,0.081550,0.051463,0.974464,0.013305,1.0,...,0.034110,0.944972,0.024890,0.984032,0.008286,0.962355,0.018702,63.676,11.460978,318.38

In [7]:
trimmed_df = comparison_df[[
    "pooling",
    "accuracy_mean",
    "accuracy_std",
    "precision_macro_mean",
    "precision_macro_std",
    "recall_macro_mean",
    "recall_macro_std",
    "f1_macro_mean",
    "f1_macro_std",
]]
trimmed_df

,pooling,accuracy_mean,accuracy_std,precision_macro_mean,precision_macro_std,recall_macro_mean,recall_macro_std,f1_macro_mean,f1_macro_std
0,mean,0.971402,0.013911,0.939152,0.024946,0.982113,0.008663,0.958068,0.019247
1,max,0.973443,0.012661,0.942858,0.023499,0.983390,0.007884,0.960880,0.017749
2,sum,0.978550,0.007496,0.952224,0.015081,0.986583,0.004658,0.967969,0.010869
3,mean_max,0.974464,0.013305,0.944972,0.024890,0.984032,0.008286,0.962355,0.018702

In [8]:
PCT_SCALE_EXCLUDE = {"fold_time"}  # keep seconds as seconds, not *100

def format_stat(mean, std, base):
    scale = 1 if base in PCT_SCALE_EXCLUDE else 100
    return f"{mean * scale:.2f} \u00b1 {std * scale:05.2f}"

metric_bases = [c[:-5] for c in trimmed_df.columns if c.endswith("_mean")]

display_df2 = pd.DataFrame(index=trimmed_df.index)
for base in metric_bases:
    display_df2[base] = trimmed_df.apply(
        lambda row: format_stat(row[f"{base}_mean"], row[f"{base}_std"], base), axis=1
    )

display_df2.insert(0, "pooling", trimmed_df["pooling"])
display_df2 = display_df2.set_index("pooling")

final_table = display_df2
final_table

               accuracy precision_macro   recall_macro       f1_macro
pooling
mean      97.14 ± 01.39   93.92 ± 02.49  98.21 ± 00.87  95.81 ± 01.92
max       97.34 ± 01.27   94.29 ± 02.35  98.34 ± 00.79  96.09 ± 01.77
sum       97.86 ± 00.75   95.22 ± 01.51  98.66 ± 00.47  96.80 ± 01.09
mean_max  97.45 ± 01.33   94.50 ± 02.49  98.40 ± 00.83  96.24 ± 01.87

In [9]:
# Turn the unicode ± into LaTeX math syntax, and escape underscores in row labels
import re

METRIC_LABELS = {
    "pooling": "Pooling Type",
    "accuracy": "Accuracy (\\%)",
    "precision_macro": "Precision (\\%)",
    "recall_macro": "Recall (\\%)",
    "f1_macro": "F1-Score (\\%)",
}

POOLING_LABELS = {
    "mean": "Mean Pooling",
    "max": "Max Pooling",
    "sum": "Sum Pooling",
    "mean_max": "Mean + Max Pooling",
}

def to_math_pm(s: str) -> str:
    return re.sub(r"(-?[\d.]+) ± (-?[\d.]+)", r"\1 $\\pm$ \2", s)

latex_ready = final_table.map(to_math_pm)
latex_ready = latex_ready.reset_index()  # turn the "pooling" index back into a plain column
latex_ready = latex_ready.rename(columns=METRIC_LABELS)
latex_ready["Pooling Type"] = latex_ready["Pooling Type"].map(POOLING_LABELS)

latex_str = latex_ready.to_latex(
    index=False,  # drop the numeric row index; "Pooling Type" is now a real column
    escape=False,  # cell values already contain LaTeX ($\pm$), don't double-escape
    column_format="l" + "r" * (len(latex_ready.columns) - 1),
    caption="Effect of the DME threshold on test-set performance",
    label="tab:ablation_semantic_fusion",
)
print(latex_str)

\begin{table}
\caption{Effect of the DME threshold on test-set performance}
\label{tab:ablation_semantic_fusion}
\begin{tabular}{lrrrr}
\toprule
Pooling Type & Accuracy (\%) & Precision (\%) & Recall (\%) & F1-Score (\%) \\
\midrule
Mean Pooling & 97.14 $\pm$ 01.39 & 93.92 $\pm$ 02.49 & 98.21 $\pm$ 00.87 & 95.81 $\pm$ 01.92 \\
Max Pooling & 97.34 $\pm$ 01.27 & 94.29 $\pm$ 02.35 & 98.34 $\pm$ 00.79 & 96.09 $\pm$ 01.77 \\
Sum Pooling & 97.86 $\pm$ 00.75 & 95.22 $\pm$ 01.51 & 98.66 $\pm$ 00.47 & 96.80 $\pm$ 01.09 \\
Mean + Max Pooling & 97.45 $\pm$ 01.33 & 94.50 $\pm$ 02.49 & 98.40 $\pm$ 00.83 & 96.24 $\pm$ 01.87 \\
\bottomrule
\end{tabular}
\end{table}

# Cross-chain context

In [10]:
import sys
from pathlib import Path

sys.path.insert(0, str(Path.cwd().parent))

from types import SimpleNamespace

from cli import Cli
from dataset_generator.types import DATASET_TYPE

# Define the absolute path for the root directory for outputs here (and if possible, make sure to have a prepared _dataset folder)
OUTPUTS_ROOT = Path("/home/gonca/Documents/GitHub/IST-Thesis/BridgeDefender/outputs/mlpbased-cctx-eval-tuningpooling-ronin12-omni-nomad-polyn-qubit-harmony-thor123-meter-hypr-xbridge")

## Test runs

The next cells will run the model training for different pooling layer strategies.

This process can take a long time to finish.

**If you already have the models trained, you can skip this section and go to the evaluation section.**

In [17]:
dataset_path = OUTPUTS_ROOT.absolute() / "_dataset"
fixed_args = {
    "device": "cpu",  # Change to "cuda" if you have a GPU and want to use it
    "dataset": DATASET_TYPE.CCTX,
    "load_data": str(dataset_path),
    "new_dataset": None,
    "force_reload": False,
    "num_workers": 0,
    "tags": "mlpbased,tuningpooling",

    "num_epochs": 100,
    "learning_rate": 0.005, # Notice that this is the same learning rate as the single-chain scope, unlike in the newer approach
    "augment_factor": 0,
    "dme_threshold": 0.5,
    "rm_semantic_fusion": True,
    "early_stopping": 15,
    "kfolds": 5,
    "first_layer_channels": 128,
    "hidden_channels": 64,
    "dropout": 0.5,
    "input_drop": 0.0,
    "att_drop": 0.0,
    "n_fp_layers": 2,
    "n_mlp_layers": 2,
    "activation": "relu",
    "residual": False,
    "random_seed": 42,
    "test_split": 0.15,
}

In [18]:
# Run for mean pooling
pooling = "mean"
Cli.train_model(SimpleNamespace(
    **fixed_args,
    pooling=pooling
))

Early stopping: 15
Exporting data from database to CSV files...

Processing graphs dataset: 100%|██████████| 1241/1241 [00:21<00:00, 56.79graph/s]

Splitting dataset into train/val/test sets with test size 15% and 5 folds for cross-validation.
Normalizing node features using min-max normalization.
Label distribution in train/val pool: 983 normal, 71 anomaly.
Identified 499 differential meta-paths for training.
Fold 1/5, epoch 1/100 — training...
  Fold 1, epoch 1, train loss: 0.7778, val loss: 0.5884, PR-AUC (anomaly): 0.2128, f2-score (anomaly): 0.0000
              precision    recall  f1-score   support

           0       0.93      1.00      0.97       197
           1       0.00      0.00      0.00        14

    accuracy                           0.93       211
   macro avg       0.47      0.50      0.48       211
weighted avg       0.87      0.93      0.90       211

Fold 1/5, epoch 2/100 — training...
  Fold 1, epoch 2, train loss: 0.6352, val loss: 0.5213, PR-AUC (anomaly): 0.3038, f2-score (anomaly): 0.5435
              precision    recall  f1-score   support

           0       0.98      0.87      0.92       197
           1       0.28      0.71      0.40        14

    accuracy                           0.86       211
   macro avg       0.63      0.79      0.66       211
weighted avg       0.93      0.86      0.88       211

Fold 1/5, epoch 3/100 — training...
  Fold 1, epoch 3, train loss: 0.4308, val loss: 0.3679, PR-AUC (anomaly): 0.8195, f2-score (anomaly): 0.6579
              precision    recall  f1-score   support

           0       0.98      0.95      0.96       197
           1       0.50      0.71      0.59        14

    accuracy                           0.93       211
   macro avg       0.74      0.83      0.78       211
weighted avg       0.95      0.93      0.94       211

Fold 1/5, epoch 4/100 — training...
  Fold 1, epoch 4, train loss: 0.2160, val loss: 0.1685, PR-AUC (anomaly): 0.8957, f2-score (anomaly): 0.7386
              precision    recall  f1-score   support

           0       0.99      0.90      0.95       197
           1       0.41      0.93      0.57        14

    accuracy                           0.91       211
   macro avg       0.70      0.92      0.76       211
weighted avg       0.96      0.91      0.92       211

Fold 1/5, epoch 5/100 — training...
  Fold 1, epoch 5, train loss: 0.1658, val loss: 0.1657, PR-AUC (anomaly): 0.9283, f2-score (anomaly): 0.8667
              precision    recall  f1-score   support

           0       0.99      0.97      0.98       197
           1       0.68      0.93      0.79        14

    accuracy                           0.97       211
   macro avg       0.84      0.95      0.88       211
weighted avg       0.97      0.97      0.97       211

Fold 1/5, epoch 6/100 — training...
  Fold 1, epoch 6, train loss: 0.0948, val loss: 0.1626, PR-AUC (anomaly): 0.8910, f2-score (anomaly): 0.8784
              precision    recall  f1-score   support

           0       0.99      0.97      0.98       197
           1       0.72      0.93      0.81        14

    accuracy                           0.97       211
   macro avg       0.86      0.95      0.90       211
weighted avg       0.98      0.97      0.97       211

Fold 1/5, epoch 7/100 — training...
  Fold 1, epoch 7, train loss: 0.0403, val loss: 0.1947, PR-AUC (anomaly): 0.8598, f2-score (anomaly): 0.9028
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       197
           1       0.81      0.93      0.87        14

    accuracy                           0.98       211
   macro avg       0.90      0.96      0.93       211
weighted avg       0.98      0.98      0.98       211

Fold 1/5, epoch 8/100 — training...
  Fold 1, epoch 8, train loss: 0.0523, val loss: 0.2080, PR-AUC (anomaly): 0.8513, f2-score (anomaly): 0.9028
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       197
           1       0.81      0.93      0.87        14

    accuracy                           0.98       211
   macro avg       0.90      0.96      0.93       211
weighted avg       0.98      0.98      0.98       211

Fold 1/5, epoch 9/100 — training...
  Fold 1, epoch 9, train loss: 0.0392, val loss: 0.2020, PR-AUC (anomaly): 0.8261, f2-score (anomaly): 0.9028
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       197
           1       0.81      0.93      0.87        14

    accuracy                           0.98       211
   macro avg       0.90      0.96      0.93       211
weighted avg       0.98      0.98      0.98       211

Fold 1/5, epoch 10/100 — training...
  Fold 1, epoch 10, train loss: 0.0330, val loss: 0.2116, PR-AUC (anomaly): 0.9260, f2-score (anomaly): 0.9028
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       197
           1       0.81      0.93      0.87        14

    accuracy                           0.98       211
   macro avg       0.90      0.96      0.93       211
weighted avg       0.98      0.98      0.98       211

Fold 1/5, epoch 11/100 — training...
  Fold 1, epoch 11, train loss: 0.0393, val loss: 0.1899, PR-AUC (anomaly): 0.8933, f2-score (anomaly): 0.9028
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       197
           1       0.81      0.93      0.87        14

    accuracy                           0.98       211
   macro avg       0.90      0.96      0.93       211
weighted avg       0.98      0.98      0.98       211

Fold 1/5, epoch 12/100 — training...
  Fold 1, epoch 12, train loss: 0.0243, val loss: 0.2033, PR-AUC (anomaly): 0.8860, f2-score (anomaly): 0.9028
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       197
           1       0.81      0.93      0.87        14

    accuracy                           0.98       211
   macro avg       0.90      0.96      0.93       211
weighted avg       0.98      0.98      0.98       211

Fold 1/5, epoch 13/100 — training...
  Fold 1, epoch 13, train loss: 0.0164, val loss: 0.2092, PR-AUC (anomaly): 0.8843, f2-score (anomaly): 0.9028
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       197
           1       0.81      0.93      0.87        14

    accuracy                           0.98       211
   macro avg       0.90      0.96      0.93       211
weighted avg       0.98      0.98      0.98       211

Fold 1/5, epoch 14/100 — training...
  Fold 1, epoch 14, train loss: 0.0173, val loss: 0.2102, PR-AUC (anomaly): 0.9004, f2-score (anomaly): 0.9028
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       197
           1       0.81      0.93      0.87        14

    accuracy                           0.98       211
   macro avg       0.90      0.96      0.93       211
weighted avg       0.98      0.98      0.98       211

Fold 1/5, epoch 15/100 — training...
  Fold 1, epoch 15, train loss: 0.0491, val loss: 0.3113, PR-AUC (anomaly): 0.8024, f2-score (anomaly): 0.8451
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       197
           1       0.80      0.86      0.83        14

    accuracy                           0.98       211
   macro avg       0.89      0.92      0.91       211
weighted avg       0.98      0.98      0.98       211

Fold 1/5, epoch 16/100 — training...
  Fold 1, epoch 16, train loss: 0.0425, val loss: 0.2431, PR-AUC (anomaly): 0.8775, f2-score (anomaly): 0.9028
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       197
           1       0.81      0.93      0.87        14

    accuracy                           0.98       211
   macro avg       0.90      0.96      0.93       211
weighted avg       0.98      0.98      0.98       211

Fold 1/5, epoch 17/100 — training...
  Fold 1, epoch 17, train loss: 0.0226, val loss: 0.2315, PR-AUC (anomaly): 0.8516, f2-score (anomaly): 0.9028
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       197
           1       0.81      0.93      0.87        14

    accuracy                           0.98       211
   macro avg       0.90      0.96      0.93       211
weighted avg       0.98      0.98      0.98       211

Fold 1/5, epoch 18/100 — training...
  Fold 1, epoch 18, train loss: 0.0204, val loss: 0.2264, PR-AUC (anomaly): 0.8125, f2-score (anomaly): 0.9028
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       197
           1       0.81      0.93      0.87        14

    accuracy                           0.98       211
   macro avg       0.90      0.96      0.93       211
weighted avg       0.98      0.98      0.98       211

Fold 1/5, epoch 19/100 — training...
  Fold 1, epoch 19, train loss: 0.0322, val loss: 0.2380, PR-AUC (anomaly): 0.8741, f2-score (anomaly): 0.9028
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       197
           1       0.81      0.93      0.87        14

    accuracy                           0.98       211
   macro avg       0.90      0.96      0.93       211
weighted avg       0.98      0.98      0.98       211

Fold 1/5, epoch 20/100 — training...
  Fold 1, epoch 20, train loss: 0.0203, val loss: 0.2403, PR-AUC (anomaly): 0.8533, f2-score (anomaly): 0.9028
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       197
           1       0.81      0.93      0.87        14

    accuracy                           0.98       211
   macro avg       0.90      0.96      0.93       211
weighted avg       0.98      0.98      0.98       211

Fold 1/5, epoch 21/100 — training...
  Fold 1, epoch 21, train loss: 0.0225, val loss: 0.2415, PR-AUC (anomaly): 0.8530, f2-score (anomaly): 0.9028
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       197
           1       0.81      0.93      0.87        14

    accuracy                           0.98       211
   macro avg       0.90      0.96      0.93       211
weighted avg       0.98      0.98      0.98       211

Fold 1/5, epoch 22/100 — training...
  Fold 1, epoch 22, train loss: 0.0132, val loss: 0.2405, PR-AUC (anomaly): 0.8672, f2-score (anomaly): 0.9028
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       197
           1       0.81      0.93      0.87        14

    accuracy                           0.98       211
   macro avg       0.90      0.96      0.93       211
weighted avg       0.98      0.98      0.98       211

Early stopping triggered at epoch 22 for fold 1.
Saved fold 1 best model to /home/gonca/Documents/GitHub/IST-Thesis/BridgeDefender/outputs/mlpbased-cctx-eval-tuningpooling-ronin12-omni-nomad-polyn-qubit-harmony-thor123-meter-hypr-xbridge/train_epochs100_augment0_lr0.005_nosf_es15_mlpbased_tuningpooling__202608102212/models/fold_1.pt
Fold 2/5, epoch 1/100 — training...
  Fold 2, epoch 1, train loss: 0.6640, val loss: 0.6077, PR-AUC (anomaly): 0.3318, f2-score (anomaly): 0.2290
              precision    recall  f1-score   support

           0       0.94      0.65      0.77       197
           1       0.08      0.43      0.13        14

    accuracy                           0.64       211
   macro avg       0.51      0.54      0.45       211
weighted avg       0.88      0.64      0.73       211

Fold 2/5, epoch 2/100 — training...
  Fold 2, epoch 2, train loss: 0.4625, val loss: 0.3114, PR-AUC (anomaly): 0.5257, f2-score (anomaly): 0.5882
              precision    recall  f1-score   support

           0       0.98      0.90      0.94       197
           1       0.34      0.71      0.47        14

    accuracy                           0.89       211
   macro avg       0.66      0.81      0.70       211
weighted avg       0.94      0.89      0.91       211

Fold 2/5, epoch 3/100 — training...
  Fold 2, epoch 3, train loss: 0.3259, val loss: 0.1892, PR-AUC (anomaly): 0.6328, f2-score (anomaly): 0.8667
              precision    recall  f1-score   support

           0       0.99      0.97      0.98       197
           1       0.68      0.93      0.79        14

    accuracy                           0.97       211
   macro avg       0.84      0.95      0.88       211
weighted avg       0.97      0.97      0.97       211

Fold 2/5, epoch 4/100 — training...
  Fold 2, epoch 4, train loss: 0.2217, val loss: 0.1112, PR-AUC (anomaly): 0.6994, f2-score (anomaly): 0.8667
              precision    recall  f1-score   support

           0       0.99      0.97      0.98       197
           1       0.68      0.93      0.79        14

    accuracy                           0.97       211
   macro avg       0.84      0.95      0.88       211
weighted avg       0.97      0.97      0.97       211

Fold 2/5, epoch 5/100 — training...
  Fold 2, epoch 5, train loss: 0.1650, val loss: 0.2150, PR-AUC (anomaly): 0.8498, f2-score (anomaly): 0.7857
              precision    recall  f1-score   support

           0       0.98      0.98      0.98       197
           1       0.79      0.79      0.79        14

    accuracy                           0.97       211
   macro avg       0.89      0.89      0.89       211
weighted avg       0.97      0.97      0.97       211

Fold 2/5, epoch 6/100 — training...
  Fold 2, epoch 6, train loss: 0.1684, val loss: 0.1090, PR-AUC (anomaly): 0.7203, f2-score (anomaly): 0.8784
              precision    recall  f1-score   support

           0       0.99      0.97      0.98       197
           1       0.72      0.93      0.81        14

    accuracy                           0.97       211
   macro avg       0.86      0.95      0.90       211
weighted avg       0.98      0.97      0.97       211

Fold 2/5, epoch 7/100 — training...
  Fold 2, epoch 7, train loss: 0.1403, val loss: 0.0770, PR-AUC (anomaly): 0.9339, f2-score (anomaly): 0.8784
              precision    recall  f1-score   support

           0       0.99      0.97      0.98       197
           1       0.72      0.93      0.81        14

    accuracy                           0.97       211
   macro avg       0.86      0.95      0.90       211
weighted avg       0.98      0.97      0.97       211

Fold 2/5, epoch 8/100 — training...
  Fold 2, epoch 8, train loss: 0.0770, val loss: 0.0648, PR-AUC (anomaly): 0.9471, f2-score (anomaly): 0.9333
              precision    recall  f1-score   support

           0       1.00      0.97      0.99       197
           1       0.74      1.00      0.85        14

    accuracy                           0.98       211
   macro avg       0.87      0.99      0.92       211
weighted avg       0.98      0.98      0.98       211

Fold 2/5, epoch 9/100 — training...
  Fold 2, epoch 9, train loss: 0.0967, val loss: 0.0413, PR-AUC (anomaly): 0.9815, f2-score (anomaly): 0.9722
              precision    recall  f1-score   support

           0       1.00      0.99      0.99       197
           1       0.88      1.00      0.93        14

    accuracy                           0.99       211
   macro avg       0.94      0.99      0.96       211
weighted avg       0.99      0.99      0.99       211

Fold 2/5, epoch 10/100 — training...
  Fold 2, epoch 10, train loss: 0.0663, val loss: 0.0429, PR-AUC (anomaly): 0.9815, f2-score (anomaly): 0.9459
              precision    recall  f1-score   support

           0       1.00      0.98      0.99       197
           1       0.78      1.00      0.88        14

    accuracy                           0.98       211
   macro avg       0.89      0.99      0.93       211
weighted avg       0.99      0.98      0.98       211

Fold 2/5, epoch 11/100 — training...
  Fold 2, epoch 11, train loss: 0.0645, val loss: 0.0497, PR-AUC (anomaly): 0.9815, f2-score (anomaly): 0.9589
              precision    recall  f1-score   support

           0       1.00      0.98      0.99       197
           1       0.82      1.00      0.90        14

    accuracy                           0.99       211
   macro avg       0.91      0.99      0.95       211
weighted avg       0.99      0.99      0.99       211

Fold 2/5, epoch 12/100 — training...
  Fold 2, epoch 12, train loss: 0.0763, val loss: 0.1659, PR-AUC (anomaly): 0.8672, f2-score (anomaly): 0.8750
              precision    recall  f1-score   support

           0       1.00      0.95      0.97       197
           1       0.58      1.00      0.74        14

    accuracy                           0.95       211
   macro avg       0.79      0.97      0.86       211
weighted avg       0.97      0.95      0.96       211

Fold 2/5, epoch 13/100 — training...
  Fold 2, epoch 13, train loss: 0.1598, val loss: 0.0784, PR-AUC (anomaly): 0.9512, f2-score (anomaly): 0.9211
              precision    recall  f1-score   support

           0       1.00      0.97      0.98       197
           1       0.70      1.00      0.82        14

    accuracy                           0.97       211
   macro avg       0.85      0.98      0.90       211
weighted avg       0.98      0.97      0.97       211

Fold 2/5, epoch 14/100 — training...
  Fold 2, epoch 14, train loss: 0.1000, val loss: 0.0716, PR-AUC (anomaly): 0.9761, f2-score (anomaly): 0.9091
              precision    recall  f1-score   support

           0       1.00      0.96      0.98       197
           1       0.67      1.00      0.80        14

    accuracy                           0.97       211
   macro avg       0.83      0.98      0.89       211
weighted avg       0.98      0.97      0.97       211

Fold 2/5, epoch 15/100 — training...
  Fold 2, epoch 15, train loss: 0.0623, val loss: 0.0453, PR-AUC (anomaly): 0.9815, f2-score (anomaly): 0.9459
              precision    recall  f1-score   support

           0       1.00      0.98      0.99       197
           1       0.78      1.00      0.88        14

    accuracy                           0.98       211
   macro avg       0.89      0.99      0.93       211
weighted avg       0.99      0.98      0.98       211

Fold 2/5, epoch 16/100 — training...
  Fold 2, epoch 16, train loss: 0.0721, val loss: 0.0548, PR-AUC (anomaly): 0.9713, f2-score (anomaly): 0.9333
              precision    recall  f1-score   support

           0       1.00      0.97      0.99       197
           1       0.74      1.00      0.85        14

    accuracy                           0.98       211
   macro avg       0.87      0.99      0.92       211
weighted avg       0.98      0.98      0.98       211

Fold 2/5, epoch 17/100 — training...
  Fold 2, epoch 17, train loss: 0.0544, val loss: 0.0757, PR-AUC (anomaly): 0.9860, f2-score (anomaly): 0.8974
              precision    recall  f1-score   support

           0       1.00      0.96      0.98       197
           1       0.64      1.00      0.78        14

    accuracy                           0.96       211
   macro avg       0.82      0.98      0.88       211
weighted avg       0.98      0.96      0.97       211

Fold 2/5, epoch 18/100 — training...
  Fold 2, epoch 18, train loss: 0.0528, val loss: 0.0392, PR-AUC (anomaly): 0.9815, f2-score (anomaly): 0.9459
              precision    recall  f1-score   support

           0       1.00      0.98      0.99       197
           1       0.78      1.00      0.88        14

    accuracy                           0.98       211
   macro avg       0.89      0.99      0.93       211
weighted avg       0.99      0.98      0.98       211

Fold 2/5, epoch 19/100 — training...
  Fold 2, epoch 19, train loss: 0.1378, val loss: 0.0685, PR-AUC (anomaly): 0.9490, f2-score (anomaly): 0.9333
              precision    recall  f1-score   support

           0       1.00      0.97      0.99       197
           1       0.74      1.00      0.85        14

    accuracy                           0.98       211
   macro avg       0.87      0.99      0.92       211

'/home/gonca/Documents/GitHub/IST-Thesis/BridgeDefender/outputs/mlpbased-cctx-eval-tuningpooling-ronin12-omni-nomad-polyn-qubit-harmony-thor123-meter-hypr-xbridge/train_epochs100_augment0_lr0.005_nosf_es15_mlpbased_tuningpooling__202608102212'

In [19]:
# Run for max pooling
pooling = "max"
Cli.train_model(SimpleNamespace(
    **fixed_args,
    pooling=pooling
))

Early stopping: 15
Splitting dataset into train/val/test sets with test size 15% and 5 folds for cross-validation.
Normalizing node features using min-max normalization.
Label distribution in train/val pool: 983 normal, 71 anomaly.
Identified 499 differential meta-paths for training.
Fold 1/5, epoch 1/100 — training...
  Fold 1, epoch 1, train loss: 0.7377, val loss: 0.5691, PR-AUC (anomaly): 0.5389, f2-score (anomaly): 0.0000
              precision    recall  f1-score   support

           0       0.93      1.00      0.97       197
           1       0.00      0.00      0.00        14

    accuracy                           0.93       211
   macro avg       0.47      0.50      0.48       211
weighted avg       0.87      0.93      0.90       211

Fold 1/5, epoch 2/100 — training...
  Fold 1, epoch 2, train loss: 0.6169, val loss: 0.5284, PR-AUC (anomaly): 0.5195, f2-score (anomaly): 0.7065
              precision    recall  f1-score   support

           0       0.99      0.88      0.94       197
           1       0.36      0.93      0.52        14

    accuracy                           0.89       211
   macro avg       0.68      0.91      0.73       211
weighted avg       0.95      0.89      0.91       211

Fold 1/5, epoch 3/100 — training...
  Fold 1, epoch 3, train loss: 0.3366, val loss: 0.1854, PR-AUC (anomaly): 0.6823, f2-score (anomaly): 0.8667
              precision    recall  f1-score   support

           0       0.99      0.97      0.98       197
           1       0.68      0.93      0.79        14

    accuracy                           0.97       211
   macro avg       0.84      0.95      0.88       211
weighted avg       0.97      0.97      0.97       211

Fold 1/5, epoch 4/100 — training...
  Fold 1, epoch 4, train loss: 0.1392, val loss: 0.1450, PR-AUC (anomaly): 0.8945, f2-score (anomaly): 0.8904
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       197
           1       0.76      0.93      0.84        14

    accuracy                           0.98       211
   macro avg       0.88      0.95      0.91       211
weighted avg       0.98      0.98      0.98       211

Fold 1/5, epoch 5/100 — training...
  Fold 1, epoch 5, train loss: 0.0720, val loss: 0.1458, PR-AUC (anomaly): 0.9068, f2-score (anomaly): 0.9028
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       197
           1       0.81      0.93      0.87        14

    accuracy                           0.98       211
   macro avg       0.90      0.96      0.93       211
weighted avg       0.98      0.98      0.98       211

Fold 1/5, epoch 6/100 — training...
  Fold 1, epoch 6, train loss: 0.0366, val loss: 0.1668, PR-AUC (anomaly): 0.8229, f2-score (anomaly): 0.9028
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       197
           1       0.81      0.93      0.87        14

    accuracy                           0.98       211
   macro avg       0.90      0.96      0.93       211
weighted avg       0.98      0.98      0.98       211

Fold 1/5, epoch 7/100 — training...
  Fold 1, epoch 7, train loss: 0.0601, val loss: 0.1660, PR-AUC (anomaly): 0.8458, f2-score (anomaly): 0.9028
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       197
           1       0.81      0.93      0.87        14

    accuracy                           0.98       211
   macro avg       0.90      0.96      0.93       211
weighted avg       0.98      0.98      0.98       211

Fold 1/5, epoch 8/100 — training...
  Fold 1, epoch 8, train loss: 0.0681, val loss: 0.1648, PR-AUC (anomaly): 0.8241, f2-score (anomaly): 0.8904
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       197
           1       0.76      0.93      0.84        14

    accuracy                           0.98       211
   macro avg       0.88      0.95      0.91       211
weighted avg       0.98      0.98      0.98       211

Fold 1/5, epoch 9/100 — training...
  Fold 1, epoch 9, train loss: 0.0544, val loss: 0.2059, PR-AUC (anomaly): 0.8185, f2-score (anomaly): 0.9028
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       197
           1       0.81      0.93      0.87        14

    accuracy                           0.98       211
   macro avg       0.90      0.96      0.93       211
weighted avg       0.98      0.98      0.98       211

Fold 1/5, epoch 10/100 — training...
  Fold 1, epoch 10, train loss: 0.0225, val loss: 0.1950, PR-AUC (anomaly): 0.8950, f2-score (anomaly): 0.9028
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       197
           1       0.81      0.93      0.87        14

    accuracy                           0.98       211
   macro avg       0.90      0.96      0.93       211
weighted avg       0.98      0.98      0.98       211

Fold 1/5, epoch 11/100 — training...
  Fold 1, epoch 11, train loss: 0.0227, val loss: 0.1975, PR-AUC (anomaly): 0.8878, f2-score (anomaly): 0.9028
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       197
           1       0.81      0.93      0.87        14

    accuracy                           0.98       211
   macro avg       0.90      0.96      0.93       211
weighted avg       0.98      0.98      0.98       211

Fold 1/5, epoch 12/100 — training...
  Fold 1, epoch 12, train loss: 0.0223, val loss: 0.1773, PR-AUC (anomaly): 0.9312, f2-score (anomaly): 0.9155
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       197
           1       0.87      0.93      0.90        14

    accuracy                           0.99       211
   macro avg       0.93      0.96      0.94       211
weighted avg       0.99      0.99      0.99       211

Fold 1/5, epoch 13/100 — training...
  Fold 1, epoch 13, train loss: 0.0147, val loss: 0.2073, PR-AUC (anomaly): 0.8886, f2-score (anomaly): 0.9155
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       197
           1       0.87      0.93      0.90        14

    accuracy                           0.99       211
   macro avg       0.93      0.96      0.94       211
weighted avg       0.99      0.99      0.99       211

Fold 1/5, epoch 14/100 — training...
  Fold 1, epoch 14, train loss: 0.0277, val loss: 0.1544, PR-AUC (anomaly): 0.9421, f2-score (anomaly): 0.9028
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       197
           1       0.81      0.93      0.87        14

    accuracy                           0.98       211
   macro avg       0.90      0.96      0.93       211
weighted avg       0.98      0.98      0.98       211

Fold 1/5, epoch 15/100 — training...
  Fold 1, epoch 15, train loss: 0.0240, val loss: 0.1775, PR-AUC (anomaly): 0.9078, f2-score (anomaly): 0.9155
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       197
           1       0.87      0.93      0.90        14

    accuracy                           0.99       211
   macro avg       0.93      0.96      0.94       211
weighted avg       0.99      0.99      0.99       211

Fold 1/5, epoch 16/100 — training...
  Fold 1, epoch 16, train loss: 0.0388, val loss: 0.3470, PR-AUC (anomaly): 0.8855, f2-score (anomaly): 0.7143
              precision    recall  f1-score   support

           0       0.99      0.89      0.94       197
           1       0.37      0.93      0.53        14

    accuracy                           0.89       211
   macro avg       0.68      0.91      0.73       211
weighted avg       0.95      0.89      0.91       211

Fold 1/5, epoch 17/100 — training...
  Fold 1, epoch 17, train loss: 0.0508, val loss: 0.2893, PR-AUC (anomaly): 0.8181, f2-score (anomaly): 0.8904
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       197
           1       0.76      0.93      0.84        14

    accuracy                           0.98       211
   macro avg       0.88      0.95      0.91       211
weighted avg       0.98      0.98      0.98       211

Fold 1/5, epoch 18/100 — training...
  Fold 1, epoch 18, train loss: 0.0364, val loss: 0.2701, PR-AUC (anomaly): 0.8085, f2-score (anomaly): 0.9028
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       197
           1       0.81      0.93      0.87        14

    accuracy                           0.98       211
   macro avg       0.90      0.96      0.93       211
weighted avg       0.98      0.98      0.98       211

Fold 1/5, epoch 19/100 — training...
  Fold 1, epoch 19, train loss: 0.0190, val loss: 0.3202, PR-AUC (anomaly): 0.8643, f2-score (anomaly): 0.9028
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       197
           1       0.81      0.93      0.87        14

    accuracy                           0.98       211
   macro avg       0.90      0.96      0.93       211
weighted avg       0.98      0.98      0.98       211

Fold 1/5, epoch 20/100 — training...
  Fold 1, epoch 20, train loss: 0.0147, val loss: 0.2938, PR-AUC (anomaly): 0.8646, f2-score (anomaly): 0.9155
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       197
           1       0.87      0.93      0.90        14

    accuracy                           0.99       211
   macro avg       0.93      0.96      0.94       211
weighted avg       0.99      0.99      0.99       211

Fold 1/5, epoch 21/100 — training...
  Fold 1, epoch 21, train loss: 0.0249, val loss: 0.2659, PR-AUC (anomaly): 0.8646, f2-score (anomaly): 0.9155
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       197
           1       0.87      0.93      0.90        14

    accuracy                           0.99       211
   macro avg       0.93      0.96      0.94       211
weighted avg       0.99      0.99      0.99       211

Fold 1/5, epoch 22/100 — training...
  Fold 1, epoch 22, train loss: 0.0068, val loss: 0.2579, PR-AUC (anomaly): 0.8326, f2-score (anomaly): 0.9155
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       197
           1       0.87      0.93      0.90        14

    accuracy                           0.99       211
   macro avg       0.93      0.96      0.94       211
weighted avg       0.99      0.99      0.99       211

Fold 1/5, epoch 23/100 — training...
  Fold 1, epoch 23, train loss: 0.0182, val loss: 0.2919, PR-AUC (anomaly): 0.8866, f2-score (anomaly): 0.9155
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       197
           1       0.87      0.93      0.90        14

    accuracy                           0.99       211
   macro avg       0.93      0.96      0.94       211
weighted avg       0.99      0.99      0.99       211

Fold 1/5, epoch 24/100 — training...
  Fold 1, epoch 24, train loss: 0.0253, val loss: 0.2943, PR-AUC (anomaly): 0.7729, f2-score (anomaly): 0.9155
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       197
           1       0.87      0.93      0.90        14

    accuracy                           0.99       211
   macro avg       0.93      0.96      0.94       211
weighted avg       0.99      0.99      0.99       211

Fold 1/5, epoch 25/100 — training...
  Fold 1, epoch 25, train loss: 0.0256, val loss: 0.2279, PR-AUC (anomaly): 0.8420, f2-score (anomaly): 0.9155
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       197
           1       0.87      0.93      0.90        14

    accuracy                           0.99       211
   macro avg       0.93      0.96      0.94       211
weighted avg       0.99      0.99      0.99       211

Fold 1/5, epoch 26/100 — training...
  Fold 1, epoch 26, train loss: 0.0163, val loss: 0.2250, PR-AUC (anomaly): 0.8461, f2-score (anomaly): 0.9155
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       197
           1       0.87      0.93      0.90        14

    accuracy                           0.99       211
   macro avg       0.93      0.96      0.94       211
weighted avg       0.99      0.99      0.99       211

Fold 1/5, epoch 27/100 — training...
  Fold 1, epoch 27, train loss: 0.0162, val loss: 0.2605, PR-AUC (anomaly): 0.8777, f2-score (anomaly): 0.9155
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       197
           1       0.87      0.93      0.90        14

    accuracy                           0.99       211
   macro avg       0.93      0.96      0.94       211
weighted avg       0.99      0.99      0.99       211

Early stopping triggered at epoch 27 for fold 1.
Saved fold 1 best model to /home/gonca/Documents/GitHub/IST-Thesis/BridgeDefender/outputs/mlpbased-cctx-eval-tuningpooling-ronin12-omni-nomad-polyn-qubit-harmony-thor123-meter-hypr-xbridge/train_epochs100_augment0_lr0.005_poolmax_nosf_es15_mlpbased_tuningpooling__202608102226/models/fold_1.pt
Fold 2/5, epoch 1/100 — training...
  Fold 2, epoch 1, train loss: 0.6492, val loss: 0.5764, PR-AUC (anomaly): 0.3940, f2-score (anomaly): 0.3125
              precision    recall  f1-score   support

           0       0.95      0.83      0.89       197
           1       0.15      0.43      0.22        14

    accuracy                           0.80       211
   macro avg       0.55      0.63      0.55       211
weighted avg       0.90      0.80      0.84       211

Fold 2/5, epoch 2/100 — training...
  Fold 2, epoch 2, train loss: 0.4205, val loss: 0.2683, PR-AUC (anomaly): 0.7685, f2-score (anomaly): 0.7692
              precision    recall  f1-score   support

           0       1.00      0.89      0.94       197
           1       0.40      1.00      0.57        14

    accuracy                           0.90       211
   macro avg       0.70      0.95      0.76       211
weighted avg       0.96      0.90      0.92       211

Fold 2/5, epoch 3/100 — training...
  Fold 2, epoch 3, train loss: 0.1290, val loss: 0.0499, PR-AUC (anomaly): 0.9122, f2-score (anomaly): 0.9722
              precision    recall  f1-score   support

           0       1.00      0.99      0.99       197
           1       0.88      1.00      0.93        14

    accuracy                           0.99       211
   macro avg       0.94      0.99      0.96       211
weighted avg       0.99      0.99      0.99       211

Fold 2/5, epoch 4/100 — training...
  Fold 2, epoch 4, train loss: 0.1346, val loss: 0.0524, PR-AUC (anomaly): 0.9636, f2-score (anomaly): 0.9722
              precision    recall  f1-score   support

           0       1.00      0.99      0.99       197
           1       0.88      1.00      0.93        14

    accuracy                           0.99       211
   macro avg       0.94      0.99      0.96       211
weighted avg       0.99      0.99      0.99       211

Fold 2/5, epoch 5/100 — training...
  Fold 2, epoch 5, train loss: 0.0821, val loss: 0.0386, PR-AUC (anomaly): 0.9901, f2-score (anomaly): 0.9722
              precision    recall  f1-score   support

           0       1.00      0.99      0.99       197
           1       0.88      1.00      0.93        14

    accuracy                           0.99       211
   macro avg       0.94      0.99      0.96       211
weighted avg       0.99      0.99      0.99       211

Fold 2/5, epoch 6/100 — training...
  Fold 2, epoch 6, train loss: 0.0838, val loss: 0.0402, PR-AUC (anomaly): 1.0000, f2-score (anomaly): 0.9722
              precision    recall  f1-score   support

           0       1.00      0.99      0.99       197
           1       0.88      1.00      0.93        14

    accuracy                           0.99       211
   macro avg       0.94      0.99      0.96       211
weighted avg       0.99      0.99      0.99       211

Fold 2/5, epoch 7/100 — training...
  Fold 2, epoch 7, train loss: 0.0745, val loss: 0.0430, PR-AUC (anomaly): 1.0000, f2-score (anomaly): 0.9722
              precision    recall  f1-score   support

           0       1.00      0.99      0.99       197
           1       0.88      1.00      0.93        14

    accuracy                           0.99       211
   macro avg       0.94      0.99      0.96       211
weighted avg       0.99      0.99      0.99       211

Fold 2/5, epoch 8/100 — training...
  Fold 2, epoch 8, train loss: 0.1422, val loss: 0.0533, PR-AUC (anomaly): 0.9053, f2-score (anomaly): 0.9722
              precision    recall  f1-score   support

           0       1.00      0.99      0.99       197
           1       0.88      1.00      0.93        14

    accuracy                           0.99       211
   macro avg       0.94      0.99      0.96       211
weighted avg       0.99      0.99      0.99       211

Fold 2/5, epoch 9/100 — training...
  Fold 2, epoch 9, train loss: 0.0952, val loss: 0.0389, PR-AUC (anomaly): 0.9860, f2-score (anomaly): 0.9722
              precision    recall  f1-score   support

           0       1.00      0.99      0.99       197
           1       0.88      1.00      0.93        14

    accuracy                           0.99       211
   macro avg       0.94      0.99      0.96       211
weighted avg       0.99      0.99      0.99       211

Fold 2/5, epoch 10/100 — training...
  Fold 2, epoch 10, train loss: 0.0829, val loss: 0.0493, PR-AUC (anomaly): 0.9448, f2-score (anomaly): 0.9722
              precision    recall  f1-score   support

           0       1.00      0.99      0.99       197
           1       0.88      1.00      0.93        14

    accuracy                           0.99       211
   macro avg       0.94      0.99      0.96       211
weighted avg       0.99      0.99      0.99       211

Fold 2/5, epoch 11/100 — training...
  Fold 2, epoch 11, train loss: 0.0530, val loss: 0.0625, PR-AUC (anomaly): 0.9805, f2-score (anomaly): 0.9589
              precision    recall  f1-score   support

           0       1.00      0.98      0.99       197
           1       0.82      1.00      0.90        14

    accuracy                           0.99       211
   macro avg       0.91      0.99      0.95       211
weighted avg       0.99      0.99      0.99       211

Fold 2/5, epoch 12/100 — training...
  Fold 2, epoch 12, train loss: 0.1071, val loss: 0.0679, PR-AUC (anomaly): 0.8869, f2-score (anomaly): 0.9589
              precision    recall  f1-score   support

           0       1.00      0.98      0.99       197
           1       0.82      1.00      0.90        14

    accuracy                           0.99       211
   macro avg       0.91      0.99      0.95       211
weighted avg       0.99      0.99      0.99       211

Fold 2/5, epoch 13/100 — training...
  Fold 2, epoch 13, train loss: 0.0693, val loss: 0.0586, PR-AUC (anomaly): 0.8254, f2-score (anomaly): 0.9722
              precision    recall  f1-score   support

           0       1.00      0.99      0.99       197
           1       0.88      1.00      0.93        14

    accuracy                           0.99       211
   macro avg       0.94      0.99      0.96       211
weighted avg       0.99      0.99      0.99       211

Fold 2/5, epoch 14/100 — training...
  Fold 2, epoch 14, train loss: 0.1284, val loss: 0.0304, PR-AUC (anomaly): 0.9952, f2-score (anomaly): 0.9722
              precision    recall  f1-score   support

           0       1.00      0.99      0.99       197
           1       0.88      1.00      0.93        14

    accuracy                           0.99       211

'/home/gonca/Documents/GitHub/IST-Thesis/BridgeDefender/outputs/mlpbased-cctx-eval-tuningpooling-ronin12-omni-nomad-polyn-qubit-harmony-thor123-meter-hypr-xbridge/train_epochs100_augment0_lr0.005_poolmax_nosf_es15_mlpbased_tuningpooling__202608102226'

In [20]:
# Run for sum pooling
pooling = "sum"
Cli.train_model(SimpleNamespace(
    **fixed_args,
    pooling=pooling
))

Early stopping: 15
Splitting dataset into train/val/test sets with test size 15% and 5 folds for cross-validation.
Normalizing node features using min-max normalization.
Label distribution in train/val pool: 983 normal, 71 anomaly.
Identified 499 differential meta-paths for training.
Fold 1/5, epoch 1/100 — training...
  Fold 1, epoch 1, train loss: 0.7465, val loss: 0.6368, PR-AUC (anomaly): 0.2014, f2-score (anomaly): 0.0000
              precision    recall  f1-score   support

           0       0.93      1.00      0.97       197
           1       0.00      0.00      0.00        14

    accuracy                           0.93       211
   macro avg       0.47      0.50      0.48       211
weighted avg       0.87      0.93      0.90       211

Fold 1/5, epoch 2/100 — training...
  Fold 1, epoch 2, train loss: 0.6626, val loss: 0.6078, PR-AUC (anomaly): 0.5721, f2-score (anomaly): 0.5435
              precision    recall  f1-score   support

           0       0.98      0.87      0.92       197
           1       0.28      0.71      0.40        14

    accuracy                           0.86       211
   macro avg       0.63      0.79      0.66       211
weighted avg       0.93      0.86      0.88       211

Fold 1/5, epoch 3/100 — training...
  Fold 1, epoch 3, train loss: 0.5951, val loss: 0.5201, PR-AUC (anomaly): 0.7327, f2-score (anomaly): 0.6923
              precision    recall  f1-score   support

           0       0.98      1.00      0.99       197
           1       1.00      0.64      0.78        14

    accuracy                           0.98       211
   macro avg       0.99      0.82      0.89       211
weighted avg       0.98      0.98      0.97       211

Fold 1/5, epoch 4/100 — training...
  Fold 1, epoch 4, train loss: 0.3183, val loss: 0.1579, PR-AUC (anomaly): 0.9547, f2-score (anomaly): 0.7558
              precision    recall  f1-score   support

           0       0.99      0.91      0.95       197
           1       0.43      0.93      0.59        14

    accuracy                           0.91       211
   macro avg       0.71      0.92      0.77       211
weighted avg       0.96      0.91      0.93       211

Fold 1/5, epoch 5/100 — training...
  Fold 1, epoch 5, train loss: 0.1278, val loss: 0.1201, PR-AUC (anomaly): 0.9001, f2-score (anomaly): 0.9028
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       197
           1       0.81      0.93      0.87        14

    accuracy                           0.98       211
   macro avg       0.90      0.96      0.93       211
weighted avg       0.98      0.98      0.98       211

Fold 1/5, epoch 6/100 — training...
  Fold 1, epoch 6, train loss: 0.0851, val loss: 0.0871, PR-AUC (anomaly): 0.9371, f2-score (anomaly): 0.9028
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       197
           1       0.81      0.93      0.87        14

    accuracy                           0.98       211
   macro avg       0.90      0.96      0.93       211
weighted avg       0.98      0.98      0.98       211

Fold 1/5, epoch 7/100 — training...
  Fold 1, epoch 7, train loss: 0.1011, val loss: 0.2101, PR-AUC (anomaly): 0.8877, f2-score (anomaly): 0.7865
              precision    recall  f1-score   support

           0       1.00      0.90      0.95       197
           1       0.42      1.00      0.60        14

    accuracy                           0.91       211
   macro avg       0.71      0.95      0.77       211
weighted avg       0.96      0.91      0.93       211

Fold 1/5, epoch 8/100 — training...
  Fold 1, epoch 8, train loss: 0.0732, val loss: 0.1456, PR-AUC (anomaly): 0.9305, f2-score (anomaly): 0.8904
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       197
           1       0.76      0.93      0.84        14

    accuracy                           0.98       211
   macro avg       0.88      0.95      0.91       211
weighted avg       0.98      0.98      0.98       211

Fold 1/5, epoch 9/100 — training...
  Fold 1, epoch 9, train loss: 0.0595, val loss: 0.1063, PR-AUC (anomaly): 0.9490, f2-score (anomaly): 0.9028
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       197
           1       0.81      0.93      0.87        14

    accuracy                           0.98       211
   macro avg       0.90      0.96      0.93       211
weighted avg       0.98      0.98      0.98       211

Fold 1/5, epoch 10/100 — training...
  Fold 1, epoch 10, train loss: 0.0472, val loss: 0.1224, PR-AUC (anomaly): 0.9090, f2-score (anomaly): 0.9028
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       197
           1       0.81      0.93      0.87        14

    accuracy                           0.98       211
   macro avg       0.90      0.96      0.93       211
weighted avg       0.98      0.98      0.98       211

Fold 1/5, epoch 11/100 — training...
  Fold 1, epoch 11, train loss: 0.0999, val loss: 0.1419, PR-AUC (anomaly): 0.9182, f2-score (anomaly): 0.8667
              precision    recall  f1-score   support

           0       0.99      0.97      0.98       197
           1       0.68      0.93      0.79        14

    accuracy                           0.97       211
   macro avg       0.84      0.95      0.88       211
weighted avg       0.97      0.97      0.97       211

Fold 1/5, epoch 12/100 — training...
  Fold 1, epoch 12, train loss: 0.0685, val loss: 0.1056, PR-AUC (anomaly): 0.9407, f2-score (anomaly): 0.8904
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       197
           1       0.76      0.93      0.84        14

    accuracy                           0.98       211
   macro avg       0.88      0.95      0.91       211
weighted avg       0.98      0.98      0.98       211

Fold 1/5, epoch 13/100 — training...
  Fold 1, epoch 13, train loss: 0.0406, val loss: 0.1599, PR-AUC (anomaly): 0.9016, f2-score (anomaly): 0.9028
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       197
           1       0.81      0.93      0.87        14

    accuracy                           0.98       211
   macro avg       0.90      0.96      0.93       211
weighted avg       0.98      0.98      0.98       211

Fold 1/5, epoch 14/100 — training...
  Fold 1, epoch 14, train loss: 0.0670, val loss: 0.1258, PR-AUC (anomaly): 0.9203, f2-score (anomaly): 0.8228
              precision    recall  f1-score   support

           0       0.99      0.95      0.97       197
           1       0.57      0.93      0.70        14

    accuracy                           0.95       211
   macro avg       0.78      0.94      0.84       211
weighted avg       0.97      0.95      0.95       211

Fold 1/5, epoch 15/100 — training...
  Fold 1, epoch 15, train loss: 0.1134, val loss: 0.1552, PR-AUC (anomaly): 0.8551, f2-score (anomaly): 0.8904
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       197
           1       0.76      0.93      0.84        14

    accuracy                           0.98       211
   macro avg       0.88      0.95      0.91       211
weighted avg       0.98      0.98      0.98       211

Fold 1/5, epoch 16/100 — training...
  Fold 1, epoch 16, train loss: 0.0590, val loss: 0.1483, PR-AUC (anomaly): 0.9537, f2-score (anomaly): 0.8553
              precision    recall  f1-score   support

           0       0.99      0.96      0.98       197
           1       0.65      0.93      0.76        14

    accuracy                           0.96       211
   macro avg       0.82      0.95      0.87       211
weighted avg       0.97      0.96      0.97       211

Fold 1/5, epoch 17/100 — training...
  Fold 1, epoch 17, train loss: 0.0339, val loss: 0.1013, PR-AUC (anomaly): 0.8886, f2-score (anomaly): 0.8904
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       197
           1       0.76      0.93      0.84        14

    accuracy                           0.98       211
   macro avg       0.88      0.95      0.91       211
weighted avg       0.98      0.98      0.98       211

Fold 1/5, epoch 18/100 — training...
  Fold 1, epoch 18, train loss: 0.0315, val loss: 0.1317, PR-AUC (anomaly): 0.9262, f2-score (anomaly): 0.9028
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       197
           1       0.81      0.93      0.87        14

    accuracy                           0.98       211
   macro avg       0.90      0.96      0.93       211
weighted avg       0.98      0.98      0.98       211

Fold 1/5, epoch 19/100 — training...
  Fold 1, epoch 19, train loss: 0.0146, val loss: 0.1453, PR-AUC (anomaly): 0.9130, f2-score (anomaly): 0.9028
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       197
           1       0.81      0.93      0.87        14

    accuracy                           0.98       211
   macro avg       0.90      0.96      0.93       211
weighted avg       0.98      0.98      0.98       211

Fold 1/5, epoch 20/100 — training...
  Fold 1, epoch 20, train loss: 0.0223, val loss: 0.1327, PR-AUC (anomaly): 0.9260, f2-score (anomaly): 0.9028
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       197
           1       0.81      0.93      0.87        14

    accuracy                           0.98       211
   macro avg       0.90      0.96      0.93       211
weighted avg       0.98      0.98      0.98       211

Early stopping triggered at epoch 20 for fold 1.
Saved fold 1 best model to /home/gonca/Documents/GitHub/IST-Thesis/BridgeDefender/outputs/mlpbased-cctx-eval-tuningpooling-ronin12-omni-nomad-polyn-qubit-harmony-thor123-meter-hypr-xbridge/train_epochs100_augment0_lr0.005_poolsum_nosf_es15_mlpbased_tuningpooling__202608102239/models/fold_1.pt
Fold 2/5, epoch 1/100 — training...
  Fold 2, epoch 1, train loss: 0.7514, val loss: 0.5908, PR-AUC (anomaly): 0.3114, f2-score (anomaly): 0.2564
              precision    recall  f1-score   support

           0       0.95      0.72      0.82       197
           1       0.10      0.43      0.16        14

    accuracy                           0.70       211
   macro avg       0.52      0.57      0.49       211
weighted avg       0.89      0.70      0.77       211

Fold 2/5, epoch 2/100 — training...
  Fold 2, epoch 2, train loss: 0.5113, val loss: 0.3501, PR-AUC (anomaly): 0.7527, f2-score (anomaly): 0.6250
              precision    recall  f1-score   support

           0       0.97      0.96      0.97       197
           1       0.56      0.64      0.60        14

    accuracy                           0.94       211
   macro avg       0.77      0.80      0.78       211
weighted avg       0.95      0.94      0.94       211

Fold 2/5, epoch 3/100 — training...
  Fold 2, epoch 3, train loss: 0.2553, val loss: 0.1115, PR-AUC (anomaly): 0.8396, f2-score (anomaly): 0.8974
              precision    recall  f1-score   support

           0       1.00      0.96      0.98       197
           1       0.64      1.00      0.78        14

    accuracy                           0.96       211
   macro avg       0.82      0.98      0.88       211
weighted avg       0.98      0.96      0.97       211

Fold 2/5, epoch 4/100 — training...
  Fold 2, epoch 4, train loss: 0.1521, val loss: 0.0672, PR-AUC (anomaly): 0.8405, f2-score (anomaly): 0.9722
              precision    recall  f1-score   support

           0       1.00      0.99      0.99       197
           1       0.88      1.00      0.93        14

    accuracy                           0.99       211
   macro avg       0.94      0.99      0.96       211
weighted avg       0.99      0.99      0.99       211

Fold 2/5, epoch 5/100 — training...
  Fold 2, epoch 5, train loss: 0.0881, val loss: 0.0613, PR-AUC (anomaly): 0.9061, f2-score (anomaly): 0.9333
              precision    recall  f1-score   support

           0       1.00      0.97      0.99       197
           1       0.74      1.00      0.85        14

    accuracy                           0.98       211
   macro avg       0.87      0.99      0.92       211
weighted avg       0.98      0.98      0.98       211

Fold 2/5, epoch 6/100 — training...
  Fold 2, epoch 6, train loss: 0.0914, val loss: 0.0512, PR-AUC (anomaly): 0.9186, f2-score (anomaly): 0.9722
              precision    recall  f1-score   support

           0       1.00      0.99      0.99       197
           1       0.88      1.00      0.93        14

    accuracy                           0.99       211
   macro avg       0.94      0.99      0.96       211
weighted avg       0.99      0.99      0.99       211

Fold 2/5, epoch 7/100 — training...
  Fold 2, epoch 7, train loss: 0.0703, val loss: 0.0720, PR-AUC (anomaly): 0.9212, f2-score (anomaly): 0.9211
              precision    recall  f1-score   support

           0       1.00      0.97      0.98       197
           1       0.70      1.00      0.82        14

    accuracy                           0.97       211
   macro avg       0.85      0.98      0.90       211
weighted avg       0.98      0.97      0.97       211

Fold 2/5, epoch 8/100 — training...
  Fold 2, epoch 8, train loss: 0.0375, val loss: 0.0451, PR-AUC (anomaly): 0.9604, f2-score (anomaly): 0.9589
              precision    recall  f1-score   support

           0       1.00      0.98      0.99       197
           1       0.82      1.00      0.90        14

    accuracy                           0.99       211
   macro avg       0.91      0.99      0.95       211
weighted avg       0.99      0.99      0.99       211

Fold 2/5, epoch 9/100 — training...
  Fold 2, epoch 9, train loss: 0.0615, val loss: 0.0756, PR-AUC (anomaly): 0.8458, f2-score (anomaly): 0.9589
              precision    recall  f1-score   support

           0       1.00      0.98      0.99       197
           1       0.82      1.00      0.90        14

    accuracy                           0.99       211
   macro avg       0.91      0.99      0.95       211
weighted avg       0.99      0.99      0.99       211

Fold 2/5, epoch 10/100 — training...
  Fold 2, epoch 10, train loss: 0.1253, val loss: 0.0607, PR-AUC (anomaly): 0.9275, f2-score (anomaly): 0.9459
              precision    recall  f1-score   support

           0       1.00      0.98      0.99       197
           1       0.78      1.00      0.88        14

    accuracy                           0.98       211
   macro avg       0.89      0.99      0.93       211
weighted avg       0.99      0.98      0.98       211

Fold 2/5, epoch 11/100 — training...
  Fold 2, epoch 11, train loss: 0.0707, val loss: 0.0596, PR-AUC (anomaly): 0.9815, f2-score (anomaly): 0.9333
              precision    recall  f1-score   support

           0       1.00      0.97      0.99       197
           1       0.74      1.00      0.85        14

    accuracy                           0.98       211
   macro avg       0.87      0.99      0.92       211
weighted avg       0.98      0.98      0.98       211

Fold 2/5, epoch 12/100 — training...
  Fold 2, epoch 12, train loss: 0.0382, val loss: 0.0586, PR-AUC (anomaly): 0.9815, f2-score (anomaly): 0.9589
              precision    recall  f1-score   support

           0       1.00      0.98      0.99       197
           1       0.82      1.00      0.90        14

    accuracy                           0.99       211
   macro avg       0.91      0.99      0.95       211
weighted avg       0.99      0.99      0.99       211

Fold 2/5, epoch 13/100 — training...
  Fold 2, epoch 13, train loss: 0.0432, val loss: 0.0367, PR-AUC (anomaly): 0.9713, f2-score (anomaly): 0.9722
              precision    recall  f1-score   support

           0       1.00      0.99      0.99       197
           1       0.88      1.00      0.93        14

    accuracy                           0.99       211
   macro avg       0.94      0.99      0.96       211
weighted avg       0.99      0.99      0.99       211

Fold 2/5, epoch 14/100 — training...
  Fold 2, epoch 14, train loss: 0.0605, val loss: 0.0453, PR-AUC (anomaly): 0.9911, f2-score (anomaly): 0.9589
              precision    recall  f1-score   support

           0       1.00      0.98      0.99       197
           1       0.82      1.00      0.90        14

    accuracy                           0.99       211
   macro avg       0.91      0.99      0.95       211
weighted avg       0.99      0.99      0.99       211

Fold 2/5, epoch 15/100 — training...
  Fold 2, epoch 15, train loss: 0.0515, val loss: 0.0665, PR-AUC (anomaly): 0.9952, f2-score (anomaly): 0.9459
              precision    recall  f1-score   support

           0       1.00      0.98      0.99       197
           1       0.78      1.00      0.88        14

    accuracy                           0.98       211
   macro avg       0.89      0.99      0.93       211
weighted avg       0.99      0.98      0.98       211

Fold 2/5, epoch 16/100 — training...
  Fold 2, epoch 16, train loss: 0.1049, val loss: 0.0621, PR-AUC (anomaly): 0.9815, f2-score (anomaly): 0.9333
              precision    recall  f1-score   support

           0       1.00      0.97      0.99       197
           1       0.74      1.00      0.85        14

    accuracy                           0.98       211
   macro avg       0.87      0.99      0.92       211
weighted avg       0.98      0.98      0.98       211

Fold 2/5, epoch 17/100 — training...
  Fold 2, epoch 17, train loss: 0.0747, val loss: 0.0693, PR-AUC (anomaly): 0.9761, f2-score (anomaly): 0.9211
              precision    recall  f1-score   support

           0       1.00      0.97      0.98       197
           1       0.70      1.00      0.82        14

    accuracy                           0.97       211
   macro avg       0.85      0.98      0.90       211
weighted avg       0.98      0.97      0.97       211

Fold 2/5, epoch 18/100 — training...
  Fold 2, epoch 18, train loss: 0.0504, val loss: 0.1162, PR-AUC (anomaly): 0.9911, f2-score (anomaly): 0.9211
              precision    recall  f1-score   support

           0       1.00      0.97      0.98       197
           1       0.70      1.00      0.82        14

    accuracy                           0.97       211
   macro avg       0.85      0.98      0.90       211
weighted avg       0.98      0.97      0.97       211

Fold 2/5, epoch 19/100 — training...
  Fold 2, epoch 19, train loss: 0.0463, val loss: 0.0492, PR-AUC (anomaly): 0.9484, f2-score (anomaly): 0.9589
              precision    recall  f1-score   support

           0       1.00      0.98      0.99       197
           1       0.82      1.00      0.90        14

    accuracy                           0.99       211
   macro avg       0.91      0.99      0.95       211
weighted avg       0.99      0.99      0.99       211

Early stopping triggered at epoch 19 for fold 2.
Saved fold 2 best model to /home/gonca/Documents/GitHub/IST-Thesis/BridgeDefender/outputs/mlpbased-cctx-eval-tuningpooling-ronin12-omni-nomad-polyn-qubit-harmony-thor123-meter-hypr-xbridge/train_epochs100_augment0_lr0.005_poolsum_nosf_es15_mlpbased_tuningpooling__202608102239/models/fold_2.pt
Fold 3/5, epoch 1/100 — training...
  Fold 3, epoch 1, train loss: 0.7291, val loss: 0.6773, PR-AUC (anomaly): 0.1183, f2-score (anomaly): 0.3516
              precision    recall  f1-score   support

           0       0.96      0.68      0.80       197
           1       0.12      0.64      0.21        14

    accuracy                           0.68       211
   macro avg       0.54      0.66      0.50       211
weighted avg       0.91      0.68      0.76       211

Fold 3/5, epoch 2/100 — training...

'/home/gonca/Documents/GitHub/IST-Thesis/BridgeDefender/outputs/mlpbased-cctx-eval-tuningpooling-ronin12-omni-nomad-polyn-qubit-harmony-thor123-meter-hypr-xbridge/train_epochs100_augment0_lr0.005_poolsum_nosf_es15_mlpbased_tuningpooling__202608102239'

In [21]:
# Run for mean+max pooling
pooling = "mean_max"
Cli.train_model(SimpleNamespace(
    **fixed_args,
    pooling=pooling
))

Early stopping: 15
Splitting dataset into train/val/test sets with test size 15% and 5 folds for cross-validation.
Normalizing node features using min-max normalization.
Label distribution in train/val pool: 983 normal, 71 anomaly.
Identified 499 differential meta-paths for training.
Fold 1/5, epoch 1/100 — training...
  Fold 1, epoch 1, train loss: 0.6317, val loss: 0.5130, PR-AUC (anomaly): 0.6285, f2-score (anomaly): 0.4140
              precision    recall  f1-score   support

           0       0.99      0.55      0.71       197
           1       0.13      0.93      0.23        14

    accuracy                           0.58       211
   macro avg       0.56      0.74      0.47       211
weighted avg       0.93      0.58      0.68       211

Fold 1/5, epoch 2/100 — training...
  Fold 1, epoch 2, train loss: 0.3375, val loss: 0.2637, PR-AUC (anomaly): 0.8264, f2-score (anomaly): 0.6566
              precision    recall  f1-score   support

           0       0.99      0.85      0.92       197
           1       0.30      0.93      0.46        14

    accuracy                           0.85       211
   macro avg       0.65      0.89      0.69       211
weighted avg       0.95      0.85      0.88       211

Fold 1/5, epoch 3/100 — training...
  Fold 1, epoch 3, train loss: 0.1577, val loss: 0.1437, PR-AUC (anomaly): 0.8835, f2-score (anomaly): 0.8553
              precision    recall  f1-score   support

           0       0.99      0.96      0.98       197
           1       0.65      0.93      0.76        14

    accuracy                           0.96       211
   macro avg       0.82      0.95      0.87       211
weighted avg       0.97      0.96      0.97       211

Fold 1/5, epoch 4/100 — training...
  Fold 1, epoch 4, train loss: 0.0924, val loss: 0.1319, PR-AUC (anomaly): 0.8941, f2-score (anomaly): 0.9155
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       197
           1       0.87      0.93      0.90        14

    accuracy                           0.99       211
   macro avg       0.93      0.96      0.94       211
weighted avg       0.99      0.99      0.99       211

Fold 1/5, epoch 5/100 — training...
  Fold 1, epoch 5, train loss: 0.0526, val loss: 0.1426, PR-AUC (anomaly): 0.9136, f2-score (anomaly): 0.9028
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       197
           1       0.81      0.93      0.87        14

    accuracy                           0.98       211
   macro avg       0.90      0.96      0.93       211
weighted avg       0.98      0.98      0.98       211

Fold 1/5, epoch 6/100 — training...
  Fold 1, epoch 6, train loss: 0.0542, val loss: 0.2081, PR-AUC (anomaly): 0.9007, f2-score (anomaly): 0.8333
              precision    recall  f1-score   support

           0       0.99      0.95      0.97       197
           1       0.59      0.93      0.72        14

    accuracy                           0.95       211
   macro avg       0.79      0.94      0.85       211
weighted avg       0.97      0.95      0.96       211

Fold 1/5, epoch 7/100 — training...
  Fold 1, epoch 7, train loss: 0.0637, val loss: 0.1746, PR-AUC (anomaly): 0.8296, f2-score (anomaly): 0.9028
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       197
           1       0.81      0.93      0.87        14

    accuracy                           0.98       211
   macro avg       0.90      0.96      0.93       211
weighted avg       0.98      0.98      0.98       211

Fold 1/5, epoch 8/100 — training...
  Fold 1, epoch 8, train loss: 0.0822, val loss: 0.1848, PR-AUC (anomaly): 0.7745, f2-score (anomaly): 0.9028
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       197
           1       0.81      0.93      0.87        14

    accuracy                           0.98       211
   macro avg       0.90      0.96      0.93       211
weighted avg       0.98      0.98      0.98       211

Fold 1/5, epoch 9/100 — training...
  Fold 1, epoch 9, train loss: 0.0582, val loss: 0.1778, PR-AUC (anomaly): 0.9051, f2-score (anomaly): 0.9028
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       197
           1       0.81      0.93      0.87        14

    accuracy                           0.98       211
   macro avg       0.90      0.96      0.93       211
weighted avg       0.98      0.98      0.98       211

Fold 1/5, epoch 10/100 — training...
  Fold 1, epoch 10, train loss: 0.0712, val loss: 0.1788, PR-AUC (anomaly): 0.9125, f2-score (anomaly): 0.9028
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       197
           1       0.81      0.93      0.87        14

    accuracy                           0.98       211
   macro avg       0.90      0.96      0.93       211
weighted avg       0.98      0.98      0.98       211

Fold 1/5, epoch 11/100 — training...
  Fold 1, epoch 11, train loss: 0.0357, val loss: 0.1348, PR-AUC (anomaly): 0.9409, f2-score (anomaly): 0.9155
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       197
           1       0.87      0.93      0.90        14

    accuracy                           0.99       211
   macro avg       0.93      0.96      0.94       211
weighted avg       0.99      0.99      0.99       211

Fold 1/5, epoch 12/100 — training...
  Fold 1, epoch 12, train loss: 0.0321, val loss: 0.1623, PR-AUC (anomaly): 0.9598, f2-score (anomaly): 0.9028
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       197
           1       0.81      0.93      0.87        14

    accuracy                           0.98       211
   macro avg       0.90      0.96      0.93       211
weighted avg       0.98      0.98      0.98       211

Fold 1/5, epoch 13/100 — training...
  Fold 1, epoch 13, train loss: 0.0305, val loss: 0.2234, PR-AUC (anomaly): 0.8923, f2-score (anomaly): 0.9028
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       197
           1       0.81      0.93      0.87        14

    accuracy                           0.98       211
   macro avg       0.90      0.96      0.93       211
weighted avg       0.98      0.98      0.98       211

Fold 1/5, epoch 14/100 — training...
  Fold 1, epoch 14, train loss: 0.0149, val loss: 0.1936, PR-AUC (anomaly): 0.9333, f2-score (anomaly): 0.9155
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       197
           1       0.87      0.93      0.90        14

    accuracy                           0.99       211
   macro avg       0.93      0.96      0.94       211
weighted avg       0.99      0.99      0.99       211

Fold 1/5, epoch 15/100 — training...
  Fold 1, epoch 15, train loss: 0.0160, val loss: 0.2098, PR-AUC (anomaly): 0.9382, f2-score (anomaly): 0.9028
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       197
           1       0.81      0.93      0.87        14

    accuracy                           0.98       211
   macro avg       0.90      0.96      0.93       211
weighted avg       0.98      0.98      0.98       211

Fold 1/5, epoch 16/100 — training...
  Fold 1, epoch 16, train loss: 0.0185, val loss: 0.1884, PR-AUC (anomaly): 0.9288, f2-score (anomaly): 0.9155
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       197
           1       0.87      0.93      0.90        14

    accuracy                           0.99       211
   macro avg       0.93      0.96      0.94       211
weighted avg       0.99      0.99      0.99       211

Fold 1/5, epoch 17/100 — training...
  Fold 1, epoch 17, train loss: 0.0117, val loss: 0.1590, PR-AUC (anomaly): 0.9651, f2-score (anomaly): 0.9155
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       197
           1       0.87      0.93      0.90        14

    accuracy                           0.99       211
   macro avg       0.93      0.96      0.94       211
weighted avg       0.99      0.99      0.99       211

Fold 1/5, epoch 18/100 — training...
  Fold 1, epoch 18, train loss: 0.0152, val loss: 0.2230, PR-AUC (anomaly): 0.9327, f2-score (anomaly): 0.9028
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       197
           1       0.81      0.93      0.87        14

    accuracy                           0.98       211
   macro avg       0.90      0.96      0.93       211
weighted avg       0.98      0.98      0.98       211

Fold 1/5, epoch 19/100 — training...
  Fold 1, epoch 19, train loss: 0.0160, val loss: 0.1615, PR-AUC (anomaly): 0.9580, f2-score (anomaly): 0.9155
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       197
           1       0.87      0.93      0.90        14

    accuracy                           0.99       211
   macro avg       0.93      0.96      0.94       211
weighted avg       0.99      0.99      0.99       211

Early stopping triggered at epoch 19 for fold 1.
Saved fold 1 best model to /home/gonca/Documents/GitHub/IST-Thesis/BridgeDefender/outputs/mlpbased-cctx-eval-tuningpooling-ronin12-omni-nomad-polyn-qubit-harmony-thor123-meter-hypr-xbridge/train_epochs100_augment0_lr0.005_poolmean_max_nosf_es15_mlpbased_tuningpooling__202608102251/models/fold_1.pt
Fold 2/5, epoch 1/100 — training...
  Fold 2, epoch 1, train loss: 0.7185, val loss: 0.5745, PR-AUC (anomaly): 0.3304, f2-score (anomaly): 0.2655
              precision    recall  f1-score   support

           0       0.95      0.74      0.83       197
           1       0.11      0.43      0.17        14

    accuracy                           0.72       211
   macro avg       0.53      0.58      0.50       211
weighted avg       0.89      0.72      0.79       211

Fold 2/5, epoch 2/100 — training...
  Fold 2, epoch 2, train loss: 0.3942, val loss: 0.1631, PR-AUC (anomaly): 0.8714, f2-score (anomaly): 0.9333
              precision    recall  f1-score   support

           0       1.00      0.97      0.99       197
           1       0.74      1.00      0.85        14

    accuracy                           0.98       211
   macro avg       0.87      0.99      0.92       211
weighted avg       0.98      0.98      0.98       211

Fold 2/5, epoch 3/100 — training...
  Fold 2, epoch 3, train loss: 0.1772, val loss: 0.0570, PR-AUC (anomaly): 0.9053, f2-score (anomaly): 0.9722
              precision    recall  f1-score   support

           0       1.00      0.99      0.99       197
           1       0.88      1.00      0.93        14

    accuracy                           0.99       211
   macro avg       0.94      0.99      0.96       211
weighted avg       0.99      0.99      0.99       211

Fold 2/5, epoch 4/100 — training...
  Fold 2, epoch 4, train loss: 0.0968, val loss: 0.1145, PR-AUC (anomaly): 0.8697, f2-score (anomaly): 0.9333
              precision    recall  f1-score   support

           0       1.00      0.97      0.99       197
           1       0.74      1.00      0.85        14

    accuracy                           0.98       211
   macro avg       0.87      0.99      0.92       211
weighted avg       0.98      0.98      0.98       211

Fold 2/5, epoch 5/100 — training...
  Fold 2, epoch 5, train loss: 0.1816, val loss: 0.1015, PR-AUC (anomaly): 0.9030, f2-score (anomaly): 0.9211
              precision    recall  f1-score   support

           0       1.00      0.97      0.98       197
           1       0.70      1.00      0.82        14

    accuracy                           0.97       211
   macro avg       0.85      0.98      0.90       211
weighted avg       0.98      0.97      0.97       211

Fold 2/5, epoch 6/100 — training...
  Fold 2, epoch 6, train loss: 0.1044, val loss: 0.0460, PR-AUC (anomaly): 0.9539, f2-score (anomaly): 0.9722
              precision    recall  f1-score   support

           0       1.00      0.99      0.99       197
           1       0.88      1.00      0.93        14

    accuracy                           0.99       211
   macro avg       0.94      0.99      0.96       211
weighted avg       0.99      0.99      0.99       211

Fold 2/5, epoch 7/100 — training...
  Fold 2, epoch 7, train loss: 0.1210, val loss: 0.0618, PR-AUC (anomaly): 0.9805, f2-score (anomaly): 0.9722
              precision    recall  f1-score   support

           0       1.00      0.99      0.99       197
           1       0.88      1.00      0.93        14

    accuracy                           0.99       211
   macro avg       0.94      0.99      0.96       211
weighted avg       0.99      0.99      0.99       211

Fold 2/5, epoch 8/100 — training...
  Fold 2, epoch 8, train loss: 0.1025, val loss: 0.0676, PR-AUC (anomaly): 0.9636, f2-score (anomaly): 0.9722
              precision    recall  f1-score   support

           0       1.00      0.99      0.99       197
           1       0.88      1.00      0.93        14

    accuracy                           0.99       211
   macro avg       0.94      0.99      0.96       211
weighted avg       0.99      0.99      0.99       211

Fold 2/5, epoch 9/100 — training...
  Fold 2, epoch 9, train loss: 0.1071, val loss: 0.0697, PR-AUC (anomaly): 0.8756, f2-score (anomaly): 0.9722
              precision    recall  f1-score   support

           0       1.00      0.99      0.99       197
           1       0.88      1.00      0.93        14

    accuracy                           0.99       211
   macro avg       0.94      0.99      0.96       211
weighted avg       0.99      0.99      0.99       211

Fold 2/5, epoch 10/100 — training...
  Fold 2, epoch 10, train loss: 0.0859, val loss: 0.0417, PR-AUC (anomaly): 0.9815, f2-score (anomaly): 0.9722
              precision    recall  f1-score   support

           0       1.00      0.99      0.99       197
           1       0.88      1.00      0.93        14

    accuracy                           0.99       211
   macro avg       0.94      0.99      0.96       211
weighted avg       0.99      0.99      0.99       211

Fold 2/5, epoch 11/100 — training...
  Fold 2, epoch 11, train loss: 0.0799, val loss: 0.0551, PR-AUC (anomaly): 0.9654, f2-score (anomaly): 0.9722
              precision    recall  f1-score   support

           0       1.00      0.99      0.99       197
           1       0.88      1.00      0.93        14

    accuracy                           0.99       211
   macro avg       0.94      0.99      0.96       211
weighted avg       0.99      0.99      0.99       211

Fold 2/5, epoch 12/100 — training...
  Fold 2, epoch 12, train loss: 0.0993, val loss: 0.0604, PR-AUC (anomaly): 0.9611, f2-score (anomaly): 0.9459
              precision    recall  f1-score   support

           0       1.00      0.98      0.99       197
           1       0.78      1.00      0.88        14

    accuracy                           0.98       211
   macro avg       0.89      0.99      0.93       211
weighted avg       0.99      0.98      0.98       211

Fold 2/5, epoch 13/100 — training...
  Fold 2, epoch 13, train loss: 0.0605, val loss: 0.0554, PR-AUC (anomaly): 0.9475, f2-score (anomaly): 0.9722
              precision    recall  f1-score   support

           0       1.00      0.99      0.99       197
           1       0.88      1.00      0.93        14

    accuracy                           0.99       211
   macro avg       0.94      0.99      0.96       211
weighted avg       0.99      0.99      0.99       211

Fold 2/5, epoch 14/100 — training...
  Fold 2, epoch 14, train loss: 0.0369, val loss: 0.0525, PR-AUC (anomaly): 0.9611, f2-score (anomaly): 0.9722
              precision    recall  f1-score   support

           0       1.00      0.99      0.99       197
           1       0.88      1.00      0.93        14

    accuracy                           0.99       211
   macro avg       0.94      0.99      0.96       211
weighted avg       0.99      0.99      0.99       211

Fold 2/5, epoch 15/100 — training...
  Fold 2, epoch 15, train loss: 0.0838, val loss: 0.0560, PR-AUC (anomaly): 0.9611, f2-score (anomaly): 0.9589
              precision    recall  f1-score   support

           0       1.00      0.98      0.99       197
           1       0.82      1.00      0.90        14

    accuracy                           0.99       211
   macro avg       0.91      0.99      0.95       211
weighted avg       0.99      0.99      0.99       211

Fold 2/5, epoch 16/100 — training...
  Fold 2, epoch 16, train loss: 0.0488, val loss: 0.0661, PR-AUC (anomaly): 0.9567, f2-score (anomaly): 0.9459
              precision    recall  f1-score   support

           0       1.00      0.98      0.99       197
           1       0.78      1.00      0.88        14

    accuracy                           0.98       211
   macro avg       0.89      0.99      0.93       211
weighted avg       0.99      0.98      0.98       211

Fold 2/5, epoch 17/100 — training...
  Fold 2, epoch 17, train loss: 0.0452, val loss: 0.1133, PR-AUC (anomaly): 0.9611, f2-score (anomaly): 0.9211
              precision    recall  f1-score   support

           0       1.00      0.97      0.98       197
           1       0.70      1.00      0.82        14

    accuracy                           0.97       211
   macro avg       0.85      0.98      0.90       211
weighted avg       0.98      0.97      0.97       211

Fold 2/5, epoch 18/100 — training...
  Fold 2, epoch 18, train loss: 0.0640, val loss: 0.0495, PR-AUC (anomaly): 0.7839, f2-score (anomaly): 0.9722
              precision    recall  f1-score   support

           0       1.00      0.99      0.99       197
           1       0.88      1.00      0.93        14

    accuracy                           0.99       211
   macro avg       0.94      0.99      0.96       211
weighted avg       0.99      0.99      0.99       211

Early stopping triggered at epoch 18 for fold 2.
Saved fold 2 best model to /home/gonca/Documents/GitHub/IST-Thesis/BridgeDefender/outputs/mlpbased-cctx-eval-tuningpooling-ronin12-omni-nomad-polyn-qubit-harmony-thor123-meter-hypr-xbridge/train_epochs100_augment0_lr0.005_poolmean_max_nosf_es15_mlpbased_tuningpooling__202608102251/models/fold_2.pt
Fold 3/5, epoch 1/100 — training...
  Fold 3, epoch 1, train loss: 0.6680, val loss: 0.5960, PR-AUC (anomaly): 0.3603, f2-score (anomaly): 0.4054
              precision    recall  f1-score   support

           0       0.97      0.77      0.86       197
           1       0.16      0.64      0.26        14

    accuracy                           0.76       211
   macro avg       0.57      0.70      0.56       211
weighted avg       0.91      0.76      0.82       211

Fold 3/5, epoch 2/100 — training...
  Fold 3, epoch 2, train loss: 0.5105, val loss: 0.2322, PR-AUC (anomaly): 0.8801, f2-score (anomaly): 0.8642
              precision    recall  f1-score   support

           0       1.00      0.94      0.97       197
           1       0.56      1.00      0.72        14

    accuracy                           0.95       211
   macro avg       0.78      0.97      0.84       211
weighted avg       0.97      0.95      0.95       211

Fold 3/5, epoch 3/100 — training...
  Fold 3, epoch 3, train loss: 0.3352, val loss: 0.1116, PR-AUC (anomaly): 0.9677, f2-score (anomaly): 0.8235
              precision    recall  f1-score   support

           0       1.00      0.92      0.96       197
           1       0.48      1.00      0.65        14

    accuracy                           0.93       211
   macro avg       0.74      0.96      0.81       211
weighted avg       0.97      0.93      0.94       211

Fold 3/5, epoch 4/100 — training...

'/home/gonca/Documents/GitHub/IST-Thesis/BridgeDefender/outputs/mlpbased-cctx-eval-tuningpooling-ronin12-omni-nomad-polyn-qubit-harmony-thor123-meter-hypr-xbridge/train_epochs100_augment0_lr0.005_poolmean_max_nosf_es15_mlpbased_tuningpooling__202608102251'

## Results processing

In [11]:
# Obtain all relevant run directories that match the pattern and contain a params.yaml file
run_dirs = sorted(
    p for p in OUTPUTS_ROOT.glob("train_epochs*")
    if p.is_dir() and (p / "params.yaml").exists()
)

print(f"Found {len(run_dirs)} run directories")
for p in run_dirs:
    print(p)

Found 4 run directories
/home/gonca/Documents/GitHub/IST-Thesis/BridgeDefender/outputs/mlpbased-cctx-eval-tuningpooling-ronin12-omni-nomad-polyn-qubit-harmony-thor123-meter-hypr-xbridge/train_epochs100_augment0_lr0.005_nosf_es15_mlpbased_tuningpooling__202608102212
/home/gonca/Documents/GitHub/IST-Thesis/BridgeDefender/outputs/mlpbased-cctx-eval-tuningpooling-ronin12-omni-nomad-polyn-qubit-harmony-thor123-meter-hypr-xbridge/train_epochs100_augment0_lr0.005_poolmax_nosf_es15_mlpbased_tuningpooling__202608102226
/home/gonca/Documents/GitHub/IST-Thesis/BridgeDefender/outputs/mlpbased-cctx-eval-tuningpooling-ronin12-omni-nomad-polyn-qubit-harmony-thor123-meter-hypr-xbridge/train_epochs100_augment0_lr0.005_poolmean_max_nosf_es15_mlpbased_tuningpooling__202608102251
/home/gonca/Documents/GitHub/IST-Thesis/BridgeDefender/outputs/mlpbased-cctx-eval-tuningpooling-ronin12-omni-nomad-polyn-qubit-harmony-thor123-meter-hypr-xbridge/train_epochs100_augment0_lr0.005_poolsum_nosf_es15_mlpbased_tuningpooling__202608102239

In [12]:
import yaml
import pandas as pd

def load_run_config(run_dir: Path) -> dict:
    TOTAL_METAPATHS = 6475  # Total number of metapaths in the dataset
    with open(run_dir / "params.yaml") as f:
        doc = yaml.safe_load(f)

    return {
        "run_dir": run_dir,
        "run_name": run_dir.name,
        "pooling": doc["params"]["pooling"],
    }

configs = [load_run_config(p) for p in run_dirs]
configs_df = pd.DataFrame(configs)
configs_df

,run_dir,run_name,pooling
0,/home/gonca/Documents/GitHub/IST-Thesis/Bridge...,train_epochs100_augment0_lr0.005_nosf_es15_mlp...,mean
1,/home/gonca/Documents/GitHub/IST-Thesis/Bridge...,train_epochs100_augment0_lr0.005_poolmax_nosf_...,max
2,/home/gonca/Documents/GitHub/IST-Thesis/Bridge...,train_epochs100_augment0_lr0.005_poolmean_max_...,mean_max
3,/home/gonca/Documents/GitHub/IST-Thesis/Bridge...,train_epochs100_augment0_lr0.005_poolsum_nosf_...,sum

In [13]:
def load_val_metrics(run_dir: Path) -> dict:
    df = pd.read_csv(run_dir / "val_best_metrics.csv")
    metric_cols = [c for c in df.columns if c != "fold"]

    result = {"run_dir": run_dir}
    for col in metric_cols:
        result[f"{col}_mean"] = df[col].mean()
        result[f"{col}_std"] = df[col].std(ddof=0)
    
    result["precision_macro_mean"] = ((df["precision_normal"] + df["precision_anomaly"]) / 2).mean()
    result["precision_macro_std"] = ((df["precision_normal"] + df["precision_anomaly"]) / 2).std(ddof=0)
    result["recall_macro_mean"] = ((df["recall_normal"] + df["recall_anomaly"]) / 2).mean()
    result["recall_macro_std"] = ((df["recall_normal"] + df["recall_anomaly"]) / 2).std(ddof=0)
    result["f1_macro_mean"] = ((df["f1_normal"] + df["f1_anomaly"]) / 2).mean()
    result["f1_macro_std"] = ((df["f1_normal"] + df["f1_anomaly"]) / 2).std(ddof=0)
    return result

metrics = [load_val_metrics(p) for p in run_dirs]
metrics_df = pd.DataFrame(metrics)
metrics_df

,run_dir,epoch_mean,epoch_std,val_loss_mean,val_loss_std,accuracy_mean,accuracy_std,precision_normal_mean,precision_normal_std,recall_normal_mean,...,pr_auc_mean,pr_auc_std,mcc_mean,mcc_std,precision_macro_mean,precision_macro_std,recall_macro_mean,recall_macro_std,f1_macro_mean,f1_macro_std
0,/home/gonca/Documents/GitHub/IST-Thesis/Bridge...,9.6,3.611094,0.115066,0.076757,0.992413,0.006427,0.996944,0.002495,0.994924,...,0.962204,0.025965,0.942838,0.047455,0.967222,0.039556,0.976510,0.017497,0.970809,0.024134
1,/home/gonca/Documents/GitHub/IST-Thesis/Bridge...,8.4,2.576820,0.101621,0.066859,0.993360,0.004831,0.996949,0.002491,0.995939,...,0.968548,0.029798,0.949001,0.036975,0.972641,0.031521,0.977017,0.016942,0.974054,0.018660
2,/home/gonca/Documents/GitHub/IST-Thesis/Bridge...,11.2,4.308132,0.077894,0.058907,0.994308,0.005526,0.997964,0.002493,0.995939,...,0.977202,0.022973,0.956273,0.042327,0.973149,0.031934,0.983684,0.018078,0.977757,0.021403
3,/home/gonca/Documents/GitHub/IST-Thesis/Bridge...,10.2,2.135416,0.122502,0.099921,0.990512,0.005995,0.995934,0.003786,0.993903,...,0.967665,0.022307,0.927817,0.044752,0.959574,0.036059,0.969333,0.024937,0.963166,0.022725

In [14]:
def load_fold_durations(run_dir: Path) -> dict:
    df = pd.read_csv(run_dir / "fold_durations.csv")
    return {
        "run_dir": run_dir,
        "fold_time_mean": df["time"].mean(),
        "fold_time_std": df["time"].std(ddof=0),  # match summary.txt convention
        "fold_time_total": df["time"].sum(),
    }

durations = [load_fold_durations(p) for p in run_dirs]
durations_df = pd.DataFrame(durations)
durations_df

,run_dir,fold_time_mean,fold_time_std,fold_time_total
0,/home/gonca/Documents/GitHub/IST-Thesis/Bridge...,155.724,18.744222,778.62
1,/home/gonca/Documents/GitHub/IST-Thesis/Bridge...,138.238,19.286399,691.19
2,/home/gonca/Documents/GitHub/IST-Thesis/Bridge...,137.498,27.591971,687.49
3,/home/gonca/Documents/GitHub/IST-Thesis/Bridge...,131.560,13.302612,657.80

In [15]:
comparison_df = (
    configs_df
    .merge(metrics_df, on="run_dir")
    .merge(durations_df, on="run_dir")
)
comparison_df["pooling"] = pd.Categorical(comparison_df["pooling"], categories=["mean", "max", "sum", "mean_max"])
comparison_df = (
    comparison_df
    .sort_values(["pooling"])
    .reset_index(drop=True)
)
comparison_df

,run_dir,run_name,pooling,epoch_mean,epoch_std,val_loss_mean,val_loss_std,accuracy_mean,accuracy_std,precision_normal_mean,...,mcc_std,precision_macro_mean,precision_macro_std,recall_macro_mean,recall_macro_std,f1_macro_mean,f1_macro_std,fold_time_mean,fold_time_std,fold_time_total
0,/home/gonca/Documents/GitHub/IST-Thesis/Bridge...,train_epochs100_augment0_lr0.005_nosf_es15_mlp...,mean,9.6,3.611094,0.115066,0.076757,0.992413,0.006427,0.996944,...,0.047455,0.967222,0.039556,0.976510,0.017497,0.970809,0.024134,155.724,18.744222,778.62
1,/home/gonca/Documents/GitHub/IST-Thesis/Bridge...,train_epochs100_augment0_lr0.005_poolmax_nosf_...,max,8.4,2.576820,0.101621,0.066859,0.993360,0.004831,0.996949,...,0.036975,0.972641,0.031521,0.977017,0.016942,0.974054,0.018660,138.238,19.286399,691.19
2,/home/gonca/Documents/GitHub/IST-Thesis/Bridge...,train_epochs100_augment0_lr0.005_poolsum_nosf_...,sum,10.2,2.135416,0.122502,0.099921,0.990512,0.005995,0.995934,...,0.044752,0.959574,0.036059,0.969333,0.024937,0.963166,0.022725,131.560,13.302612,657.80
3,/home/gonca/Documents/GitHub/IST-Thesis/Bridge...,train_epochs100_augment0_lr0.005_poolmean_max_...,mean_max,11.2,4.308132,0.077894,0.058907,0.994308,0.005526,0.997964,...,0.042327,0.973149,0.031934,0.983684,0.018078,0.977757,0.021403,137.498,27.591971,687.49

In [16]:
trimmed_df = comparison_df[[
    "pooling",
    "accuracy_mean",
    "accuracy_std",
    "precision_macro_mean",
    "precision_macro_std",
    "recall_macro_mean",
    "recall_macro_std",
    "f1_macro_mean",
    "f1_macro_std",
]]
trimmed_df

,pooling,accuracy_mean,accuracy_std,precision_macro_mean,precision_macro_std,recall_macro_mean,recall_macro_std,f1_macro_mean,f1_macro_std
0,mean,0.992413,0.006427,0.967222,0.039556,0.976510,0.017497,0.970809,0.024134
1,max,0.993360,0.004831,0.972641,0.031521,0.977017,0.016942,0.974054,0.018660
2,sum,0.990512,0.005995,0.959574,0.036059,0.969333,0.024937,0.963166,0.022725
3,mean_max,0.994308,0.005526,0.973149,0.031934,0.983684,0.018078,0.977757,0.021403

In [17]:
PCT_SCALE_EXCLUDE = {"fold_time"}  # keep seconds as seconds, not *100

def format_stat(mean, std, base):
    scale = 1 if base in PCT_SCALE_EXCLUDE else 100
    return f"{mean * scale:.2f} \u00b1 {std * scale:05.2f}"

metric_bases = [c[:-5] for c in trimmed_df.columns if c.endswith("_mean")]

display_df2 = pd.DataFrame(index=trimmed_df.index)
for base in metric_bases:
    display_df2[base] = trimmed_df.apply(
        lambda row: format_stat(row[f"{base}_mean"], row[f"{base}_std"], base), axis=1
    )

display_df2.insert(0, "pooling", trimmed_df["pooling"])
display_df2 = display_df2.set_index("pooling")

final_table2 = display_df2
final_table2

               accuracy precision_macro   recall_macro       f1_macro
pooling
mean      99.24 ± 00.64   96.72 ± 03.96  97.65 ± 01.75  97.08 ± 02.41
max       99.34 ± 00.48   97.26 ± 03.15  97.70 ± 01.69  97.41 ± 01.87
sum       99.05 ± 00.60   95.96 ± 03.61  96.93 ± 02.49  96.32 ± 02.27
mean_max  99.43 ± 00.55   97.31 ± 03.19  98.37 ± 01.81  97.78 ± 02.14

In [18]:
# Turn the unicode ± into LaTeX math syntax, and escape underscores in row labels
import re

METRIC_LABELS = {
    "pooling": "Pooling Type",
    "accuracy": "Accuracy (\\%)",
    "precision_macro": "Precision (\\%)",
    "recall_macro": "Recall (\\%)",
    "f1_macro": "F1-Score (\\%)",
}

POOLING_LABELS = {
    "mean": "Mean Pooling",
    "max": "Max Pooling",
    "sum": "Sum Pooling",
    "mean_max": "Mean + Max Pooling",
}

def to_math_pm(s: str) -> str:
    return re.sub(r"(-?[\d.]+) ± (-?[\d.]+)", r"\1 $\\pm$ \2", s)

latex_ready2 = final_table2.map(to_math_pm)
latex_ready2 = latex_ready2.reset_index()  # turn the "pooling" index back into a plain column
latex_ready2 = latex_ready2.rename(columns=METRIC_LABELS)
latex_ready2["Pooling Type"] = latex_ready2["Pooling Type"].map(POOLING_LABELS)

latex_str = latex_ready2.to_latex(
    index=False,  # drop the numeric row index; "Pooling Type" is now a real column
    escape=False,  # cell values already contain LaTeX ($\pm$), don't double-escape
    column_format="l" + "r" * (len(latex_ready2.columns) - 1),
    caption="Effect of the DME threshold on test-set performance",
    label="tab:ablation_semantic_fusion",
)
print(latex_str)

\begin{table}
\caption{Effect of the DME threshold on test-set performance}
\label{tab:ablation_semantic_fusion}
\begin{tabular}{lrrrr}
\toprule
Pooling Type & Accuracy (\%) & Precision (\%) & Recall (\%) & F1-Score (\%) \\
\midrule
Mean Pooling & 99.24 $\pm$ 00.64 & 96.72 $\pm$ 03.96 & 97.65 $\pm$ 01.75 & 97.08 $\pm$ 02.41 \\
Max Pooling & 99.34 $\pm$ 00.48 & 97.26 $\pm$ 03.15 & 97.70 $\pm$ 01.69 & 97.41 $\pm$ 01.87 \\
Sum Pooling & 99.05 $\pm$ 00.60 & 95.96 $\pm$ 03.61 & 96.93 $\pm$ 02.49 & 96.32 $\pm$ 02.27 \\
Mean + Max Pooling & 99.43 $\pm$ 00.55 & 97.31 $\pm$ 03.19 & 98.37 $\pm$ 01.81 & 97.78 $\pm$ 02.14 \\
\bottomrule
\end{tabular}
\end{table}

# Putting it all together

In [19]:
# Combine the single-chain and cross-chain pooling comparison tables into one,
# tagging each block of rows with the context (model) it came from.

def prep_model_table(df: pd.DataFrame, model_label: str) -> pd.DataFrame:
    prepped = df.map(to_math_pm)
    prepped = prepped.reset_index()  # turn the "pooling" index back into a plain column
    prepped = prepped.rename(columns=METRIC_LABELS)
    prepped["Pooling Type"] = prepped["Pooling Type"].map(POOLING_LABELS)
    prepped.insert(0, "Model", model_label)
    return prepped

combined_df = pd.concat([
    prep_model_table(final_table, "DeepSAD-based (Single-Chain)"),
    prep_model_table(final_table2, "DeepSAD-based (Cross-Chain)"),
], ignore_index=True)
combined_df = combined_df.set_index(["Model", "Pooling Type"])
combined_df

                                                     Accuracy (\%)  \
Model                        Pooling Type
DeepSAD-based (Single-Chain) Mean Pooling        97.14 $\pm$ 01.39
                             Max Pooling         97.34 $\pm$ 01.27
                             Sum Pooling         97.86 $\pm$ 00.75
                             Mean + Max Pooling  97.45 $\pm$ 01.33
DeepSAD-based (Cross-Chain)  Mean Pooling        99.24 $\pm$ 00.64
                             Max Pooling         99.34 $\pm$ 00.48
                             Sum Pooling         99.05 $\pm$ 00.60
                             Mean + Max Pooling  99.43 $\pm$ 00.55

                                                    Precision (\%)  \
Model                        Pooling Type
DeepSAD-based (Single-Chain) Mean Pooling        93.92 $\pm$ 02.49
                             Max Pooling         94.29 $\pm$ 02.35
                             Sum Pooling         95.22 $\pm$ 01.51
                             Mean + Max Pooling  94.50 $\pm$ 02.49
DeepSAD-based (Cross-Chain)  Mean Pooling        96.72 $\pm$ 03.96
                             Max Pooling         97.26 $\pm$ 03.15
                             Sum Pooling         95.96 $\pm$ 03.61
                             Mean + Max Pooling  97.31 $\pm$ 03.19

                                                       Recall (\%)  \
Model                        Pooling Type
DeepSAD-based (Single-Chain) Mean Pooling        98.21 $\pm$ 00.87
                             Max Pooling         98.34 $\pm$ 00.79
                             Sum Pooling         98.66 $\pm$ 00.47
                             Mean + Max Pooling  98.40 $\pm$ 00.83
DeepSAD-based (Cross-Chain)  Mean Pooling        97.65 $\pm$ 01.75
                             Max Pooling         97.70 $\pm$ 01.69
                             Sum Pooling         96.93 $\pm$ 02.49
                             Mean + Max Pooling  98.37 $\pm$ 01.81

                                                     F1-Score (\%)
Model                        Pooling Type
DeepSAD-based (Single-Chain) Mean Pooling        95.81 $\pm$ 01.92
                             Max Pooling         96.09 $\pm$ 01.77
                             Sum Pooling         96.80 $\pm$ 01.09
                             Mean + Max Pooling  96.24 $\pm$ 01.87
DeepSAD-based (Cross-Chain)  Mean Pooling        97.08 $\pm$ 02.41
                             Max Pooling         97.41 $\pm$ 01.87
                             Sum Pooling         96.32 $\pm$ 02.27
                             Mean + Max Pooling  97.78 $\pm$ 02.14

In [20]:
# Build the LaTeX table by hand: a single header row (Model + Pooling Type + metrics),
# vertically-centered \multirow cells for the repeated "Model" values, and \midrule
# (instead of \cline) between the two model blocks.

flat_df = combined_df.reset_index()
metric_cols = [c for c in flat_df.columns if c not in ("Model", "Pooling Type")]

header = " & ".join(["Model", "Pooling Type", *metric_cols]) + r" \\"

body_lines = []
models = flat_df["Model"].unique()
for i, model in enumerate(models):
    group = flat_df[flat_df["Model"] == model]
    for j, (_, row) in enumerate(group.iterrows()):
        model_cell = f"\\multirow{{{len(group)}}}{{*}}{{{model}}}" if j == 0 else ""
        cells = [model_cell, row["Pooling Type"], *[str(v) for v in row[metric_cols]]]
        body_lines.append(" & ".join(cells) + r" \\")
    if i < len(models) - 1:
        body_lines.append(r"\midrule")

column_format = "ll" + "c" * len(metric_cols)
body = "\n".join(body_lines)

latex_str = (
    "\\begin{table}\n"
    "\\centering\n"
    "\\resizebox{\\linewidth}{!}{%\n"
    f"\\begin{{tabular}}{{{column_format}}}\n"
    "\\toprule\n"
    f"{header}\n"
    "\\midrule\n"
    f"{body}\n"
    "\\bottomrule\n"
    "\\end{tabular}}%\n"
    "\\caption{Effect of pooling strategy on test-set performance for both models, in both single-chain and cross-chain contexts}\n"
    "\\label{tab:pooling_comparison_combined}\n"
    "\\end{table}\n"
)
print(latex_str)

\begin{table}
\centering
\resizebox{\linewidth}{!}{%
\begin{tabular}{llcccc}
\toprule
Model & Pooling Type & Accuracy (\%) & Precision (\%) & Recall (\%) & F1-Score (\%) \\
\midrule
\multirow{4}{*}{DeepSAD-based (Single-Chain)} & Mean Pooling & 97.14 $\pm$ 01.39 & 93.92 $\pm$ 02.49 & 98.21 $\pm$ 00.87 & 95.81 $\pm$ 01.92 \\
 & Max Pooling & 97.34 $\pm$ 01.27 & 94.29 $\pm$ 02.35 & 98.34 $\pm$ 00.79 & 96.09 $\pm$ 01.77 \\
 & Sum Pooling & 97.86 $\pm$ 00.75 & 95.22 $\pm$ 01.51 & 98.66 $\pm$ 00.47 & 96.80 $\pm$ 01.09 \\
 & Mean + Max Pooling & 97.45 $\pm$ 01.33 & 94.50 $\pm$ 02.49 & 98.40 $\pm$ 00.83 & 96.24 $\pm$ 01.87 \\
\midrule
\multirow{4}{*}{DeepSAD-based (Cross-Chain)} & Mean Pooling & 99.24 $\pm$ 00.64 & 96.72 $\pm$ 03.96 & 97.65 $\pm$ 01.75 & 97.08 $\pm$ 02.41 \\
 & Max Pooling & 99.34 $\pm$ 00.48 & 97.26 $\pm$ 03.15 & 97.70 $\pm$ 01.69 & 97.41 $\pm$ 01.87 \\
 & Sum Pooling & 99.05 $\pm$ 00.60 & 95.96 $\pm$ 03.61 & 96.93 $\pm$ 02.49 & 96.32 $\pm$ 02.27 \\
 & Mean + Max Pooling & 99.43 $\pm$ 00.55 & 97.31 $\pm$ 03.19 & 98.37 $\pm$ 01.81 & 97.78 $\pm$ 02.14 \\
\bottomrule
\end{tabular}}%
\caption{Effect of pooling strategy on test-set performance for both models, in both single-chain and cross-chain contexts}
\label{tab:pooling_comparison_combined}
\end{table}